object frmMainFCC: TfrmMainFCC
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'FCC'
  ClientHeight = 1024
  ClientWidth = 1280
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesigned
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnPaint = FormPaint
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Label6: TLabel
    Left = 28
    Top = 235
    Width = 39
    Height = 16
    Caption = 'Radar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label16: TLabel
    Left = 132
    Top = 235
    Width = 24
    Height = 16
    Caption = '----'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object pnlUpper: TPanel
    Left = 0
    Top = -1
    Width = 1280
    Height = 1027
    TabOrder = 0
    object lblRulerBottomLeft10: TLabel
      Left = 265
      Top = 507
      Width = 12
      Height = 13
      Caption = '10'
    end
    object lblRulerBottomLeft20: TLabel
      Left = 199
      Top = 507
      Width = 12
      Height = 13
      Caption = '20'
    end
    object lblRulerBottomLeft30: TLabel
      Left = 137
      Top = 507
      Width = 12
      Height = 13
      Caption = '30'
    end
    object lblRulerBottomLeft40: TLabel
      Left = 75
      Top = 507
      Width = 12
      Height = 13
      Caption = '40'
    end
    object lblRulerRight0: TLabel
      Left = 667
      Top = 245
      Width = 12
      Height = 13
      AutoSize = False
      Caption = '0'
    end
    object lblRulerRightTop10: TLabel
      Left = 664
      Top = 183
      Width = 12
      Height = 13
      Caption = '10'
    end
    object lblRulerRightTop20: TLabel
      Left = 667
      Top = 118
      Width = 12
      Height = 13
      Caption = '20'
    end
    object lblRulerRightBtm10: TLabel
      Left = 664
      Top = 309
      Width = 12
      Height = 13
      Caption = '10'
    end
    object lblRulerRightBtm20: TLabel
      Left = 664
      Top = 374
      Width = 12
      Height = 13
      Caption = '20'
    end
    object lblRulerRightBtm30: TLabel
      Left = 663
      Top = 436
      Width = 12
      Height = 13
      Caption = '30'
    end
    object lblRulerRightTop30: TLabel
      Left = 667
      Top = 53
      Width = 12
      Height = 13
      Caption = '30'
    end
    object pnlSituationZone: TPanel
      Left = 684
      Top = 33
      Width = 596
      Height = 467
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      BevelOuter = bvNone
      Color = clMedGray
      ParentBackground = False
      TabOrder = 0
      object imgFcc1Image: TImage
        Left = 851
        Top = 690
        Width = 58
        Height = 87
        Stretch = True
      end
      object imgBackgrounSituationZone: TImage
        Left = 0
        Top = 0
        Width = 596
        Height = 467
        Align = alClient
        ExplicitLeft = 1
        ExplicitTop = 1
        ExplicitWidth = 822
        ExplicitHeight = 798
      end
      object lblMap48Km: TLabel
        Left = 92
        Top = 43
        Width = 32
        Height = 16
        Caption = '48Km'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblMap24Km: TLabel
        Left = 92
        Top = 74
        Width = 32
        Height = 16
        Caption = '24Km'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblMap12Km: TLabel
        Left = 92
        Top = 105
        Width = 32
        Height = 16
        Caption = '12Km'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblMap6Km: TLabel
        Left = 99
        Top = 136
        Width = 25
        Height = 16
        Caption = '6Km'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblMap3Km: TLabel
        Left = 103
        Top = 167
        Width = 25
        Height = 16
        Caption = '3Km'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblMap1point5Km: TLabel
        Left = 92
        Top = 198
        Width = 36
        Height = 16
        Caption = '1.5Km'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object imgCompas: TImage
        Left = 146
        Top = 8
        Width = 80
        Height = 80
        Visible = False
        OnClick = imgCompasClick
      end
      object lblMapLat: TLabel
        Left = 847
        Top = 926
        Width = 18
        Height = 13
        Caption = 'LAT'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clPurple
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblMapLon: TLabel
        Left = 847
        Top = 944
        Width = 20
        Height = 13
        Caption = 'LON'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clPurple
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object btnMapIncrement: TButton
        Left = 27
        Top = 8
        Width = 46
        Height = 25
        Caption = '+'
        TabOrder = 1
        OnClick = btnMapIncrementClick
      end
      object btnMapDecrement: TButton
        Left = 27
        Top = 225
        Width = 46
        Height = 25
        Caption = '-'
        TabOrder = 2
        OnClick = btnMapDecrementClick
      end
      object pnlMap48km: TPanel
        Tag = 5
        Left = 11
        Top = 39
        Width = 75
        Height = 25
        BevelOuter = bvNone
        Color = clAqua
        ParentBackground = False
        TabOrder = 3
        OnClick = pnlMapRangeClick
      end
      object pnlMap24km: TPanel
        Tag = 4
        Left = 11
        Top = 70
        Width = 75
        Height = 25
        BevelOuter = bvNone
        Color = clAqua
        ParentBackground = False
        TabOrder = 4
        OnClick = pnlMapRangeClick
      end
      object pnlMap12km: TPanel
        Tag = 3
        Left = 11
        Top = 101
        Width = 75
        Height = 25
        BevelOuter = bvNone
        Color = clAqua
        ParentBackground = False
        TabOrder = 5
        OnClick = pnlMapRangeClick
      end
      object pnlMap6km: TPanel
        Tag = 2
        Left = 11
        Top = 132
        Width = 75
        Height = 25
        BevelOuter = bvNone
        Color = clAqua
        ParentBackground = False
        TabOrder = 6
        OnClick = pnlMapRangeClick
      end
      object pnlMap3km: TPanel
        Tag = 1
        Left = 11
        Top = 163
        Width = 75
        Height = 25
        BevelOuter = bvNone
        Color = clAqua
        ParentBackground = False
        TabOrder = 7
        OnClick = pnlMapRangeClick
      end
      object pnlMap1point5km: TPanel
        Left = 11
        Top = 194
        Width = 75
        Height = 25
        BevelOuter = bvNone
        Color = clAqua
        ParentBackground = False
        TabOrder = 8
        OnClick = pnlMapRangeClick
      end
      object acbxDisRing: TAdvOfficeCheckBox
        Tag = 1
        Left = 767
        Top = 47
        Width = 120
        Height = 25
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clYellow
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 9
        Visible = False
        OnClick = acbxTargetParaClick
        Alignment = taLeftJustify
        Caption = 'Dis Ring'
        ReturnIsTab = False
        Version = '1.6.1.0'
      end
      object acbxShootArea: TAdvOfficeCheckBox
        Tag = 2
        Left = 767
        Top = 72
        Width = 120
        Height = 25
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clYellow
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 10
        Visible = False
        OnClick = acbxTargetParaClick
        Alignment = taLeftJustify
        Caption = 'Shoot Area'
        ReturnIsTab = False
        Version = '1.6.1.0'
      end
      object acbxTrackerArea: TAdvOfficeCheckBox
        Tag = 3
        Left = 767
        Top = 97
        Width = 124
        Height = 25
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clYellow
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 11
        Visible = False
        OnClick = acbxTargetParaClick
        Alignment = taLeftJustify
        Caption = 'Tracker Area'
        ReturnIsTab = False
        Version = '1.6.1.0'
      end
      object acbxTargetPara: TAdvOfficeCheckBox
        Left = 767
        Top = 22
        Width = 120
        Height = 25
        Checked = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clYellow
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 12
        Visible = False
        OnClick = acbxTargetParaClick
        Alignment = taLeftJustify
        Caption = 'Target Para'
        ReturnIsTab = False
        State = cbChecked
        Version = '1.6.1.0'
      end
      object FMap: TMap
        Left = 0
        Top = 0
        Width = 596
        Height = 467
        ParentColor = False
        Align = alClient
        TabOrder = 0
        Visible = False
        OnMouseUp = FMapMouseUp
        OnMouseMove = FMapMouseMove
        OnMouseDown = FMapMouseDown
        OnDrawUserLayer = FMapDrawUserLayer
        ExplicitTop = 2
        ExplicitWidth = 592
        ExplicitHeight = 463
        ControlData = {
          8A1A0600993D00004430000001000000FFFFFF000D47656F44696374696F6E61
          727905456D70747900E8030000000000000000000002000E001E000000000000
          0000000000000000000000000000000000000000000600010000000000500001
          010000640000000001F4010000050000800C000000000000000000000000FFFF
          FF000100000000000000000000000000000000000000000000000352E30B918F
          CE119DE300AA004BB851010000009001407E050005417269616C000352E30B91
          8FCE119DE300AA004BB851010000009001348C030005417269616C0000000000
          00000000000000000000000000000000000000000000000000000000000000FF
          FFFF000000000000000001370000000000FFFFFF000000000000000352E30B91
          8FCE119DE300AA004BB851010000009001DC7C010005417269616C000352E30B
          918FCE119DE300AA004BB851010200009001A42C02000B4D61702053796D626F
          6C730000000000000001000100FFFFFF000200FFFFFF00000000000001000000
          01000118010000486C8F2B01000000EC99C1771C000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000002
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          8076C000000000008056C0000000000080764000000000008056400100000018
          010000486C8F2B01000000880300C01C00000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000200000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000E8E197009D6A84751F
          00000000000000806A8475780AE81050CF8B6A28E29700000000000000000000
          000088B3400000000000408F400001000001}
      end
    end
    object pnlViewer3D: TPanel
      Left = 8
      Top = 1
      Width = 649
      Height = 501
      Caption = 'pnlViewer3D'
      Color = clBlack
      ParentBackground = False
      TabOrder = 1
      object Shape1: TShape
        Left = 325
        Top = 0
        Width = 1
        Height = 501
        Pen.Color = clWhite
        Visible = False
      end
      object Shape2: TShape
        Left = 0
        Top = 251
        Width = 649
        Height = 1
        Pen.Color = clWhite
        Visible = False
      end
      object tableReceiveBITE: TAdvStringGrid
        Left = 1
        Top = 24
        Width = 647
        Height = 476
        Cursor = crDefault
        Align = alBottom
        Color = clNone
        ColCount = 3
        DrawingStyle = gdsClassic
        FixedColor = clRed
        FixedCols = 0
        RowCount = 20
        FixedRows = 0
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        GradientStartColor = clBlack
        ParentFont = False
        ScrollBars = ssBoth
        TabOrder = 0
        GridFixedLineColor = clRed
        HoverRowCells = [hcNormal, hcSelected]
        ActiveCellFont.Charset = DEFAULT_CHARSET
        ActiveCellFont.Color = clWhite
        ActiveCellFont.Height = -11
        ActiveCellFont.Name = 'Tahoma'
        ActiveCellFont.Style = [fsBold]
        ActiveCellColor = clBlack
        ColumnSize.Stretch = True
        ColumnSize.StretchColumn = 1
        ControlLook.FixedGradientHoverFrom = clGray
        ControlLook.FixedGradientHoverTo = clWhite
        ControlLook.FixedGradientDownFrom = clGray
        ControlLook.FixedGradientDownTo = clSilver
        ControlLook.DropDownHeader.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownHeader.Font.Color = clWindowText
        ControlLook.DropDownHeader.Font.Height = -11
        ControlLook.DropDownHeader.Font.Name = 'Tahoma'
        ControlLook.DropDownHeader.Font.Style = []
        ControlLook.DropDownHeader.Visible = True
        ControlLook.DropDownHeader.Buttons = <>
        ControlLook.DropDownFooter.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownFooter.Font.Color = clWindowText
        ControlLook.DropDownFooter.Font.Height = -11
        ControlLook.DropDownFooter.Font.Name = 'Tahoma'
        ControlLook.DropDownFooter.Font.Style = []
        ControlLook.DropDownFooter.Visible = True
        ControlLook.DropDownFooter.Buttons = <>
        Filter = <>
        FilterDropDown.Font.Charset = DEFAULT_CHARSET
        FilterDropDown.Font.Color = clWindowText
        FilterDropDown.Font.Height = -11
        FilterDropDown.Font.Name = 'Tahoma'
        FilterDropDown.Font.Style = []
        FilterDropDown.TextChecked = 'Checked'
        FilterDropDown.TextUnChecked = 'Unchecked'
        FilterDropDownClear = '(All)'
        FilterEdit.TypeNames.Strings = (
          'Starts with'
          'Ends with'
          'Contains'
          'Not contains'
          'Equal'
          'Not equal'
          'Larger than'
          'Smaller than'
          'Clear')
        FixedRowHeight = 22
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWhite
        FixedFont.Height = -11
        FixedFont.Name = 'Tahoma'
        FixedFont.Style = [fsBold]
        FloatFormat = '%.2f'
        HoverButtons.Buttons = <>
        HoverButtons.Position = hbLeftFromColumnLeft
        HTMLSettings.ImageFolder = 'images'
        HTMLSettings.ImageBaseName = 'img'
        PrintSettings.DateFormat = 'dd/mm/yyyy'
        PrintSettings.Font.Charset = DEFAULT_CHARSET
        PrintSettings.Font.Color = clWindowText
        PrintSettings.Font.Height = -11
        PrintSettings.Font.Name = 'Tahoma'
        PrintSettings.Font.Style = []
        PrintSettings.FixedFont.Charset = DEFAULT_CHARSET
        PrintSettings.FixedFont.Color = clWindowText
        PrintSettings.FixedFont.Height = -11
        PrintSettings.FixedFont.Name = 'Tahoma'
        PrintSettings.FixedFont.Style = []
        PrintSettings.HeaderFont.Charset = DEFAULT_CHARSET
        PrintSettings.HeaderFont.Color = clWindowText
        PrintSettings.HeaderFont.Height = -11
        PrintSettings.HeaderFont.Name = 'Tahoma'
        PrintSettings.HeaderFont.Style = []
        PrintSettings.FooterFont.Charset = DEFAULT_CHARSET
        PrintSettings.FooterFont.Color = clWindowText
        PrintSettings.FooterFont.Height = -11
        PrintSettings.FooterFont.Name = 'Tahoma'
        PrintSettings.FooterFont.Style = []
        PrintSettings.PageNumSep = '/'
        SearchFooter.FindNextCaption = 'Find &next'
        SearchFooter.FindPrevCaption = 'Find &previous'
        SearchFooter.Font.Charset = DEFAULT_CHARSET
        SearchFooter.Font.Color = clWindowText
        SearchFooter.Font.Height = -11
        SearchFooter.Font.Name = 'Tahoma'
        SearchFooter.Font.Style = []
        SearchFooter.HighLightCaption = 'Highlight'
        SearchFooter.HintClose = 'Close'
        SearchFooter.HintFindNext = 'Find next occurrence'
        SearchFooter.HintFindPrev = 'Find previous occurrence'
        SearchFooter.HintHighlight = 'Highlight occurrences'
        SearchFooter.MatchCaseCaption = 'Match case'
        SearchFooter.ResultFormat = '(%d of %d)'
        SelectionColor = clBlack
        SelectionTextColor = clWhite
        ShowDesignHelper = False
        SortSettings.DefaultFormat = ssAutomatic
        Version = '8.4.7.0'
        ColWidths = (
          64
          515
          64)
      end
      object pnlReceiveBiteHeader: TPanel
        Left = 1
        Top = 1
        Width = 647
        Height = 23
        Align = alClient
        Caption = 'Receive BITE'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -15
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
      end
    end
    object advRulerBottomRight: TAdvRangeSlider
      Left = 325
      Top = 501
      Width = 265
      Height = 30
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      BorderColor = clNone
      BorderColorDisabled = clNone
      ColorTo = clNone
      ColorDisabled = clNone
      ColorDisabledTo = clNone
      Direction = gdHorizontal
      DragCursor = crArrow
      Color = clNone
      Max = 40
      ParentShowHint = False
      PositionRight = 40
      ShowHint = False
      Slider.BorderColor = clNone
      Slider.BorderColorDisabled = clNone
      Slider.Color = clNone
      Slider.ColorTo = clNone
      Slider.ColorDisabled = clNone
      Slider.ColorDisabledTo = clBlack
      Slider.ColorCompleted = clNone
      Slider.ColorCompletedTo = clNone
      Slider.ColorCompletedDisabled = clNone
      Slider.ColorCompletedDisabledTo = clNone
      Slider.Direction = gdHorizontal
      Slider.Offset = -12
      Slider.ColorRemaining = clNone
      Slider.ColorRemainingTo = clNone
      Slider.ColorRemainingDisabled = clNone
      Slider.ColorRemainingDisabledTo = clNone
      TabOrder = 2
      ThumbLeft.BorderColor = clNone
      ThumbLeft.BorderColorHot = 10079963
      ThumbLeft.BorderColorDown = 4548219
      ThumbLeft.BorderColorDisabled = clBlack
      ThumbLeft.Color = clNone
      ThumbLeft.ColorTo = 16178633
      ThumbLeft.ColorDown = 7778289
      ThumbLeft.ColorDownTo = 4296947
      ThumbLeft.ColorHot = 15465983
      ThumbLeft.ColorHotTo = 11332863
      ThumbLeft.ColorDisabled = clBlack
      ThumbLeft.ColorDisabledTo = clBlack
      ThumbLeft.ColorMirror = 15586496
      ThumbLeft.ColorMirrorTo = 16245200
      ThumbLeft.ColorMirrorHot = 5888767
      ThumbLeft.ColorMirrorHotTo = 10807807
      ThumbLeft.ColorMirrorDown = 946929
      ThumbLeft.ColorMirrorDownTo = 5021693
      ThumbLeft.ColorMirrorDisabled = clBlack
      ThumbLeft.ColorMirrorDisabledTo = clBlack
      ThumbLeft.Gradient = ggVertical
      ThumbLeft.GradientMirror = ggRadial
      ThumbLeft.Shape = tsPointer
      ThumbRight.BorderColor = clNone
      ThumbRight.BorderColorHot = 10079963
      ThumbRight.BorderColorDown = 4548219
      ThumbRight.BorderColorDisabled = clNone
      ThumbRight.Color = clNone
      ThumbRight.ColorTo = 16178633
      ThumbRight.ColorDown = 7778289
      ThumbRight.ColorDownTo = 4296947
      ThumbRight.ColorHot = 15465983
      ThumbRight.ColorHotTo = 11332863
      ThumbRight.ColorDisabled = clBlack
      ThumbRight.ColorDisabledTo = clBlack
      ThumbRight.ColorMirror = 15586496
      ThumbRight.ColorMirrorTo = 16245200
      ThumbRight.ColorMirrorHot = 5888767
      ThumbRight.ColorMirrorHotTo = 10807807
      ThumbRight.ColorMirrorDown = 946929
      ThumbRight.ColorMirrorDownTo = 5021693
      ThumbRight.ColorMirrorDisabled = clBlack
      ThumbRight.ColorMirrorDisabledTo = clBlack
      ThumbRight.Gradient = ggVertical
      ThumbRight.GradientMirror = ggRadial
      ThumbRight.Size = 0
      ThumbRight.Width = 0
      ThumbRight.Shape = tsPointer
      TickMark.Color = clBlack
      TickMark.ColorDisabled = clBlack
      TickMark.Font.Charset = DEFAULT_CHARSET
      TickMark.Font.Color = clWindowText
      TickMark.Font.Height = -11
      TickMark.Font.Name = 'Tahoma'
      TickMark.Font.Style = []
      TickMark.ShowText = True
      TickMark.ShowImageAtSteps = 10
      TickMark.Size = 6
      TrackHint = False
      TrackLabel.Position = lpBottomLeft
      TrackLabel.Font.Charset = DEFAULT_CHARSET
      TrackLabel.Font.Color = clWindowText
      TrackLabel.Font.Height = -11
      TrackLabel.Font.Name = 'Tahoma'
      TrackLabel.Font.Style = []
      TrackLabel.Format = 'PosLeft: %d  PosRight: %d'
      TrackLabel.Spacing = 0
      Version = '1.6.10.2'
    end
    object advSliderBottomLeft: TAdvRangeSlider
      Left = 77
      Top = 501
      Width = 265
      Height = 9
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      BorderColor = clNone
      BorderColorDisabled = clNone
      ColorTo = clNone
      ColorDisabled = clNone
      ColorDisabledTo = clNone
      Direction = gdHorizontal
      DragCursor = crArrow
      Color = clNone
      Max = 40
      ParentShowHint = False
      PositionLeft = 40
      PositionRight = 40
      ShowHint = False
      Slider.BorderColor = clNone
      Slider.BorderColorDisabled = clNone
      Slider.Color = clNone
      Slider.ColorTo = clNone
      Slider.ColorDisabled = clNone
      Slider.ColorDisabledTo = clBlack
      Slider.ColorCompleted = clNone
      Slider.ColorCompletedTo = clNone
      Slider.ColorCompletedDisabled = clNone
      Slider.ColorCompletedDisabledTo = clNone
      Slider.Direction = gdHorizontal
      Slider.Offset = -12
      Slider.ColorRemaining = clNone
      Slider.ColorRemainingTo = clNone
      Slider.ColorRemainingDisabled = clNone
      Slider.ColorRemainingDisabledTo = clNone
      TabOrder = 3
      ThumbLeft.BorderColor = clNone
      ThumbLeft.BorderColorHot = 10079963
      ThumbLeft.BorderColorDown = 4548219
      ThumbLeft.BorderColorDisabled = clBlack
      ThumbLeft.Color = clNone
      ThumbLeft.ColorTo = 16178633
      ThumbLeft.ColorDown = 7778289
      ThumbLeft.ColorDownTo = 4296947
      ThumbLeft.ColorHot = 15465983
      ThumbLeft.ColorHotTo = 11332863
      ThumbLeft.ColorDisabled = clBlack
      ThumbLeft.ColorDisabledTo = clBlack
      ThumbLeft.ColorMirror = 15586496
      ThumbLeft.ColorMirrorTo = 16245200
      ThumbLeft.ColorMirrorHot = 5888767
      ThumbLeft.ColorMirrorHotTo = 10807807
      ThumbLeft.ColorMirrorDown = 946929
      ThumbLeft.ColorMirrorDownTo = 5021693
      ThumbLeft.ColorMirrorDisabled = clBlack
      ThumbLeft.ColorMirrorDisabledTo = clBlack
      ThumbLeft.Gradient = ggVertical
      ThumbLeft.GradientMirror = ggRadial
      ThumbLeft.Shape = tsPointer
      ThumbRight.BorderColor = clNone
      ThumbRight.BorderColorHot = 10079963
      ThumbRight.BorderColorDown = 4548219
      ThumbRight.BorderColorDisabled = clNone
      ThumbRight.Color = clNone
      ThumbRight.ColorTo = 16178633
      ThumbRight.ColorDown = 7778289
      ThumbRight.ColorDownTo = 4296947
      ThumbRight.ColorHot = 15465983
      ThumbRight.ColorHotTo = 11332863
      ThumbRight.ColorDisabled = clBlack
      ThumbRight.ColorDisabledTo = clBlack
      ThumbRight.ColorMirror = 15586496
      ThumbRight.ColorMirrorTo = 16245200
      ThumbRight.ColorMirrorHot = 5888767
      ThumbRight.ColorMirrorHotTo = 10807807
      ThumbRight.ColorMirrorDown = 946929
      ThumbRight.ColorMirrorDownTo = 5021693
      ThumbRight.ColorMirrorDisabled = clBlack
      ThumbRight.ColorMirrorDisabledTo = clBlack
      ThumbRight.Gradient = ggVertical
      ThumbRight.GradientMirror = ggRadial
      ThumbRight.Size = 0
      ThumbRight.Width = 0
      ThumbRight.Shape = tsPointer
      TickMark.Color = clBlack
      TickMark.ColorDisabled = clBlack
      TickMark.Font.Charset = DEFAULT_CHARSET
      TickMark.Font.Color = clWindowText
      TickMark.Font.Height = -11
      TickMark.Font.Name = 'Tahoma'
      TickMark.Font.Style = []
      TickMark.RotateFontVert = False
      TickMark.ShowImageAtSteps = 10
      TickMark.Size = 6
      TrackHint = False
      TrackLabel.Position = lpBottomLeft
      TrackLabel.Font.Charset = DEFAULT_CHARSET
      TrackLabel.Font.Color = clWindowText
      TrackLabel.Font.Height = -11
      TrackLabel.Font.Name = 'Tahoma'
      TrackLabel.Font.Style = []
      TrackLabel.Format = 'PosLeft: %d  PosRight: %d'
      TrackLabel.Spacing = 0
      Version = '1.6.10.2'
    end
    object AdvRangeSlider1: TAdvRangeSlider
      Left = 657
      Top = 52
      Width = 7
      Height = 399
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      BorderColor = clNone
      BorderColorDisabled = clNone
      ColorTo = clNone
      ColorDisabled = clNone
      ColorDisabledTo = clNone
      Direction = gdHorizontal
      DragCursor = crArrow
      Color = clNone
      Max = 60
      Orientation = trVertical
      ParentShowHint = False
      PositionRight = 40
      ShowHint = False
      Slider.BorderColor = clNone
      Slider.BorderColorDisabled = clNone
      Slider.Color = clNone
      Slider.ColorTo = clNone
      Slider.ColorDisabled = clNone
      Slider.ColorDisabledTo = clBlack
      Slider.ColorCompleted = clNone
      Slider.ColorCompletedTo = clNone
      Slider.ColorCompletedDisabled = clNone
      Slider.ColorCompletedDisabledTo = clNone
      Slider.Direction = gdHorizontal
      Slider.Offset = -12
      Slider.ColorRemaining = clNone
      Slider.ColorRemainingTo = clNone
      Slider.ColorRemainingDisabled = clNone
      Slider.ColorRemainingDisabledTo = clNone
      TabOrder = 4
      ThumbLeft.BorderColor = clNone
      ThumbLeft.BorderColorHot = 10079963
      ThumbLeft.BorderColorDown = 4548219
      ThumbLeft.BorderColorDisabled = clBlack
      ThumbLeft.Color = clNone
      ThumbLeft.ColorTo = 16178633
      ThumbLeft.ColorDown = 7778289
      ThumbLeft.ColorDownTo = 4296947
      ThumbLeft.ColorHot = 15465983
      ThumbLeft.ColorHotTo = 11332863
      ThumbLeft.ColorDisabled = clBlack
      ThumbLeft.ColorDisabledTo = clBlack
      ThumbLeft.ColorMirror = 15586496
      ThumbLeft.ColorMirrorTo = 16245200
      ThumbLeft.ColorMirrorHot = 5888767
      ThumbLeft.ColorMirrorHotTo = 10807807
      ThumbLeft.ColorMirrorDown = 946929
      ThumbLeft.ColorMirrorDownTo = 5021693
      ThumbLeft.ColorMirrorDisabled = clBlack
      ThumbLeft.ColorMirrorDisabledTo = clBlack
      ThumbLeft.Gradient = ggVertical
      ThumbLeft.GradientMirror = ggRadial
      ThumbLeft.Shape = tsPointer
      ThumbRight.BorderColor = clNone
      ThumbRight.BorderColorHot = 10079963
      ThumbRight.BorderColorDown = 4548219
      ThumbRight.BorderColorDisabled = clNone
      ThumbRight.Color = clNone
      ThumbRight.ColorTo = 16178633
      ThumbRight.ColorDown = 7778289
      ThumbRight.ColorDownTo = 4296947
      ThumbRight.ColorHot = 15465983
      ThumbRight.ColorHotTo = 11332863
      ThumbRight.ColorDisabled = clBlack
      ThumbRight.ColorDisabledTo = clBlack
      ThumbRight.ColorMirror = 15586496
      ThumbRight.ColorMirrorTo = 16245200
      ThumbRight.ColorMirrorHot = 5888767
      ThumbRight.ColorMirrorHotTo = 10807807
      ThumbRight.ColorMirrorDown = 946929
      ThumbRight.ColorMirrorDownTo = 5021693
      ThumbRight.ColorMirrorDisabled = clBlack
      ThumbRight.ColorMirrorDisabledTo = clBlack
      ThumbRight.Gradient = ggVertical
      ThumbRight.GradientMirror = ggRadial
      ThumbRight.Size = 0
      ThumbRight.Width = 0
      ThumbRight.Shape = tsPointer
      TickMark.Color = clBlack
      TickMark.ColorDisabled = clBlack
      TickMark.Font.Charset = DEFAULT_CHARSET
      TickMark.Font.Color = clWindowText
      TickMark.Font.Height = -11
      TickMark.Font.Name = 'Tahoma'
      TickMark.Font.Style = []
      TickMark.RotateFontVert = False
      TickMark.ShowImageAtSteps = 10
      TickMark.Size = 6
      TrackHint = False
      TrackLabel.Position = lpBottomLeft
      TrackLabel.Font.Charset = DEFAULT_CHARSET
      TrackLabel.Font.Color = clWindowText
      TrackLabel.Font.Height = -11
      TrackLabel.Font.Name = 'Tahoma'
      TrackLabel.Font.Style = []
      TrackLabel.Format = 'PosLeft: %d  PosRight: %d'
      TrackLabel.Spacing = 0
      Version = '1.6.10.2'
    end
  end
  object pnlBite: TPanel
    Left = 603
    Top = 704
    Width = 677
    Height = 321
    ParentBackground = False
    TabOrder = 2
    object pnlHaeaderBite: TPanel
      Left = 1
      Top = 1
      Width = 675
      Height = 28
      Align = alTop
      Caption = 'BITE'
      Color = clHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
    end
    object AdvPageControl1: TAdvPageControl
      Left = 1
      Top = 29
      Width = 675
      Height = 291
      ActivePage = AdvTabMR35
      ActiveFont.Charset = DEFAULT_CHARSET
      ActiveFont.Color = clWindowText
      ActiveFont.Height = -11
      ActiveFont.Name = 'Tahoma'
      ActiveFont.Style = []
      Align = alClient
      DoubleBuffered = True
      TabBackGroundColor = clBtnFace
      TabMargin.RightMargin = 0
      TabOverlap = 0
      Version = '2.0.2.0'
      PersistPagesState.Location = plRegistry
      PersistPagesState.Enabled = False
      TabOrder = 1
      object AdvTabMR35: TAdvTabSheet
        Caption = 'MR35'
        Color = clBtnFace
        ColorTo = clNone
        TabColor = clBtnFace
        TabColorTo = clNone
        object lblMR35FCC2: TLabel
          Left = 3
          Top = 33
          Width = 30
          Height = 16
          Caption = 'FCC2'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblMR35FCC2Val: TLabel
          Left = 176
          Top = 33
          Width = 57
          Height = 16
          Caption = 'Undefined'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblMR35Time: TLabel
          Left = 3
          Top = 11
          Width = 29
          Height = 16
          Caption = 'Time'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblMR35TimeVal: TLabel
          Left = 176
          Top = 10
          Width = 57
          Height = 16
          Caption = 'Undefined'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblMR35MR35: TLabel
          Left = 3
          Top = 58
          Width = 32
          Height = 16
          Caption = 'MR35'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblMR35MR35Val: TLabel
          Left = 176
          Top = 58
          Width = 41
          Height = 16
          Caption = 'Normal'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
      end
      object AdvTabTrans: TAdvTabSheet
        Caption = 'Trans'
        Color = clBtnFace
        ColorTo = clNone
        TabColor = clBtnFace
        TabColorTo = clNone
      end
      object AdvTabRev: TAdvTabSheet
        Caption = 'Rev'
        Color = clBtnFace
        ColorTo = clNone
        TabColor = clBtnFace
        TabColorTo = clNone
      end
      object AdvTabServo: TAdvTabSheet
        Caption = 'Servo'
        Color = clBtnFace
        ColorTo = clNone
        TabColor = clBtnFace
        TabColorTo = clNone
      end
      object AdvTabCon: TAdvTabSheet
        Caption = 'Con'
        Color = clBtnFace
        ColorTo = clNone
        TabColor = clBtnFace
        TabColorTo = clNone
      end
      object AdvTabTVLS: TAdvTabSheet
        Caption = 'TV-LS'
        Color = clBtnFace
        ColorTo = clNone
        TabColor = clBtnFace
        TabColorTo = clNone
      end
    end
  end
  object pnlExteriorData: TPanel
    Left = 603
    Top = 505
    Width = 678
    Height = 202
    ParentBackground = False
    TabOrder = 1
    object pnlHeaderExteriorData: TPanel
      Left = 1
      Top = 1
      Width = 676
      Height = 28
      Align = alTop
      Caption = 'EXTERIOR DATA && TARGET DESIGNATION'
      Color = clHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
    end
    object pnlExteriorDataLeft: TPanel
      Left = 1
      Top = 29
      Width = 339
      Height = 172
      Align = alLeft
      TabOrder = 1
      object advControlPageExtDat: TAdvPageControl
        Left = 1
        Top = 1
        Width = 337
        Height = 170
        ActivePage = advTabNAVI
        ActiveFont.Charset = DEFAULT_CHARSET
        ActiveFont.Color = clWindowText
        ActiveFont.Height = -11
        ActiveFont.Name = 'Tahoma'
        ActiveFont.Style = []
        Align = alClient
        DoubleBuffered = True
        TabBackGroundColor = clBtnFace
        TabMargin.RightMargin = 0
        TabOverlap = 0
        Version = '2.0.2.0'
        PersistPagesState.Location = plRegistry
        PersistPagesState.Enabled = False
        TabOrder = 0
        object advTabNAVI: TAdvTabSheet
          Caption = 'NAVI'
          Color = clBtnFace
          ColorTo = clNone
          TabColor = clBtnFace
          TabColorTo = clNone
          object lblHeadingNAVI: TLabel
            Left = 3
            Top = 13
            Width = 46
            Height = 16
            Caption = 'Heading'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblHeadingNAVIsat: TLabel
            Left = 201
            Top = 11
            Width = 10
            Height = 16
            Caption = ' '#176
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblSpeedNAVI: TLabel
            Left = 3
            Top = 45
            Width = 36
            Height = 16
            Caption = 'Speed'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblSpeedNAVIsat: TLabel
            Left = 201
            Top = 44
            Width = 13
            Height = 16
            Caption = 'kn'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblRollNAVI: TLabel
            Left = 3
            Top = 79
            Width = 21
            Height = 16
            Caption = 'Roll'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblRollNAVIsat: TLabel
            Left = 200
            Top = 76
            Width = 10
            Height = 16
            Caption = ' '#176
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblPitchNAVI: TLabel
            Left = 4
            Top = 109
            Width = 27
            Height = 16
            Caption = 'Pitch'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblPitchNAVIsat: TLabel
            Left = 200
            Top = 107
            Width = 10
            Height = 16
            Caption = ' '#176
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object EdtHeadingNAVIVal: TEdit
            Left = 84
            Top = 10
            Width = 115
            Height = 24
            Alignment = taCenter
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 0
            Text = '0.000'
          end
          object EdtSpeedNAVIVal: TEdit
            Left = 84
            Top = 41
            Width = 115
            Height = 24
            Alignment = taCenter
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 1
            Text = '0.00'
          end
          object EdtRollNAVIVal: TEdit
            Left = 84
            Top = 73
            Width = 115
            Height = 24
            Alignment = taCenter
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
            Text = '0.000'
          end
          object EdtPitchNAVIVal: TEdit
            Left = 84
            Top = 105
            Width = 115
            Height = 24
            Alignment = taCenter
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 3
            Text = '0.000'
          end
        end
        object AdvTabIND: TAdvTabSheet
          Caption = 'IND'
          Color = clBtnFace
          ColorTo = clNone
          TabColor = clBtnFace
          TabColorTo = clNone
          object lblIDTargetIND: TLabel
            Left = 3
            Top = 13
            Width = 54
            Height = 16
            Caption = 'Batch No.'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblHeadingIND: TLabel
            Left = 3
            Top = 77
            Width = 46
            Height = 16
            Caption = 'Heading'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblHeadingINDsat: TLabel
            Left = 200
            Top = 76
            Width = 10
            Height = 16
            Caption = ' '#176
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblSpeedIND: TLabel
            Left = 3
            Top = 45
            Width = 36
            Height = 16
            Caption = 'Speed'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object lblSpeedINDsat: TLabel
            Left = 201
            Top = 44
            Width = 13
            Height = 16
            Caption = 'kn'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
          object edtIDTargetVal: TEdit
            Left = 84
            Top = 11
            Width = 115
            Height = 24
            Alignment = taCenter
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 0
            Text = '0'
          end
          object edtHeadingINDVal: TEdit
            Left = 84
            Top = 74
            Width = 115
            Height = 24
            Alignment = taCenter
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 1
            Text = '0.000'
          end
          object edtSpeedINDVal: TEdit
            Left = 84
            Top = 43
            Width = 115
            Height = 24
            Alignment = taCenter
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ReadOnly = True
            TabOrder = 2
            Text = '0.00'
          end
        end
        object AdvTabDEVI: TAdvTabSheet
          Caption = 'DEVI'
          Color = clBtnFace
          ColorTo = clNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabColor = clBtnFace
          TabColorTo = clNone
        end
      end
    end
    object pnlExteriorDataRight: TPanel
      Left = 340
      Top = 29
      Width = 337
      Height = 172
      Align = alClient
      TabOrder = 2
      object lblBatchNoDesig: TLabel
        Left = 11
        Top = 57
        Width = 50
        Height = 16
        Caption = 'Batch No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblHeadingDesig: TLabel
        Left = 11
        Top = 87
        Width = 46
        Height = 16
        Caption = 'Heading'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblSpeedDesig: TLabel
        Left = 11
        Top = 117
        Width = 36
        Height = 16
        Caption = 'Speed'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object edtBatchNoDesig: TEdit
        Left = 92
        Top = 54
        Width = 115
        Height = 24
        Alignment = taCenter
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 0
        Text = '0'
      end
      object edtHeadingDesig: TEdit
        Left = 92
        Top = 84
        Width = 115
        Height = 24
        Alignment = taCenter
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 1
        Text = '0.000'
      end
      object edtSpeedDesig: TEdit
        Left = 92
        Top = 114
        Width = 115
        Height = 24
        Alignment = taCenter
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        ReadOnly = True
        TabOrder = 2
        Text = '0.000'
      end
      object fbDesigTarget: TFlatButton
        Left = 11
        Top = 6
        Width = 142
        Height = 35
        Default = True
        AllowAllUp = True
        Color = clGreen
        ColorFocused = clGreen
        ColorDown = clLime
        ColorBorder = clBlack
        GroupIndex = 3
        Caption = 'DESIGT'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -17
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        ParentColor = False
        TabOrder = 3
        OnClick = fbBreakTargetClick
      end
      object fbBreakTarget: TFlatButton
        Left = 185
        Top = 6
        Width = 142
        Height = 35
        AllowAllUp = True
        Color = clGreen
        ColorFocused = clGreen
        ColorDown = clLime
        ColorBorder = clBlack
        GroupIndex = 3
        Caption = 'BREAK'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -17
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        ParentColor = False
        TabOrder = 4
        OnClick = fbBreakTargetClick
      end
    end
  end
  object pnlPosture: TPanel
    Left = 684
    Top = 3
    Width = 596
    Height = 28
    Caption = 'POSTURE'
    Color = clHighlight
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 3
  end
  object pnlLaser: TPanel
    Left = 0
    Top = 525
    Width = 599
    Height = 137
    BevelInner = bvLowered
    ParentBackground = False
    TabOrder = 4
    object lblKmLaser: TLabel
      Left = 544
      Top = 116
      Width = 13
      Height = 13
      Caption = 'km'
    end
    object advRulerLaser: TAdvRangeSlider
      Left = 0
      Top = 108
      Width = 545
      Height = 30
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      BorderColor = clNone
      BorderColorDisabled = clNone
      ColorTo = clNone
      ColorDisabled = clNone
      ColorDisabledTo = clNone
      Direction = gdHorizontal
      DragCursor = crArrow
      Color = clNone
      Max = 40
      ParentShowHint = False
      PositionRight = 40
      ShowHint = False
      Slider.BorderColor = clNone
      Slider.BorderColorDisabled = clNone
      Slider.Color = clNone
      Slider.ColorTo = clNone
      Slider.ColorDisabled = clNone
      Slider.ColorDisabledTo = clBlack
      Slider.ColorCompleted = clNone
      Slider.ColorCompletedTo = clNone
      Slider.ColorCompletedDisabled = clNone
      Slider.ColorCompletedDisabledTo = clNone
      Slider.Direction = gdHorizontal
      Slider.Offset = -12
      Slider.ColorRemaining = clNone
      Slider.ColorRemainingTo = clNone
      Slider.ColorRemainingDisabled = clNone
      Slider.ColorRemainingDisabledTo = clNone
      TabOrder = 0
      ThumbLeft.BorderColor = clNone
      ThumbLeft.BorderColorHot = 10079963
      ThumbLeft.BorderColorDown = 4548219
      ThumbLeft.BorderColorDisabled = clBlack
      ThumbLeft.Color = clNone
      ThumbLeft.ColorTo = 16178633
      ThumbLeft.ColorDown = 7778289
      ThumbLeft.ColorDownTo = 4296947
      ThumbLeft.ColorHot = 15465983
      ThumbLeft.ColorHotTo = 11332863
      ThumbLeft.ColorDisabled = clBlack
      ThumbLeft.ColorDisabledTo = clBlack
      ThumbLeft.ColorMirror = 15586496
      ThumbLeft.ColorMirrorTo = 16245200
      ThumbLeft.ColorMirrorHot = 5888767
      ThumbLeft.ColorMirrorHotTo = 10807807
      ThumbLeft.ColorMirrorDown = 946929
      ThumbLeft.ColorMirrorDownTo = 5021693
      ThumbLeft.ColorMirrorDisabled = clBlack
      ThumbLeft.ColorMirrorDisabledTo = clBlack
      ThumbLeft.Gradient = ggVertical
      ThumbLeft.GradientMirror = ggRadial
      ThumbLeft.Shape = tsPointer
      ThumbRight.BorderColor = clNone
      ThumbRight.BorderColorHot = 10079963
      ThumbRight.BorderColorDown = 4548219
      ThumbRight.BorderColorDisabled = clNone
      ThumbRight.Color = clNone
      ThumbRight.ColorTo = 16178633
      ThumbRight.ColorDown = 7778289
      ThumbRight.ColorDownTo = 4296947
      ThumbRight.ColorHot = 15465983
      ThumbRight.ColorHotTo = 11332863
      ThumbRight.ColorDisabled = clBlack
      ThumbRight.ColorDisabledTo = clBlack
      ThumbRight.ColorMirror = 15586496
      ThumbRight.ColorMirrorTo = 16245200
      ThumbRight.ColorMirrorHot = 5888767
      ThumbRight.ColorMirrorHotTo = 10807807
      ThumbRight.ColorMirrorDown = 946929
      ThumbRight.ColorMirrorDownTo = 5021693
      ThumbRight.ColorMirrorDisabled = clBlack
      ThumbRight.ColorMirrorDisabledTo = clBlack
      ThumbRight.Gradient = ggVertical
      ThumbRight.GradientMirror = ggRadial
      ThumbRight.Size = 0
      ThumbRight.Width = 0
      ThumbRight.Shape = tsPointer
      TickMark.Color = clBlack
      TickMark.ColorDisabled = clBlack
      TickMark.Font.Charset = DEFAULT_CHARSET
      TickMark.Font.Color = clWindowText
      TickMark.Font.Height = -11
      TickMark.Font.Name = 'Tahoma'
      TickMark.Font.Style = []
      TickMark.ShowText = True
      TickMark.ShowImageAtSteps = 5
      TickMark.Size = 6
      TrackHint = False
      TrackLabel.Position = lpBottomLeft
      TrackLabel.Font.Charset = DEFAULT_CHARSET
      TrackLabel.Font.Color = clWindowText
      TrackLabel.Font.Height = -11
      TrackLabel.Font.Name = 'Tahoma'
      TrackLabel.Font.Style = []
      TrackLabel.Format = 'PosLeft: %d  PosRight: %d'
      TrackLabel.Spacing = 0
      Version = '1.6.10.2'
    end
    object pnlLaserGraph: TPanel
      Left = 1
      Top = 0
      Width = 540
      Height = 105
      Color = clBlack
      ParentBackground = False
      TabOrder = 1
    end
    object pnl4X: TPanel
      Left = 547
      Top = 1
      Width = 43
      Height = 23
      BevelInner = bvLowered
      Caption = '4X'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object pnl2X: TPanel
      Left = 547
      Top = 27
      Width = 43
      Height = 23
      BevelInner = bvLowered
      Caption = '2X'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
    end
    object pnl1X: TPanel
      Left = 547
      Top = 53
      Width = 43
      Height = 23
      BevelInner = bvLowered
      Caption = '1X'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object panel12X: TPanel
      Left = 547
      Top = 79
      Width = 43
      Height = 23
      BevelInner = bvLowered
      Caption = '1/2X'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
  end
  object pnlRadar: TPanel
    Left = 1
    Top = 668
    Width = 599
    Height = 137
    BevelInner = bvLowered
    ParentBackground = False
    TabOrder = 5
    object lblKmRadar: TLabel
      Left = 444
      Top = 115
      Width = 13
      Height = 13
      Caption = 'km'
    end
    object lblRadarFC: TLabel
      Left = 488
      Top = 19
      Width = 18
      Height = 19
      Caption = 'FC'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblRadarAGC: TLabel
      Left = 478
      Top = 53
      Width = 32
      Height = 19
      Caption = 'AGC'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblRadarGate: TLabel
      Left = 463
      Top = 90
      Width = 41
      Height = 19
      Caption = 'GATE'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblRadarGATEsat: TLabel
      Left = 575
      Top = 90
      Width = 14
      Height = 19
      Caption = 'm'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object rulerRadarBottom: TAdvRangeSlider
      Left = 12
      Top = 107
      Width = 435
      Height = 30
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      BorderColor = clNone
      BorderColorDisabled = clNone
      ColorTo = clNone
      ColorDisabled = clNone
      ColorDisabledTo = clNone
      Direction = gdHorizontal
      DragCursor = crArrow
      Color = clNone
      Max = 2
      Min = -2
      ParentShowHint = False
      PositionRight = 2
      ShowHint = False
      Slider.BorderColor = clNone
      Slider.BorderColorDisabled = clNone
      Slider.Color = clNone
      Slider.ColorTo = clNone
      Slider.ColorDisabled = clNone
      Slider.ColorDisabledTo = clBlack
      Slider.ColorCompleted = clNone
      Slider.ColorCompletedTo = clNone
      Slider.ColorCompletedDisabled = clNone
      Slider.ColorCompletedDisabledTo = clNone
      Slider.Direction = gdHorizontal
      Slider.Offset = -12
      Slider.ColorRemaining = clNone
      Slider.ColorRemainingTo = clNone
      Slider.ColorRemainingDisabled = clNone
      Slider.ColorRemainingDisabledTo = clNone
      TabOrder = 0
      ThumbLeft.BorderColor = clNone
      ThumbLeft.BorderColorHot = 10079963
      ThumbLeft.BorderColorDown = 4548219
      ThumbLeft.BorderColorDisabled = clBlack
      ThumbLeft.Color = clNone
      ThumbLeft.ColorTo = 16178633
      ThumbLeft.ColorDown = 7778289
      ThumbLeft.ColorDownTo = 4296947
      ThumbLeft.ColorHot = 15465983
      ThumbLeft.ColorHotTo = 11332863
      ThumbLeft.ColorDisabled = clBlack
      ThumbLeft.ColorDisabledTo = clBlack
      ThumbLeft.ColorMirror = 15586496
      ThumbLeft.ColorMirrorTo = 16245200
      ThumbLeft.ColorMirrorHot = 5888767
      ThumbLeft.ColorMirrorHotTo = 10807807
      ThumbLeft.ColorMirrorDown = 946929
      ThumbLeft.ColorMirrorDownTo = 5021693
      ThumbLeft.ColorMirrorDisabled = clBlack
      ThumbLeft.ColorMirrorDisabledTo = clBlack
      ThumbLeft.Gradient = ggVertical
      ThumbLeft.GradientMirror = ggRadial
      ThumbLeft.Shape = tsPointer
      ThumbRight.BorderColor = clNone
      ThumbRight.BorderColorHot = 10079963
      ThumbRight.BorderColorDown = 4548219
      ThumbRight.BorderColorDisabled = clNone
      ThumbRight.Color = clNone
      ThumbRight.ColorTo = 16178633
      ThumbRight.ColorDown = 7778289
      ThumbRight.ColorDownTo = 4296947
      ThumbRight.ColorHot = 15465983
      ThumbRight.ColorHotTo = 11332863
      ThumbRight.ColorDisabled = clBlack
      ThumbRight.ColorDisabledTo = clBlack
      ThumbRight.ColorMirror = 15586496
      ThumbRight.ColorMirrorTo = 16245200
      ThumbRight.ColorMirrorHot = 5888767
      ThumbRight.ColorMirrorHotTo = 10807807
      ThumbRight.ColorMirrorDown = 946929
      ThumbRight.ColorMirrorDownTo = 5021693
      ThumbRight.ColorMirrorDisabled = clBlack
      ThumbRight.ColorMirrorDisabledTo = clBlack
      ThumbRight.Gradient = ggVertical
      ThumbRight.GradientMirror = ggRadial
      ThumbRight.Size = 0
      ThumbRight.Width = 0
      ThumbRight.Shape = tsPointer
      TickMark.Color = clBlack
      TickMark.ColorDisabled = clBlack
      TickMark.Font.Charset = DEFAULT_CHARSET
      TickMark.Font.Color = clWindowText
      TickMark.Font.Height = -11
      TickMark.Font.Name = 'Tahoma'
      TickMark.Font.Style = []
      TickMark.ShowText = True
      TickMark.Size = 6
      TrackHint = False
      TrackLabel.Position = lpBottomLeft
      TrackLabel.Font.Charset = DEFAULT_CHARSET
      TrackLabel.Font.Color = clWindowText
      TrackLabel.Font.Height = -11
      TrackLabel.Font.Name = 'Tahoma'
      TrackLabel.Font.Style = []
      TrackLabel.Format = 'PosLeft: %d  PosRight: %d'
      TrackLabel.Spacing = 0
      Version = '1.6.10.2'
    end
    object pnlRadarGraph: TPanel
      Left = 1
      Top = 2
      Width = 456
      Height = 105
      Color = clBlack
      ParentBackground = False
      TabOrder = 1
    end
    object edtRadarFC: TEdit
      Left = 531
      Top = 16
      Width = 58
      Height = 26
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 2
      Text = '0'
    end
    object edtRadarAGC: TEdit
      Left = 531
      Top = 49
      Width = 58
      Height = 26
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 3
      Text = '0'
    end
    object edtRadarGate: TEdit
      Left = 510
      Top = 85
      Width = 58
      Height = 26
      Alignment = taCenter
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 4
      Text = '0'
    end
  end
  object pnlTargetLocation: TPanel
    Left = 0
    Top = 808
    Width = 599
    Height = 137
    BevelInner = bvLowered
    ParentBackground = False
    TabOrder = 6
    object lblRAzimuth: TLabel
      Left = 30
      Top = 56
      Width = 71
      Height = 18
      Caption = 'R. Azimuth'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblRAzimuthsat: TLabel
      Left = 120
      Top = 83
      Width = 12
      Height = 18
      Caption = ' '#176
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblElevation: TLabel
      Left = 165
      Top = 56
      Width = 57
      Height = 18
      Caption = 'Elevation'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblElevationsat: TLabel
      Left = 250
      Top = 83
      Width = 12
      Height = 18
      Caption = ' '#176
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblRDRange: TLabel
      Left = 293
      Top = 56
      Width = 65
      Height = 18
      Caption = 'RD Range'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblLSRange: TLabel
      Left = 459
      Top = 56
      Width = 61
      Height = 18
      Caption = 'LS Range'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object pnlTargetLocationHeader: TPanel
      Left = 2
      Top = 2
      Width = 595
      Height = 28
      Align = alTop
      Caption = 'TARGET LOCATION'
      Color = clHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
    end
    object edtRAzimuthVal: TEdit
      Left = 6
      Top = 80
      Width = 115
      Height = 24
      Alignment = taCenter
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 1
      Text = '0.000'
    end
    object edtElevationVal: TEdit
      Left = 135
      Top = 80
      Width = 115
      Height = 24
      Alignment = taCenter
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 2
      Text = '0.000'
    end
    object edtRDRangeVal: TEdit
      Left = 267
      Top = 80
      Width = 116
      Height = 24
      Alignment = taCenter
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 3
      Text = '0'
    end
    object edtLSRangeVal: TEdit
      Left = 433
      Top = 80
      Width = 115
      Height = 24
      Alignment = taCenter
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ReadOnly = True
      TabOrder = 4
      Text = '0'
    end
    object fbRangeMeter: TFlatButton
      Left = 389
      Top = 80
      Width = 38
      Height = 25
      Color = clSilver
      ColorDown = clLime
      GroupIndex = 1
      Down = True
      Caption = 'm'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ParentColor = False
      TabOrder = 5
    end
    object fbRangeNM: TFlatButton
      Left = 389
      Top = 52
      Width = 38
      Height = 25
      Color = clSilver
      ColorDown = clLime
      GroupIndex = 1
      Caption = 'Nm'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ParentColor = False
      TabOrder = 6
    end
    object fbLaserRangeM: TFlatButton
      Left = 553
      Top = 80
      Width = 38
      Height = 25
      Color = clSilver
      ColorDown = clLime
      GroupIndex = 2
      Down = True
      Caption = 'm'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ParentColor = False
      TabOrder = 7
    end
    object fbLaserRangeNM: TFlatButton
      Left = 553
      Top = 52
      Width = 38
      Height = 25
      Color = clSilver
      ColorDown = clLime
      GroupIndex = 2
      Caption = 'Nm'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ParentColor = False
      TabOrder = 8
    end
  end
  object pnlInformation: TPanel
    Left = 0
    Top = 951
    Width = 599
    Height = 72
    BevelInner = bvLowered
    ParentBackground = False
    TabOrder = 7
    object lblSystemTime: TLabel
      Left = 19
      Top = 22
      Width = 75
      Height = 16
      Caption = 'System Time'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblRunTime: TLabel
      Left = 19
      Top = 38
      Width = 55
      Height = 16
      Caption = 'Run Time'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblRunTimeVal: TLabel
      Left = 119
      Top = 38
      Width = 52
      Height = 16
      Caption = '00:00:00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object lblSystemTimeVal: TLabel
      Left = 119
      Top = 22
      Width = 52
      Height = 16
      Caption = '00:00:00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
  end
  object tmrUpdateShipPos: TTimer
    Enabled = False
    Interval = 500
    OnTimer = UpdatePosition
    Left = 688
    Top = 424
  end
  object tmrUpdateForm: TTimer
    OnTimer = tmrUpdateFormTimer
    Left = 641
    Top = 425
  end
  object NLDJoystick: TNLDJoystick
    OnButtonDown = NLDJoystick1ButtonDown
    OnButtonUp = NLDJoystick1ButtonUp
    OnMove = NLDJoystick1Move
    PollingInterval = -1
    Left = 573
    Top = 421
  end
end
