object frmControlByNumber: TfrmControlByNumber
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsSingle
  ClientHeight = 191
  ClientWidth = 223
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWhite
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 274
    Height = 241
    BevelOuter = bvNone
    BorderStyle = bsSingle
    Color = clBlack
    ParentBackground = False
    TabOrder = 0
    object lblApply: TLabel
      Left = 20
      Top = 165
      Width = 31
      Height = 16
      Caption = 'Apply'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clGray
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = lblApplyClick
    end
    object lblClose: TLabel
      Left = 164
      Top = 165
      Width = 31
      Height = 16
      Caption = 'Close'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      OnClick = lblCloseClick
    end
    object RadioGroup1: TRadioGroup
      Left = 6
      Top = 13
      Width = 207
      Height = 141
      Color = clNone
      ParentBackground = False
      ParentColor = False
      TabOrder = 4
    end
    object Panel1: TPanel
      Left = -9
      Top = 160
      Width = 234
      Height = 1
      Color = clWhite
      ParentBackground = False
      TabOrder = 3
    end
    object Panel2: TPanel
      Left = 27
      Top = 8
      Width = 125
      Height = 17
      BevelOuter = bvNone
      Caption = 'Control By Number'
      Color = clBlack
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 5
    end
    object btnLinkY: TRadioButton
      Left = 32
      Top = 72
      Width = 19
      Height = 25
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 1
    end
    object btnMSITNo: TRadioButton
      Left = 32
      Top = 40
      Width = 29
      Height = 26
      Checked = True
      Color = clGreen
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 0
      TabStop = True
    end
    object edtTrackNo: TEdit
      Left = 124
      Top = 122
      Width = 81
      Height = 24
      BevelInner = bvNone
      BevelOuter = bvNone
      Color = clBlack
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      NumbersOnly = True
      ParentFont = False
      TabOrder = 2
      OnChange = edtTrackNoChange
    end
    object pnlLinkYTNo: TPanel
      Left = 67
      Top = 75
      Width = 62
      Height = 17
      BevelOuter = bvNone
      Caption = 'Link Y TNo'
      Color = clBlack
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 7
    end
    object pnlMSITNo: TPanel
      Left = 67
      Top = 44
      Width = 54
      Height = 17
      BevelOuter = bvNone
      Caption = 'MSI TNo'
      Color = clBlack
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 6
    end
    object pnlTrackNo: TPanel
      Left = 32
      Top = 125
      Width = 54
      Height = 17
      BevelOuter = bvNone
      Caption = 'Track No'
      Color = clBlack
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 8
    end
  end
end
