[Drive]
name=D

[Network]
SessionID=2222
GamePort=7899
BroadCastAddress=192.168.1.255
DB_Address=192.168.1.195
SoundPlayerAddr=127.0.0.1
CubicleID=2

[Display]
Monitor=1

[SimSetting]
HideCursorOnMarkerActive=0
AssumedPortDistanceNM=1
AudioUsesVoip=0
SentryFilterDefaultOn=0
CwProcessingDefaultOn=0

[Ports]
PortNames=Surabaya,Jakarta
; Lon, Lat
Surabaya=112.733700,-7.196308
Jakarta=106.883110,-6.100849