[Ident]
ConsoleName = MOC 1
CubicleName = 1
ListenPort = 5555
SessionID = 1111
AppName = tcmss.exe
BroadcastAddr = 192.168.5.255
BRIDGE3DFullPath= D:TCMS\tcmss.3d\Bridge TCMS Sigma\Bridge TCMS\Bridge\Win32\Debug\BridgeDelphiCSharp.exe 
;D:\Kerjoan\Technoit\[ONSITE]\TCMS_MOC3\tcmss.3d\Bridge TCMS Sigma\Bridge TCMS\Bridge\Win32\Debug\BridgeDelphiCSharp.exe
BRIDGE3DName='BridgeDelphiCSharp.exe'
App3DName='TCMS_x64.exe'