//MOC4
[Map]
geoset=.\tcms_map\tcms_world_lama.gst
long=112.722778
latt=-7.198333
zoom=128
geosetnorole=.\tcms_map\tcms_world.gst
geosetEnc=.\tcms_map\tcms_world.gst

[Drive]
name=D

[Network]
GamePort = 6970
LauncherPort =8888
;BroadCastAddress = 192.168.0.255
BroadCastAddress = 192.168.3.255
SessionID= 1111
MOCName=MOC 6
Leader=0
Port3D=6970
TCMSPort3D=6971

[ident]
ConsoleName = MOC 6
LauncherPort=8888
MOCName=MOC 6
CubicleID=1
Trainer=0
CubicleCount=4

[Code]
fa_code=1234

[OwnShip]
spd=5
crs=0
spd_le=12:47
crs_le=12:47
lat=-4.09797034502331
long=110.9096
PosX=368.622155959906
PosY=398.452988037667
latlong_le=12:47

[Drift]
crs=0
spd=0
le=11:53

[Depth]
depth=50
le=00:00

[Humidity]
humid=2
le=10:29

[Wind]
reldir=172
spd=10
le=13:00

[MagVar]
magvar=1 W
le=09:41

[Barom]
bar=1
le=10:56

[AirTemp]
temp=-2
le=12:21



[Database]
dbserver=127.0.0.1
dbproto=mysql
dbname=tcms
dbuser=cm9vdA==
dbpass=YWRtaW4=
dbport=3306
dbhost=localhost
[Lirod]
FileName=didLauncher.exe
Params=didGameServer --port 7000 --fullscreen "false" --standalone "true" --vehicle 29 --weapon 14 --launcher 1 --useSerialCom "false" --scPort 3 --scBoud 9600 --scData 8 --scFirstPitch -80 --scFire 254 --scLock 251
Dir=3D\bin
CurrDir=D:\DID Project\svn\tcms_prj\tcmss.bin\
BatchName=Exec.bat
StopBatchName=StopExec.bat
TrainingSpeed=0.5
ElevationSpeed=0.5
VideoNum=1
VideoType=1
AttachTo=1
OffsetX=112.7
OffsetY=-7.0
Narrow=120
Wide=600
DepthOfView=120000
AirStep=1
PlayerHeight=15
 
[ARPA]
status=0

[AIS]
status=0

[SPS]
status =1
monitorID=0
monTop=10
monLeft=10

[Snapshot]
MOCName=6
ImageName=MOC1_Image1
ImagePath=Z:\Image\

[Password]
PasswordOn = 0

[PDKSetting]
ipConnect = 127.0.0.1
portConnect = 2345
isFullScreen = 0
FormHeight = 700
FormWidth = 500
FontSize = 12
ServiceMonitor = 1

[Port]
Name=COM1
Enable=0
Reverse=0
PdkEnable=1

[ArduinoPort]
Name=COM3
Enable=0
BaudRate=0
DataBits=0
StopBits=0
ParityBits=0
FlowControl=0

[Project]
ProjectType=1
[Monitor]
Primary=1
ReadOutTop=1540
WorksetTop=1540
AvoidMoniIdx=2

[Sonar]
status=1
[Gun76mm]
CorrectionMode=0
TrainEnable=0
[Tetral]
TimeToLaunch=2
[TVVideo1]
FileName=did3DViewer.exe
VideoNum=1
VideoType=grayscale
StartBatchName=Start3DLirod.bat
StopBatchName=Stop3DLirod.bat
[TVVideo2]
FileName=did3DViewer.exe
VideoNum=2
VideoType=grayscale
StartBatchName=Start3DLirod.bat
StopBatchName=Stop3DLirod.bat

[Gun35mm]
CorrectionMode=0
TrainEnable=0
[Chat]
Path=C:\Program Files (x86)\Spark\Spark.exe
PathDir=C:\Program Files (x86)\Spark
[ArduinoPort2]
Name=COM10
Enable=0
BaudRate=0
DataBits=0
StopBits=0
ParityBits=0
FlowControl=0
[ArduinoPortExo]
Name=COM4
Enable=0
BaudRate=0
DataBits=0
StopBits=0
ParityBits=0
FlowControl=0
[ArduinoPortEcm]
Name=COM4
Enable=0
BaudRate=0
DataBits=0
StopBits=0
ParityBits=0
FlowControl=0
[ArduinoPortMica]
Name=COM4
Enable=0
BaudRate=0
DataBits=0
StopBits=0
ParityBits=0
FlowControl=0
