object frmFoeFriendSituationPage: TfrmFoeFriendSituationPage
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'frmFoeFriendSituationPage'
  ClientHeight = 1080
  ClientWidth = 1920
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnHide = FormHide
  OnKeyDown = FormKeyDown
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Label56: TLabel
    Left = 18
    Top = 17
    Width = 107
    Height = 18
    Caption = 'DIRT ATTACK'
    Font.Charset = ANSI_CHARSET
    Font.Color = clLime
    Font.Height = -16
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object advpgcFunctionMenuFoe: TAdvPageControl
    Left = 0
    Top = 0
    Width = 1920
    Height = 1080
    ActivePage = advtsMControl
    ActiveFont.Charset = DEFAULT_CHARSET
    ActiveFont.Color = 10908270
    ActiveFont.Height = -13
    ActiveFont.Name = 'Tahoma'
    ActiveFont.Style = []
    Align = alClient
    DoubleBuffered = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    DefaultTabColor = 10790913
    ActiveColor = 12762561
    TabBackGroundColor = clBtnFace
    TabMargin.RightMargin = 0
    TabOverlap = 0
    Version = '2.0.2.0'
    PersistPagesState.Location = plRegistry
    PersistPagesState.Enabled = False
    TabOrder = 0
    OnChange = advpgcFunctionMenuFoeChange
    object advtsSituation: TAdvTabSheet
      Caption = 'Situation'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlLeft_Situation: TPanel
        Left = 0
        Top = 0
        Width = 952
        Height = 999
        Align = alLeft
        TabOrder = 0
        object pnlMap_Situation: TPanel
          Left = 1
          Top = 1
          Width = 950
          Height = 850
          Align = alTop
          Caption = 'pnlMap_Situation'
          TabOrder = 0
        end
        object pnlArea2_Situation: TPanel
          Left = 1
          Top = 851
          Width = 950
          Height = 147
          Align = alClient
          Caption = 'pnlArea2_Situation'
          TabOrder = 1
        end
      end
      object pnlRight_Situation: TPanel
        Left = 952
        Top = 0
        Width = 960
        Height = 999
        Align = alClient
        TabOrder = 1
        object pnlArea3B_Situation: TPanel
          Left = 1
          Top = 301
          Width = 958
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_Situation: TPanel
          Left = 1
          Top = 1
          Width = 958
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_Situation: TPanel
          Left = 1
          Top = 601
          Width = 958
          Height = 397
          Align = alClient
          Caption = 'pnlArea4_Situation'
          TabOrder = 2
        end
      end
      object pnlArea5_Situation: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 2
      end
    end
    object advtsFireDistr: TAdvTabSheet
      Caption = 'Fire Distr.'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_FireDist: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_FireDist: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_FireDist: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
        end
        object pnlArea2_FireDist: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_FireDist: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_FireDist: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_FireDist: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_FireDist: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
    end
    object advtsMInfo: TAdvTabSheet
      Caption = 'M. info.'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_MInfo: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_MInfo: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_MInfo: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
        end
        object pnlArea2_MInfo: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_MInfo: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_MInfo: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_MInfo: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_MInfo: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
    end
    object advtsParSetting: TAdvTabSheet
      Caption = 'Par. Setting'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_ParSetting: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_ParSetting: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_ParSetting: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
        end
        object pnlArea2_ParSetting: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_ParSetting: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_ParSetting: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_ParSetting: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_ParSetting: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
    end
    object advtsChSelect: TAdvTabSheet
      Caption = 'Ch. Select'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_ChSelect: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_ChSelect: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_ChSelect: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
        end
        object pnlArea2_ChSelect: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_ChSelect: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_ChSelect: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_ChSelect: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_ChSelect: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
    end
    object advtsMControl: TAdvTabSheet
      Caption = 'M. Control'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_MControl: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_MControl: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_MControl: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
        end
        object pnlArea2_MControl: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_MControl: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_MControl: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_MControl: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_MControl: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
      object pnlMissileControl: TPanel
        Tag = 5
        Left = 232
        Top = 264
        Width = 489
        Height = 322
        Color = clActiveBorder
        ParentBackground = False
        TabOrder = 3
        Visible = False
        object Bevel2: TBevel
          Left = 20
          Top = 236
          Width = 445
          Height = 9
          Shape = bsBottomLine
        end
        object Label51: TLabel
          Left = 25
          Top = 261
          Width = 257
          Height = 18
          Caption = 'For select,Press [Up] or [down]'
          Font.Charset = ANSI_CHARSET
          Font.Color = clNavy
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object Label53: TLabel
          Left = 25
          Top = 293
          Width = 281
          Height = 18
          Caption = '[Enter] for confirm,[Esc] for return'
          Font.Charset = ANSI_CHARSET
          Font.Color = clNavy
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object pnlMCtrlHeader: TPanel
          Tag = 60
          Left = 1
          Top = 1
          Width = 487
          Height = 41
          Align = alTop
          Alignment = taLeftJustify
          BevelOuter = bvLowered
          Caption = 'Missile Control'
          Color = clNavy
          Font.Charset = ANSI_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
        end
        object pnlPowerOnContentMCtrl: TPanel
          Left = 152
          Top = 68
          Width = 313
          Height = 162
          BevelOuter = bvNone
          TabOrder = 1
          object Label58: TLabel
            Left = 191
            Top = 12
            Width = 33
            Height = 18
            Caption = '1~2'
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlue
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
          object Panel19: TPanel
            Left = 10
            Top = 5
            Width = 175
            Height = 32
            Color = clBlue
            ParentBackground = False
            TabOrder = 0
          end
        end
        object pnlPowerOnMCtrl: TPanel
          Tag = 61
          Left = 20
          Top = 69
          Width = 122
          Height = 35
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Caption = 'Power On'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = 11754291
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
        end
        object pnlReCheckMCtrl: TPanel
          Tag = 62
          Left = 20
          Top = 110
          Width = 122
          Height = 35
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Caption = 'ReCheck'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 3
        end
        object pnlINSAlignMCtrl: TPanel
          Tag = 63
          Left = 20
          Top = 152
          Width = 122
          Height = 35
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Caption = 'INS Align.'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 4
        end
        object pnlPowerOffMCtrl: TPanel
          Tag = 64
          Left = 20
          Top = 194
          Width = 122
          Height = 35
          BevelInner = bvLowered
          BevelOuter = bvLowered
          Caption = 'PowerOff'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 5
        end
        object pnlReCheckContentMCtrl: TPanel
          Left = 152
          Top = 68
          Width = 313
          Height = 162
          BevelOuter = bvNone
          TabOrder = 6
          object Label61: TLabel
            Left = 191
            Top = 12
            Width = 66
            Height = 18
            Caption = 'Recheck'
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlue
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlINSAlignContentMCtrl: TPanel
          Left = 152
          Top = 68
          Width = 313
          Height = 162
          BevelOuter = bvNone
          TabOrder = 7
          object Label63: TLabel
            Left = 191
            Top = 12
            Width = 82
            Height = 18
            Caption = 'INS Align.'
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlue
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlPowerOffContentMCtrl: TPanel
          Left = 152
          Top = 68
          Width = 313
          Height = 162
          BevelOuter = bvNone
          TabOrder = 8
          object Label67: TLabel
            Left = 191
            Top = 12
            Width = 74
            Height = 18
            Caption = 'PowerOff'
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlue
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
    end
    object advtsMMonitor: TAdvTabSheet
      Caption = 'M. Monitor'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_MMonitor: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_MMonitor: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_MMonitor: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
        end
        object pnlArea2_MMonitor: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_MMonitor: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_MMonitor: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_MMonitor: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_MMonitor: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
    end
    object advtsINSTest: TAdvTabSheet
      Caption = 'INS Test'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_InsTest: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_InsTest: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_InsTest: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
          object pnlInsTestTab: TPanel
            Tag = 5
            Left = 232
            Top = 279
            Width = 489
            Height = 292
            Color = clActiveBorder
            ParentBackground = False
            TabOrder = 0
            object Bevel1: TBevel
              Left = 20
              Top = 186
              Width = 445
              Height = 9
              Shape = bsBottomLine
            end
            object Label36: TLabel
              Left = 25
              Top = 211
              Width = 185
              Height = 18
              Caption = 'For cancel, Press [Esc]'
              Font.Charset = ANSI_CHARSET
              Font.Color = clNavy
              Font.Height = -16
              Font.Name = 'Verdana'
              Font.Style = []
              ParentFont = False
            end
            object Label39: TLabel
              Left = 25
              Top = 243
              Width = 210
              Height = 18
              Caption = 'For confirm, Press [Enter]'
              Font.Charset = ANSI_CHARSET
              Font.Color = clNavy
              Font.Height = -16
              Font.Name = 'Verdana'
              Font.Style = []
              ParentFont = False
            end
            object Label43: TLabel
              Left = 25
              Top = 75
              Width = 125
              Height = 18
              Caption = 'Are you sure of'
              Font.Charset = ANSI_CHARSET
              Font.Color = clBlue
              Font.Height = -16
              Font.Name = 'Verdana'
              Font.Style = []
              ParentFont = False
            end
            object Label45: TLabel
              Left = 25
              Top = 143
              Width = 297
              Height = 18
              Caption = 'Note: Booster should be safe state!'
              Font.Charset = ANSI_CHARSET
              Font.Color = clRed
              Font.Height = -16
              Font.Name = 'Verdana'
              Font.Style = []
              ParentFont = False
            end
            object Label47: TLabel
              Left = 25
              Top = 109
              Width = 310
              Height = 18
              Caption = 'entering into inertial navigation test?'
              Font.Charset = ANSI_CHARSET
              Font.Color = clBlue
              Font.Height = -16
              Font.Name = 'Verdana'
              Font.Style = []
              ParentFont = False
            end
            object Panel2: TPanel
              Left = 1
              Top = 1
              Width = 487
              Height = 41
              Align = alTop
              Alignment = taLeftJustify
              BevelOuter = bvLowered
              Caption = 'INS Test'
              Color = clNavy
              Font.Charset = ANSI_CHARSET
              Font.Color = clLime
              Font.Height = -16
              Font.Name = 'Verdana'
              Font.Style = []
              ParentBackground = False
              ParentFont = False
              TabOrder = 0
            end
          end
        end
        object pnlArea2_InsTest: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_InsTest: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_InsTest: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_InsTest: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_InsTest: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
    end
    object advtsLaunchData: TAdvTabSheet
      Caption = 'Launch Data'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_LaunchData: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_LaunhData: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_LaunchData: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
        end
        object pnlArea2_LaunchData: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_LaunchData: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_LaunchData: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_LaunchData: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_LaunchData: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
    end
    object advtsExit: TAdvTabSheet
      Caption = 'Exit'
      Color = clBtnFace
      ColorTo = clNone
      TabColor = 10790913
      TabColorTo = clNone
      object pnlArea5_Exit: TPanel
        Left = 0
        Top = 999
        Width = 1912
        Height = 50
        Align = alBottom
        TabOrder = 0
      end
      object pnlLeft_Exit: TPanel
        Left = 0
        Top = 0
        Width = 956
        Height = 999
        Align = alLeft
        TabOrder = 1
        object pnlArea1_Exit: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 850
          Align = alTop
          Caption = 'Area1'
          TabOrder = 0
        end
        object pnlArea2_Exit: TPanel
          Left = 1
          Top = 851
          Width = 954
          Height = 147
          Align = alClient
          Caption = 'Area2'
          TabOrder = 1
        end
      end
      object pnlRight_Exit: TPanel
        Left = 956
        Top = 0
        Width = 956
        Height = 999
        Align = alClient
        TabOrder = 2
        object pnlArea3B_Exit: TPanel
          Left = 1
          Top = 301
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3B'
          TabOrder = 0
        end
        object pnlArea3A_Exit: TPanel
          Left = 1
          Top = 1
          Width = 954
          Height = 300
          Align = alTop
          Caption = 'Area3A'
          TabOrder = 1
        end
        object pnlArea4_Exit: TPanel
          Left = 1
          Top = 601
          Width = 954
          Height = 397
          Align = alClient
          Caption = 'Area4 FireDist'
          TabOrder = 2
        end
      end
      object pnlExitTab: TPanel
        Tag = 5
        Left = 232
        Top = 279
        Width = 489
        Height = 292
        Color = clActiveBorder
        ParentBackground = False
        TabOrder = 3
        object Bevel3: TBevel
          Left = 20
          Top = 186
          Width = 445
          Height = 9
          Shape = bsBottomLine
        end
        object Label15: TLabel
          Left = 25
          Top = 211
          Width = 185
          Height = 18
          Caption = 'For cancel, Press [Esc]'
          Font.Charset = ANSI_CHARSET
          Font.Color = clNavy
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object Label16: TLabel
          Left = 25
          Top = 243
          Width = 210
          Height = 18
          Caption = 'For confirm, Press [Enter]'
          Font.Charset = ANSI_CHARSET
          Font.Color = clNavy
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object Label17: TLabel
          Left = 25
          Top = 75
          Width = 207
          Height = 18
          Caption = 'Return to the start page.'
          Font.Charset = ANSI_CHARSET
          Font.Color = clRed
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object Label1: TLabel
          Left = 25
          Top = 143
          Width = 112
          Height = 18
          Caption = 'Are you sure?'
          Font.Charset = ANSI_CHARSET
          Font.Color = clRed
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object Label2: TLabel
          Left = 25
          Top = 109
          Width = 272
          Height = 18
          Caption = 'The missiles will be powered off!'
          Font.Charset = ANSI_CHARSET
          Font.Color = clRed
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object pnlHeaderSE: TPanel
          Left = 1
          Top = 1
          Width = 487
          Height = 41
          Align = alTop
          Alignment = taLeftJustify
          BevelOuter = bvLowered
          Caption = 'Exit'
          Color = clNavy
          Font.Charset = ANSI_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Verdana'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
        end
      end
    end
  end
  object pnlArea3A: TPanel
    Left = 928
    Top = 57
    Width = 952
    Height = 300
    Color = clWhite
    ParentBackground = False
    TabOrder = 1
  end
  object pnlArea3B: TPanel
    Left = 1005
    Top = 424
    Width = 952
    Height = 300
    Color = clWhite
    ParentBackground = False
    TabOrder = 2
  end
  object pnlArea2: TPanel
    Left = 13
    Top = 844
    Width = 954
    Height = 147
    TabOrder = 3
    object pnlArea2Btm: TPanel
      Left = 1
      Top = 76
      Width = 952
      Height = 70
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
      object pnlParam2Top: TPanel
        Left = 0
        Top = 0
        Width = 952
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        TabOrder = 0
        object pnlLongParamHeader: TPanel
          Tag = 15
          Left = 0
          Top = 0
          Width = 130
          Height = 35
          Align = alLeft
          Caption = 'LONG (deg)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object pnlLongParam: TPanel
          Left = 130
          Top = 0
          Width = 188
          Height = 35
          Align = alLeft
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblLongParam: TLabel
            Left = 65
            Top = 8
            Width = 86
            Height = 18
            Alignment = taRightJustify
            Caption = '000.00000'
            Color = clLime
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
        end
        object pnlESpdParamHeader: TPanel
          Tag = 17
          Left = 318
          Top = 0
          Width = 130
          Height = 35
          Align = alLeft
          Caption = 'E.Spd(m/s)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object pnlESpdParam: TPanel
          Left = 448
          Top = 0
          Width = 188
          Height = 35
          Align = alLeft
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 3
          object lblESpdParam: TLabel
            Left = 99
            Top = 9
            Width = 36
            Height = 18
            Alignment = taRightJustify
            Caption = '0.00'
            Color = clLime
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
        end
        object pnlSeaStateParamHeader: TPanel
          Tag = 19
          Left = 636
          Top = 0
          Width = 130
          Height = 35
          Align = alLeft
          Caption = 'Sea State'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
        end
        object pnlSeaStateParam: TPanel
          Left = 766
          Top = 0
          Width = 188
          Height = 35
          Align = alLeft
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 5
          object lblSeaStateParam: TLabel
            Left = 22
            Top = 6
            Width = 32
            Height = 18
            Caption = 'Low'
            Color = clLime
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
        end
      end
      object pnlParam2Btm: TPanel
        Left = 0
        Top = 35
        Width = 952
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 1
        object pnlLatParamHeader: TPanel
          Tag = 16
          Left = 0
          Top = 0
          Width = 130
          Height = 35
          Align = alLeft
          Caption = 'LAT (deg)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
        end
        object pnlLatParam: TPanel
          Left = 130
          Top = 0
          Width = 188
          Height = 35
          Align = alLeft
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblLatParam: TLabel
            Left = 65
            Top = 8
            Width = 86
            Height = 18
            Alignment = taRightJustify
            Caption = '000.00000'
            Color = clLime
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
        end
        object pnlNSpdParamHeader: TPanel
          Tag = 18
          Left = 318
          Top = 0
          Width = 130
          Height = 35
          Align = alLeft
          Caption = 'N.Spd(m/s)'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
        object pnlNSpdParam: TPanel
          Left = 448
          Top = 0
          Width = 188
          Height = 35
          Align = alLeft
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 3
          object lblNSpdParam: TLabel
            Left = 99
            Top = 9
            Width = 36
            Height = 18
            Alignment = taRightJustify
            Caption = '0.00'
            Color = clLime
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
        end
        object pnlPDOMParamHeader: TPanel
          Tag = 20
          Left = 636
          Top = 0
          Width = 130
          Height = 35
          Align = alLeft
          Caption = 'PDOP'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
        end
        object pnlPDOPParam: TPanel
          Left = 766
          Top = 0
          Width = 188
          Height = 35
          Align = alLeft
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 5
          object lblPDOPParam: TLabel
            Left = 99
            Top = 6
            Width = 36
            Height = 18
            Caption = '0.00'
            Color = clLime
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
        end
      end
    end
    object pnlArea2Top: TPanel
      Left = 1
      Top = 1
      Width = 952
      Height = 75
      Align = alTop
      BevelOuter = bvNone
      TabOrder = 1
      object Panel3: TPanel
        Left = 0
        Top = 0
        Width = 188
        Height = 75
        Align = alLeft
        Caption = 'placement'
        Color = clBlack
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
      end
      object Panel12: TPanel
        Left = 188
        Top = 0
        Width = 130
        Height = 75
        Align = alLeft
        TabOrder = 1
        object Label7: TLabel
          Left = 41
          Top = 11
          Width = 41
          Height = 16
          Caption = 'S. Roll'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object edtSRoll: TEdit
          Left = 17
          Top = 33
          Width = 97
          Height = 27
          Alignment = taCenter
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          Text = '0.00'
        end
      end
      object Panel15: TPanel
        Left = 318
        Top = 0
        Width = 188
        Height = 75
        Align = alLeft
        Caption = 'placement'
        Color = clBlack
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 2
      end
      object Panel16: TPanel
        Left = 506
        Top = 0
        Width = 130
        Height = 75
        Align = alLeft
        TabOrder = 3
        object Label33: TLabel
          Left = 41
          Top = 11
          Width = 52
          Height = 16
          Caption = 'S. Pitch'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object edtSPitch: TEdit
          Left = 17
          Top = 33
          Width = 97
          Height = 27
          Alignment = taCenter
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          Text = '0.00'
        end
      end
      object Panel17: TPanel
        Left = 636
        Top = 0
        Width = 188
        Height = 75
        Align = alLeft
        Caption = 'placement'
        Color = clBlack
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 4
      end
      object Panel18: TPanel
        Left = 824
        Top = 0
        Width = 130
        Height = 75
        Align = alLeft
        TabOrder = 5
        object Label34: TLabel
          Left = 6
          Top = 11
          Width = 44
          Height = 16
          Caption = 'S. Spd'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object Label35: TLabel
          Left = 6
          Top = 41
          Width = 44
          Height = 16
          Caption = 'S. Hdg'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = []
          ParentFont = False
        end
        object edtSSpd: TEdit
          Left = 58
          Top = 7
          Width = 58
          Height = 24
          Alignment = taCenter
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          Text = '0.00'
        end
        object edtSHdg: TEdit
          Left = 58
          Top = 37
          Width = 58
          Height = 24
          Alignment = taCenter
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          Text = '0.00'
        end
      end
    end
  end
  object pnlArea4: TPanel
    Left = 0
    Top = 450
    Width = 954
    Height = 372
    TabOrder = 4
    object pnlLeft_Area4: TPanel
      Left = 1
      Top = 1
      Width = 477
      Height = 370
      Align = alLeft
      BevelOuter = bvNone
      Caption = 'Panel1'
      TabOrder = 0
      object pnlArea4_Row10_L: TPanel
        Left = 0
        Top = 315
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object Panel57: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label54: TLabel
            Left = 10
            Top = 9
            Width = 76
            Height = 18
            Caption = 'Hdg(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlHdgVal2_L: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblHdgVal2_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlHdgVal1_L: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblHdgVal1_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row8_L: TPanel
        Left = 0
        Top = 245
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object Panel51: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label50: TLabel
            Left = 10
            Top = 9
            Width = 71
            Height = 18
            Caption = 'Brg(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlBrgVal2_L: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlBrgVal1_L: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblBrgVal_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row6_L: TPanel
        Left = 0
        Top = 175
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object Panel45: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label46: TLabel
            Left = 10
            Top = 9
            Width = 65
            Height = 18
            Caption = 'A1(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlA1Val2: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlA1Val1: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblA1Val: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row4_L: TPanel
        Left = 0
        Top = 105
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object Panel39: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label42: TLabel
            Left = 10
            Top = 9
            Width = 81
            Height = 18
            Caption = 'Rmin(Km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRMinVal2_L: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlRMinVal1_L: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblRMinVal_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row2_L: TPanel
        Left = 0
        Top = 35
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        object Panel33: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label38: TLabel
            Left = 10
            Top = 9
            Width = 81
            Height = 18
            Caption = 'Ron1(Km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRon2Val_L: TPanel
          Left = 387
          Top = 0
          Width = 90
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblRon2Val_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRon1Val_L: TPanel
          Left = 159
          Top = 0
          Width = 90
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblRon1Val_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object Panel60: TPanel
          Left = 249
          Top = 0
          Width = 138
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          object Label59: TLabel
            Left = 10
            Top = 9
            Width = 81
            Height = 18
            Caption = 'Ron2(Km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row9_L: TPanel
        Left = 0
        Top = 280
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        object Panel54: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label52: TLabel
            Left = 10
            Top = 9
            Width = 71
            Height = 18
            Caption = 'Pth(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlPthVal2_L: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblPthVal2_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlPthVal1_L: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblPthVal1_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row7_L: TPanel
        Left = 0
        Top = 210
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        object Panel48: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label48: TLabel
            Left = 10
            Top = 9
            Width = 65
            Height = 18
            Caption = 'A2(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlA2Val2_L: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlA2Val1_L: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblA2Val_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row5_L: TPanel
        Left = 0
        Top = 140
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 7
        object Panel42: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label44: TLabel
            Left = 10
            Top = 9
            Width = 55
            Height = 18
            Caption = 'B(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlBVal2_L: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlBVal1_L: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblBVal_L: TLabel
            Left = 6
            Top = 11
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row3_L: TPanel
        Left = 0
        Top = 70
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 8
        object Panel36: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label40: TLabel
            Left = 10
            Top = 9
            Width = 85
            Height = 18
            Caption = 'Rmax(Km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRMaxVal2_L: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlRMaxVal1_L: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblRMaxVal_L: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row1_L: TPanel
        Left = 0
        Top = 0
        Width = 477
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 9
        object pnlTgtNbHeader_L: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object lblTgtNbHeader_L: TLabel
            Left = 10
            Top = 9
            Width = 78
            Height = 18
            Caption = 'Tgt: 0001'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlDirtAttackHeader_L: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          object Label37: TLabel
            Left = 10
            Top = 9
            Width = 107
            Height = 18
            Caption = 'DIRT ATTACK'
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlue
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlHeader_L: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
      end
    end
    object pnlRight_Area4: TPanel
      Left = 478
      Top = 1
      Width = 475
      Height = 370
      Align = alClient
      BevelOuter = bvNone
      Caption = 'Panel1'
      TabOrder = 1
      object pnlArea4_Row1_R: TPanel
        Left = 0
        Top = 0
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object pnlTgtNbHeader_R: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object lblTgtNbHeader_R: TLabel
            Left = 10
            Top = 9
            Width = 78
            Height = 18
            Caption = 'Tgt: 0001'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlDirtAttackHeader_R: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 1
          object Label41: TLabel
            Left = 10
            Top = 9
            Width = 107
            Height = 18
            Caption = 'DIRT ATTACK'
            Font.Charset = ANSI_CHARSET
            Font.Color = clBlue
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlHeader_R: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 2
        end
      end
      object pnlArea4_Row10_R: TPanel
        Left = 0
        Top = 315
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object Panel23: TPanel
          Left = 0
          Top = 0
          Width = 193
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object lblCCSVal: TLabel
            Left = 10
            Top = 9
            Width = 111
            Height = 18
            Caption = 'CCS:unknown'
            Font.Charset = ANSI_CHARSET
            Font.Color = clYellow
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlHdgVal2_R: TPanel
          Left = 340
          Top = 0
          Width = 147
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblRPSVal: TLabel
            Left = 10
            Top = 9
            Width = 94
            Height = 18
            Caption = 'RPS:normal'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlHdgVal1_R: TPanel
          Left = 193
          Top = 0
          Width = 147
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblIpdVal: TLabel
            Left = 10
            Top = 9
            Width = 92
            Height = 18
            Caption = 'IPD:normal'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row2_R: TPanel
        Left = 0
        Top = 35
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object Panel27: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label49: TLabel
            Left = 10
            Top = 9
            Width = 81
            Height = 18
            Caption = 'Ron1(Km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRon2Val_R: TPanel
          Left = 387
          Top = 0
          Width = 90
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblRon2Val_R: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object Panel29: TPanel
          Left = 159
          Top = 0
          Width = 90
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblRon1Val_R: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object Panel30: TPanel
          Left = 249
          Top = 0
          Width = 138
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 3
          object Label55: TLabel
            Left = 10
            Top = 9
            Width = 81
            Height = 18
            Caption = 'Ron2(Km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row3_R: TPanel
        Left = 0
        Top = 70
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object Panel32: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label57: TLabel
            Left = 10
            Top = 9
            Width = 85
            Height = 18
            Caption = 'Rmax(Km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRMaxVal2_R: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlRMaxVal1_R: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblRMaxVal_R: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row4_R: TPanel
        Left = 0
        Top = 105
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        object Panel38: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label60: TLabel
            Left = 10
            Top = 9
            Width = 81
            Height = 18
            Caption = 'Rmin(Km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRMinVal2_R: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlRMinVal1_R: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblRMinVal_R: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row5_R: TPanel
        Left = 0
        Top = 140
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        object Panel44: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label62: TLabel
            Left = 10
            Top = 9
            Width = 55
            Height = 18
            Caption = 'B(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlBVal2_R: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlBVal1_R: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblBVal_R: TLabel
            Left = 6
            Top = 11
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row6_R: TPanel
        Left = 0
        Top = 175
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        object Panel50: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label64: TLabel
            Left = 10
            Top = 9
            Width = 65
            Height = 18
            Caption = 'A1(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object Panel52: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object Panel53: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object Label65: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row7_R: TPanel
        Left = 0
        Top = 210
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 7
        object Panel56: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label66: TLabel
            Left = 10
            Top = 9
            Width = 65
            Height = 18
            Caption = 'A2(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlA2Val2_R: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlA2Val1_R: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblA2Val_R: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row8_R: TPanel
        Left = 0
        Top = 245
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 8
        object Panel62: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label68: TLabel
            Left = 10
            Top = 9
            Width = 71
            Height = 18
            Caption = 'Brg(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlBrgVal2_R: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
        object pnlBrgVal1_R: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblBrgVal_R: TLabel
            Left = 10
            Top = 9
            Width = 46
            Height = 18
            Caption = '00.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnlArea4_Row9_R: TPanel
        Left = 0
        Top = 280
        Width = 475
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 9
        object Panel66: TPanel
          Left = 0
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label70: TLabel
            Left = 10
            Top = 9
            Width = 69
            Height = 18
            Caption = 'RII(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlPthVal2_R: TPanel
          Left = 318
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblPthVal2_R: TLabel
            Left = 6
            Top = 11
            Width = 36
            Height = 18
            Caption = '0.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlPthVal1_R: TPanel
          Left = 159
          Top = 0
          Width = 159
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 2
          object lblPthVal1_R: TLabel
            Left = 10
            Top = 9
            Width = 36
            Height = 18
            Caption = '0.00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
    end
  end
  object pnlArea5: TPanel
    Left = 61
    Top = 1022
    Width = 869
    Height = 50
    BevelOuter = bvNone
    Color = 11754291
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 5
    object pnlTimeClock: TPanel
      Tag = 14
      Left = 769
      Top = 0
      Width = 100
      Height = 50
      Align = alRight
      Caption = '00:00:00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
    end
    object pnlFCSTrng: TPanel
      Tag = 13
      Left = 669
      Top = 0
      Width = 100
      Height = 50
      Align = alRight
      Caption = 'FCS TRNG'
      TabOrder = 1
    end
    object pnlIPDNav: TPanel
      Tag = 12
      Left = 569
      Top = 0
      Width = 100
      Height = 50
      Align = alRight
      Caption = 'IPD NAV.'
      TabOrder = 2
    end
    object pnlRPSPlan: TPanel
      Tag = 11
      Left = 469
      Top = 0
      Width = 100
      Height = 50
      Align = alRight
      Caption = 'RPS Plan'
      TabOrder = 3
    end
  end
  object tmrClock: TTimer
    Enabled = False
    OnTimer = tmrClockTimer
    Left = 4
    Top = 371
  end
end
