object frmTorpedoTubeStatusWindow: TfrmTorpedoTubeStatusWindow
  Left = 0
  Top = 0
  BorderStyle = bsNone
  ClientHeight = 337
  ClientWidth = 296
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 297
    Height = 337
    BevelOuter = bvNone
    Caption = 'pnlMain'
    TabOrder = 0
    object pnlTorpedo1: TPanel
      Left = 149
      Top = 6
      Width = 140
      Height = 80
      TabOrder = 0
      OnClick = pnlTorpedoClick
      object shpFrameTorpedo1: TShape
        Left = 5
        Top = 17
        Width = 130
        Height = 60
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object shpTorpedo1: TShape
        Left = 138
        Top = 0
        Width = 1
        Height = 80
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo1: TLabel
        Left = 35
        Top = 1
        Width = 73
        Height = 14
        Alignment = taCenter
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber1: TLabel
        Left = 10
        Top = 19
        Width = 7
        Height = 14
        Caption = '1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC1: TLabel
        Left = 119
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol1: TPaintBox
        Left = 64
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblActiveToSo1: TLabel
        Left = 19
        Top = 44
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo1: TLabel
        Left = 7
        Top = 59
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse1: TLabel
        Left = 121
        Top = 56
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblSalvoNumber1: TLabel
        Left = 118
        Top = 19
        Width = 14
        Height = 14
        Caption = '01'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pnlNumTorpedo1: TPanel
        Left = 8
        Top = 20
        Width = 33
        Height = 20
        Caption = '1'
        Color = clLime
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        Visible = False
      end
    end
    object pnlTorpedo2: TPanel
      Tag = 1
      Left = 8
      Top = 6
      Width = 140
      Height = 80
      TabOrder = 1
      OnClick = pnlTorpedoClick
      object shpFrameTorpedo2: TShape
        Left = 5
        Top = 16
        Width = 130
        Height = 60
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object shpTorpedo2: TShape
        Left = 0
        Top = 0
        Width = 1
        Height = 95
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo2: TLabel
        Left = 37
        Top = 1
        Width = 73
        Height = 14
        Alignment = taCenter
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber2: TLabel
        Left = 11
        Top = 20
        Width = 7
        Height = 14
        Caption = '2'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC2: TLabel
        Left = 118
        Top = 38
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol2: TPaintBox
        Tag = 1
        Left = 64
        Top = 22
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblSalvoNumber2: TLabel
        Left = 117
        Top = 19
        Width = 14
        Height = 14
        Caption = '02'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse2: TLabel
        Left = 121
        Top = 56
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo2: TLabel
        Left = 20
        Top = 41
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo2: TLabel
        Left = 8
        Top = 56
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pnlNumTorpedo2: TPanel
        Left = 10
        Top = 19
        Width = 33
        Height = 20
        Caption = '2'
        Color = clLime
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        Visible = False
      end
    end
    object pnlTorpedo3: TPanel
      Tag = 2
      Left = 149
      Top = 87
      Width = 140
      Height = 80
      TabOrder = 2
      OnClick = pnlTorpedoClick
      object shpFrameTorpedo3: TShape
        Left = 5
        Top = 16
        Width = 130
        Height = 60
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object shpTorpedo3: TShape
        Left = 138
        Top = 0
        Width = 1
        Height = 95
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo3: TLabel
        Left = 38
        Top = 0
        Width = 64
        Height = 14
        Alignment = taCenter
        Caption = 'MSI-SRC-SA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber3: TLabel
        Left = 10
        Top = 18
        Width = 7
        Height = 14
        Caption = '3'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC3: TLabel
        Left = 118
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol3: TPaintBox
        Tag = 2
        Left = 62
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblSalvoNumber3: TLabel
        Left = 117
        Top = 20
        Width = 14
        Height = 14
        Caption = '03'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse3: TLabel
        Left = 121
        Top = 57
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo3: TLabel
        Left = 19
        Top = 44
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo3: TLabel
        Left = 7
        Top = 60
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pnlNumTorpedo3: TPanel
        Left = 9
        Top = 19
        Width = 33
        Height = 20
        Caption = '3'
        Color = clLime
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        Visible = False
      end
    end
    object pnlTorpedo4: TPanel
      Tag = 3
      Left = 7
      Top = 87
      Width = 140
      Height = 80
      TabOrder = 3
      OnClick = pnlTorpedoClick
      object shpFrameTorpedo4: TShape
        Left = 5
        Top = 16
        Width = 130
        Height = 60
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object shpTorpedo4: TShape
        Left = 0
        Top = 0
        Width = 1
        Height = 95
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo4: TLabel
        Left = 38
        Top = 1
        Width = 73
        Height = 14
        Alignment = taCenter
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber4: TLabel
        Left = 9
        Top = 19
        Width = 7
        Height = 14
        Caption = '4'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC4: TLabel
        Left = 118
        Top = 41
        Width = 12
        Height = 14
        Caption = 'W'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol4: TPaintBox
        Tag = 3
        Left = 63
        Top = 21
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblSalvoNumber4: TLabel
        Left = 116
        Top = 21
        Width = 14
        Height = 14
        Caption = '04'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse4: TLabel
        Left = 121
        Top = 60
        Width = 6
        Height = 14
        Caption = 'F'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo4: TLabel
        Left = 19
        Top = 42
        Width = 8
        Height = 14
        Caption = 'A'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo4: TLabel
        Left = 8
        Top = 58
        Width = 42
        Height = 14
        Caption = '110002'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pnlNumTorpedo4: TPanel
        Left = 9
        Top = 19
        Width = 33
        Height = 20
        Caption = '4'
        Color = clLime
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        Visible = False
      end
    end
    object pnlTorpedo5: TPanel
      Tag = 4
      Left = 149
      Top = 168
      Width = 140
      Height = 80
      TabOrder = 4
      OnClick = pnlTorpedoClick
      object shpFrameTorpedo5: TShape
        Left = 4
        Top = 16
        Width = 130
        Height = 60
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object shpTorpedo5: TShape
        Left = 138
        Top = 0
        Width = 1
        Height = 95
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo5: TLabel
        Left = 38
        Top = 2
        Width = 73
        Height = 14
        Alignment = taCenter
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber5: TLabel
        Left = 10
        Top = 22
        Width = 7
        Height = 14
        Caption = '5'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC5: TLabel
        Left = 119
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol5: TPaintBox
        Tag = 4
        Left = 63
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblActiveToSo5: TLabel
        Left = 20
        Top = 43
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo5: TLabel
        Left = 9
        Top = 59
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblSalvoNumber5: TLabel
        Left = 117
        Top = 20
        Width = 14
        Height = 14
        Caption = '05'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse5: TLabel
        Left = 122
        Top = 57
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pnlNumTorpedo5: TPanel
        Left = 9
        Top = 20
        Width = 33
        Height = 20
        Caption = '5'
        Color = clLime
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        Visible = False
      end
    end
    object pnlTorpedo6: TPanel
      Tag = 5
      Left = 7
      Top = 168
      Width = 140
      Height = 80
      TabOrder = 5
      OnClick = pnlTorpedoClick
      object shpFrameTorpedo6: TShape
        Left = 5
        Top = 16
        Width = 130
        Height = 60
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object shpTorpedo6: TShape
        Left = 0
        Top = 0
        Width = 1
        Height = 95
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo6: TLabel
        Left = 43
        Top = 2
        Width = 64
        Height = 14
        Alignment = taCenter
        Caption = 'MAN-HORIZ'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber6: TLabel
        Left = 12
        Top = 22
        Width = 7
        Height = 14
        Caption = '6'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC6: TLabel
        Left = 120
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol6: TPaintBox
        Tag = 5
        Left = 63
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblSalvoNumber6: TLabel
        Left = 119
        Top = 20
        Width = 14
        Height = 14
        Caption = '06'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse6: TLabel
        Left = 123
        Top = 57
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo6: TLabel
        Left = 18
        Top = 44
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo6: TLabel
        Left = 9
        Top = 61
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pnlNumTorpedo6: TPanel
        Left = 9
        Top = 20
        Width = 33
        Height = 20
        Caption = '6'
        Color = clLime
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        Visible = False
      end
    end
    object pnlTorpedo7: TPanel
      Tag = 6
      Left = 149
      Top = 249
      Width = 140
      Height = 80
      TabOrder = 6
      OnClick = pnlTorpedoClick
      object shpFrameTorpedo7: TShape
        Left = 4
        Top = 15
        Width = 130
        Height = 60
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object shpTorpedo7: TShape
        Left = 138
        Top = 0
        Width = 1
        Height = 80
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo7: TLabel
        Left = 39
        Top = 1
        Width = 73
        Height = 14
        Alignment = taCenter
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber7: TLabel
        Left = 11
        Top = 20
        Width = 7
        Height = 14
        Caption = '7'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC7: TLabel
        Left = 118
        Top = 39
        Width = 12
        Height = 16
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol7: TPaintBox
        Tag = 6
        Left = 62
        Top = 22
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblSalvoNumber7: TLabel
        Left = 116
        Top = 21
        Width = 14
        Height = 16
        Caption = '07'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse7: TLabel
        Left = 121
        Top = 55
        Width = 7
        Height = 16
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo7: TLabel
        Left = 18
        Top = 42
        Width = 8
        Height = 16
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo7: TLabel
        Left = 7
        Top = 57
        Width = 42
        Height = 16
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pnlNumTorpedo7: TPanel
        Left = 8
        Top = 18
        Width = 33
        Height = 20
        Caption = '7'
        Color = clLime
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        Visible = False
      end
    end
    object pnlTorpedo8: TPanel
      Tag = 7
      Left = 8
      Top = 249
      Width = 140
      Height = 80
      TabOrder = 7
      OnClick = pnlTorpedoClick
      object shpFrameTorpedo8: TShape
        Left = 4
        Top = 15
        Width = 130
        Height = 60
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object shpTorpedo8: TShape
        Left = 0
        Top = 0
        Width = 1
        Height = 80
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo8: TLabel
        Left = 39
        Top = 2
        Width = 73
        Height = 14
        Alignment = taCenter
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber8: TLabel
        Left = 10
        Top = 22
        Width = 7
        Height = 14
        Caption = '8'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC8: TLabel
        Left = 118
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol8: TPaintBox
        Tag = 7
        Left = 62
        Top = 22
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblSalvoNumber8: TLabel
        Left = 116
        Top = 20
        Width = 14
        Height = 14
        Caption = '08'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse8: TLabel
        Left = 121
        Top = 57
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo8: TLabel
        Left = 18
        Top = 45
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo8: TLabel
        Left = 7
        Top = 59
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pnlNumTorpedo8: TPanel
        Left = 7
        Top = 18
        Width = 33
        Height = 20
        Caption = '8'
        Color = clLime
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentBackground = False
        ParentFont = False
        TabOrder = 0
        Visible = False
      end
    end
  end
  object tmrDrawTube: TTimer
    OnTimer = tmrDrawTubeTimer
    Left = 80
    Top = 30
  end
end
