object frmHomingCommands: TfrmHomingCommands
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 196
  ClientWidth = 265
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 297
    Height = 241
    BevelEdges = []
    BevelOuter = bvNone
    TabOrder = 0
    object btnAutoAcoustic: TVrDemoButton
      Left = 14
      Top = 14
      Width = 233
      Height = 33
      FontEnter.Charset = ANSI_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -13
      FontEnter.Name = 'Tahoma'
      FontEnter.Style = []
      FontLeave.Charset = ANSI_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -13
      FontLeave.Name = 'Tahoma'
      FontLeave.Style = []
      OutlineColor = clWhite
      ShadowColor = clBlack
      HighlightColor = clBlack
      FocusColor = clBlack
      Caption = 'Auto Acoustic'
      Color = clBlack
      TabOrder = 0
    end
    object btnToSoPN: TVrDemoButton
      Left = 14
      Top = 48
      Width = 233
      Height = 33
      FontEnter.Charset = ANSI_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -13
      FontEnter.Name = 'Tahoma'
      FontEnter.Style = []
      FontLeave.Charset = ANSI_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -13
      FontLeave.Name = 'Tahoma'
      FontLeave.Style = []
      OutlineColor = clWhite
      ShadowColor = clBlack
      HighlightColor = clBlack
      FocusColor = clBlack
      Caption = 'ToSo PN'
      Color = clBlack
      TabOrder = 1
    end
    object btnToSoPN3D: TVrDemoButton
      Left = 14
      Top = 82
      Width = 233
      Height = 33
      FontEnter.Charset = ANSI_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -13
      FontEnter.Name = 'Tahoma'
      FontEnter.Style = []
      FontLeave.Charset = ANSI_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -13
      FontLeave.Name = 'Tahoma'
      FontLeave.Style = []
      OutlineColor = clWhite
      ShadowColor = clBlack
      HighlightColor = clBlack
      FocusColor = clBlack
      Caption = 'ToSo PN 3D'
      Color = clBlack
      TabOrder = 2
    end
    object btnToSoDPC: TVrDemoButton
      Left = 14
      Top = 116
      Width = 233
      Height = 33
      FontEnter.Charset = ANSI_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -13
      FontEnter.Name = 'Tahoma'
      FontEnter.Style = []
      FontLeave.Charset = ANSI_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -13
      FontLeave.Name = 'Tahoma'
      FontLeave.Style = []
      OutlineColor = clWhite
      ShadowColor = clBlack
      HighlightColor = clBlack
      FocusColor = clBlack
      Caption = 'ToSo DPC'
      Color = clBlack
      TabOrder = 3
    end
    object btnWake: TVrDemoButton
      Left = 14
      Top = 150
      Width = 233
      Height = 33
      FontEnter.Charset = ANSI_CHARSET
      FontEnter.Color = clWhite
      FontEnter.Height = -13
      FontEnter.Name = 'Tahoma'
      FontEnter.Style = []
      FontLeave.Charset = ANSI_CHARSET
      FontLeave.Color = clWhite
      FontLeave.Height = -13
      FontLeave.Name = 'Tahoma'
      FontLeave.Style = []
      OutlineColor = clWhite
      ShadowColor = clBlack
      HighlightColor = clBlack
      FocusColor = clBlack
      Caption = 'Wake'
      Color = clBlack
      TabOrder = 4
    end
  end
end
