object frmHomingStatusPlot: TfrmHomingStatusPlot
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 355
  ClientWidth = 557
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 649
    Height = 377
    BevelEdges = []
    BevelOuter = bvNone
    Color = clBlack
    ParentBackground = False
    TabOrder = 0
    object TabHomingStatusPlot: TAdvSmoothTabPager
      Left = 12
      Top = 3
      Width = 533
      Height = 342
      Fill.Color = clBlack
      Fill.ColorTo = -1
      Fill.ColorMirror = -1
      Fill.ColorMirrorTo = -1
      Fill.GradientType = gtVertical
      Fill.GradientMirrorType = gtSolid
      Fill.BorderColor = clBlack
      Fill.Rounding = 0
      Fill.ShadowColor = -1
      Fill.ShadowOffset = 0
      Fill.Glow = gmNone
      Fill.GlowGradientColor = -1
      Fill.GlowRadialColor = -1
      Transparent = False
      ActivePage = TabHomingStatus
      TabTextOrientation = toHorizontal
      TabSettings.LeftMargin = 0
      TabSettings.RightMargin = 0
      TabSettings.StartMargin = 0
      TabSettings.Height = 40
      TabSettings.Spacing = 5
      TabSettings.Width = 300
      TabReorder = False
      TabOrder = 0
      Touch.ParentTabletOptions = False
      Touch.TabletOptions = [toPressAndHold]
      TMSStyle = 4
      object TabHomingStatus: TAdvSmoothTabPage
        Left = 1
        Top = 40
        Width = 531
        Height = 300
        Caption = 'Homing Status'
        PageAppearance.Color = -1
        PageAppearance.ColorTo = -1
        PageAppearance.ColorMirror = -1
        PageAppearance.ColorMirrorTo = -1
        PageAppearance.GradientType = gtVertical
        PageAppearance.GradientMirrorType = gtVertical
        PageAppearance.BorderColor = -1
        PageAppearance.Rounding = 0
        PageAppearance.ShadowOffset = 0
        PageAppearance.Glow = gmNone
        TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Appearance.Font.Color = clBlack
        TabAppearance.Appearance.Font.Height = -11
        TabAppearance.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Appearance.Font.Style = []
        TabAppearance.Appearance.SimpleLayout = True
        TabAppearance.Appearance.Rounding = 0
        TabAppearance.Status.Caption = '0'
        TabAppearance.Status.Appearance.Fill.Color = clRed
        TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
        TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
        TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
        TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
        TabAppearance.Status.Appearance.Fill.BorderColor = clGray
        TabAppearance.Status.Appearance.Fill.Rounding = 0
        TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
        TabAppearance.Status.Appearance.Fill.Glow = gmNone
        TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Status.Appearance.Font.Color = clWhite
        TabAppearance.Status.Appearance.Font.Height = -11
        TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Status.Appearance.Font.Style = []
        TabAppearance.BevelColor = clWhite
        TabAppearance.BevelColorDown = clWhite
        TabAppearance.BevelColorSelected = clWhite
        TabAppearance.BevelColorDisabled = clWhite
        TabAppearance.Color = clWhite
        TabAppearance.ColorDown = clWhite
        TabAppearance.ColorSelected = 16250613
        TabAppearance.ColorHot = 16776701
        TabAppearance.ColorDisabled = clWhite
        TabAppearance.ColorTextHot = clWhite
        TabAppearance.ColorTextSelected = -1
        TMSStyle = 20
        object Label1: TLabel
          Left = 208
          Top = 14
          Width = 48
          Height = 16
          Caption = 'Torpedo'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblValTorpedo: TLabel
          Left = 288
          Top = 14
          Width = 7
          Height = 16
          Caption = '1'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object Label2: TLabel
          Left = 336
          Top = 14
          Width = 43
          Height = 16
          Caption = 'Contact'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblValContact: TLabel
          Left = 416
          Top = 14
          Width = 21
          Height = 16
          Caption = '101'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblToSoHomingPN3D: TLabel
          Left = 10
          Top = 54
          Width = 114
          Height = 16
          Caption = 'ToSo homing PN 3D'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblTgtLostSub: TLabel
          Left = 312
          Top = 94
          Width = 72
          Height = 16
          Caption = 'Tgt Lost Sub'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblLongRangeAttack: TLabel
          Left = 10
          Top = 144
          Width = 106
          Height = 16
          Caption = 'Long Range Attack'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblToSotargetacquiredclose: TLabel
          Left = 10
          Top = 278
          Width = 154
          Height = 16
          Caption = 'ToSo target acquired close'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object lblCloseInSub: TLabel
          Left = 147
          Top = 259
          Width = 73
          Height = 16
          Caption = 'Close-In Sub'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object pbTgtLostSub: TPaintBox
          Left = 408
          Top = 120
          Width = 81
          Height = 41
          OnPaint = pbTgtLostSubPaint
        end
        object pbWakeLost: TPaintBox
          Left = 312
          Top = 208
          Width = 81
          Height = 41
          OnPaint = pbWakeLostPaint
        end
        object Label3: TLabel
          Left = 408
          Top = 238
          Width = 104
          Height = 16
          Caption = 'Wake Lost/Search'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object pbWakeAttack: TPaintBox
          Left = 152
          Top = 96
          Width = 81
          Height = 41
          OnPaint = pbWakeAttackPaint
        end
        object lblWakeAttaack: TLabel
          Left = 64
          Top = 78
          Width = 71
          Height = 16
          Caption = 'Wake Attack'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
        end
        object pbLongRange: TPaintBox
          Left = 16
          Top = 176
          Width = 177
          Height = 73
          OnPaint = pbLongRangePaint
        end
      end
      object TabToSoCoverage: TAdvSmoothTabPage
        Left = 1
        Top = 40
        Width = 531
        Height = 300
        Caption = 'Horizontal/Vertical ToSo Coverage'
        PageAppearance.Color = clBlack
        PageAppearance.ColorTo = clBlack
        PageAppearance.ColorMirror = clBlack
        PageAppearance.ColorMirrorTo = clBlack
        PageAppearance.GradientType = gtVertical
        PageAppearance.GradientMirrorType = gtVertical
        PageAppearance.BackGroundPicturePosition = ppCenterCenter
        PageAppearance.BorderColor = clBlack
        PageAppearance.Rounding = 0
        PageAppearance.ShadowOffset = 0
        PageAppearance.Glow = gmNone
        PageAppearance.GlowGradientColor = clBlack
        PageAppearance.GlowRadialColor = clBlack
        TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Appearance.Font.Color = clBlack
        TabAppearance.Appearance.Font.Height = -13
        TabAppearance.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Appearance.Font.Style = []
        TabAppearance.Appearance.SimpleLayout = True
        TabAppearance.Appearance.Rounding = 0
        TabAppearance.Status.Caption = '0'
        TabAppearance.Status.Appearance.Fill.Color = clRed
        TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
        TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
        TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
        TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
        TabAppearance.Status.Appearance.Fill.BorderColor = clGray
        TabAppearance.Status.Appearance.Fill.Rounding = 0
        TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
        TabAppearance.Status.Appearance.Fill.Glow = gmNone
        TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Status.Appearance.Font.Color = clWhite
        TabAppearance.Status.Appearance.Font.Height = -11
        TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Status.Appearance.Font.Style = []
        TabAppearance.BevelColor = clWhite
        TabAppearance.BevelColorDown = clWhite
        TabAppearance.BevelColorSelected = clWhite
        TabAppearance.BevelColorDisabled = clWhite
        TabAppearance.Color = clWhite
        TabAppearance.ColorDown = 16250613
        TabAppearance.ColorSelected = 16250613
        TabAppearance.ColorHot = 16776701
        TabAppearance.ColorDisabled = 15921906
        TMSStyle = 20
        object pbToSoCoveragePlot: TPaintBox
          Left = 24
          Top = 32
          Width = 481
          Height = 233
          OnPaint = pbToSoCoveragePlotPaint
        end
      end
    end
  end
end
