object frmTorpedoTubeStatusWindow: TfrmTorpedoTubeStatusWindow
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 337
  ClientWidth = 296
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 296
    Height = 337
    BevelEdges = []
    BevelOuter = bvNone
    TabOrder = 0
    object pnlTorpedo2: TPanel
      Left = 8
      Top = 6
      Width = 140
      Height = 80
      TabOrder = 0
      object shpFrameTorpedo2: TShape
        Left = 5
        Top = 16
        Width = 133
        Height = 62
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo2: TLabel
        Left = 37
        Top = 1
        Width = 73
        Height = 14
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber2: TLabel
        Left = 11
        Top = 20
        Width = 7
        Height = 14
        Caption = '2'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC2: TLabel
        Left = 123
        Top = 40
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol2: TPaintBox
        Tag = 1
        Left = 69
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblNumberTorpedo2: TLabel
        Left = 121
        Top = 25
        Width = 14
        Height = 14
        Caption = '02'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse2: TLabel
        Left = 126
        Top = 58
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo2: TLabel
        Left = 19
        Top = 44
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo2: TLabel
        Left = 7
        Top = 59
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pbFrameTorpedo2: TPaintBox
        Left = -5
        Top = -3
        Width = 140
        Height = 80
        OnPaint = pbFrameTorpedo1Paint
      end
    end
    object pnlTorpedo4: TPanel
      Left = 7
      Top = 87
      Width = 140
      Height = 80
      TabOrder = 1
      object shpFrameTorpedo4: TShape
        Left = 7
        Top = 19
        Width = 130
        Height = 57
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo4: TLabel
        Left = 38
        Top = 2
        Width = 73
        Height = 14
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber4: TLabel
        Left = 9
        Top = 25
        Width = 7
        Height = 14
        Caption = '4'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC4: TLabel
        Left = 123
        Top = 41
        Width = 12
        Height = 14
        Caption = 'W'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol4: TPaintBox
        Tag = 3
        Left = 69
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblNumberTorpedo4: TLabel
        Left = 121
        Top = 21
        Width = 14
        Height = 14
        Caption = '04'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse4: TLabel
        Left = 126
        Top = 60
        Width = 6
        Height = 14
        Caption = 'F'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo4: TLabel
        Left = 19
        Top = 46
        Width = 8
        Height = 14
        Caption = 'A'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo4: TLabel
        Left = 8
        Top = 62
        Width = 42
        Height = 14
        Caption = '110002'
        FocusControl = pnlTorpedo2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pbFrameTorpedo4: TPaintBox
        Left = 0
        Top = 0
        Width = 140
        Height = 80
        OnPaint = pbFrameTorpedo1Paint
      end
    end
    object pnlTorpedo6: TPanel
      Left = 7
      Top = 168
      Width = 140
      Height = 80
      TabOrder = 2
      object shpFrameTorpedo: TShape
        Left = 8
        Top = 20
        Width = 130
        Height = 57
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo6: TLabel
        Left = 43
        Top = 3
        Width = 64
        Height = 14
        Caption = 'MAN-HORIZ'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber6: TLabel
        Left = 10
        Top = 24
        Width = 7
        Height = 14
        Caption = '6'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC6: TLabel
        Left = 123
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol6: TPaintBox
        Tag = 5
        Left = 69
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblNumberTorpedo6: TLabel
        Left = 122
        Top = 20
        Width = 14
        Height = 14
        Caption = '06'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse6: TLabel
        Left = 126
        Top = 57
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo6: TLabel
        Left = 17
        Top = 45
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo6: TLabel
        Left = 8
        Top = 62
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pbFrameTorpedo6: TPaintBox
        Left = 0
        Top = 0
        Width = 140
        Height = 80
        OnPaint = pbFrameTorpedo1Paint
      end
    end
    object pnlTorpedo8: TPanel
      Left = 8
      Top = 249
      Width = 140
      Height = 80
      TabOrder = 3
      object shpFrameTorpedo8: TShape
        Left = 8
        Top = 19
        Width = 130
        Height = 57
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo8: TLabel
        Left = 39
        Top = 2
        Width = 73
        Height = 14
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber8: TLabel
        Left = 10
        Top = 22
        Width = 7
        Height = 14
        Caption = '8'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC8: TLabel
        Left = 123
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol8: TPaintBox
        Tag = 7
        Left = 69
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblNumberTorpedo8: TLabel
        Left = 121
        Top = 20
        Width = 14
        Height = 14
        Caption = '07'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse8: TLabel
        Left = 126
        Top = 57
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo8: TLabel
        Left = 17
        Top = 48
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo8: TLabel
        Left = 6
        Top = 62
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pbFrameTorpedo8: TPaintBox
        Left = 0
        Top = 0
        Width = 140
        Height = 80
        OnPaint = pbFrameTorpedo1Paint
      end
    end
    object pnlTorpedo3: TPanel
      Left = 149
      Top = 87
      Width = 140
      Height = 80
      TabOrder = 5
      object shpFrameTorpedo3: TShape
        Left = 8
        Top = 19
        Width = 130
        Height = 57
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo3: TLabel
        Left = 38
        Top = 2
        Width = 64
        Height = 14
        Caption = 'MSI-SRC-SA'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber3: TLabel
        Left = 10
        Top = 25
        Width = 7
        Height = 14
        Caption = '3'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC3: TLabel
        Left = 123
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol3: TPaintBox
        Tag = 2
        Left = 69
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblNumberTorpedo3: TLabel
        Left = 122
        Top = 20
        Width = 14
        Height = 14
        Caption = '03'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse3: TLabel
        Left = 126
        Top = 57
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo3: TLabel
        Left = 23
        Top = 46
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo3: TLabel
        Left = 11
        Top = 62
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pbFrameTorpedo3: TPaintBox
        Left = 0
        Top = 0
        Width = 140
        Height = 80
        OnPaint = pbFrameTorpedo1Paint
      end
    end
    object pnlTorpedo5: TPanel
      Left = 149
      Top = 168
      Width = 140
      Height = 80
      TabOrder = 6
      object shpFrameTorpedo5: TShape
        Left = 8
        Top = 17
        Width = 130
        Height = 57
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo5: TLabel
        Left = 38
        Top = 2
        Width = 73
        Height = 14
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber5: TLabel
        Left = 10
        Top = 22
        Width = 7
        Height = 14
        Caption = '5'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC5: TLabel
        Left = 123
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol5: TPaintBox
        Tag = 4
        Left = 69
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblActiveToSo5: TLabel
        Left = 20
        Top = 43
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo5: TLabel
        Left = 9
        Top = 59
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumberTorpedo5: TLabel
        Left = 121
        Top = 20
        Width = 14
        Height = 14
        Caption = '05'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse5: TLabel
        Left = 126
        Top = 57
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pbFrameTorpedo5: TPaintBox
        Left = 0
        Top = 0
        Width = 140
        Height = 80
        OnPaint = pbFrameTorpedo1Paint
      end
    end
    object pnlTorpedo7: TPanel
      Left = 149
      Top = 249
      Width = 140
      Height = 80
      TabOrder = 7
      object shpFrameTorpedo7: TShape
        Left = 9
        Top = 16
        Width = 130
        Height = 57
        Brush.Color = clBlack
        Pen.Color = clWhite
      end
      object lblTorpedo7: TLabel
        Left = 39
        Top = 1
        Width = 73
        Height = 14
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber7: TLabel
        Left = 11
        Top = 20
        Width = 7
        Height = 14
        Caption = '7'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC7: TLabel
        Left = 123
        Top = 39
        Width = 12
        Height = 16
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol7: TPaintBox
        Tag = 6
        Left = 69
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblNumberTorpedo7: TLabel
        Left = 121
        Top = 21
        Width = 14
        Height = 16
        Caption = '07'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse7: TLabel
        Left = 126
        Top = 55
        Width = 7
        Height = 16
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblActiveToSo7: TLabel
        Left = 18
        Top = 42
        Width = 8
        Height = 16
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo7: TLabel
        Left = 7
        Top = 57
        Width = 42
        Height = 16
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pbFrameTorpedo7: TPaintBox
        Left = 0
        Top = 0
        Width = 140
        Height = 80
        OnPaint = pbFrameTorpedo1Paint
      end
    end
    object pnlTorpedo1: TPanel
      Left = 149
      Top = 6
      Width = 140
      Height = 80
      TabOrder = 4
      object shpFrameTorpedo1: TShape
        Left = 8
        Top = 17
        Width = 130
        Height = 62
        Brush.Color = clBlack
        Pen.Color = clWhite
        Visible = False
      end
      object lblTorpedo1: TLabel
        Left = 35
        Top = 1
        Width = 73
        Height = 14
        Caption = 'TORP READY'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumber1: TLabel
        Left = 10
        Top = 19
        Width = 7
        Height = 14
        Caption = '1'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object lblWTSRC1: TLabel
        Left = 123
        Top = 39
        Width = 12
        Height = 14
        Caption = 'W'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object pbTubeSymbol1: TPaintBox
        Left = 69
        Top = 23
        Width = 51
        Height = 51
        OnPaint = pbTubeSymbol1Paint
      end
      object lblActiveToSo1: TLabel
        Left = 19
        Top = 44
        Width = 8
        Height = 14
        Caption = 'A'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblValueTorpedo1: TLabel
        Left = 7
        Top = 59
        Width = 42
        Height = 14
        Caption = '110002'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblFuse1: TLabel
        Left = 125
        Top = 56
        Width = 6
        Height = 14
        Caption = 'F'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object lblNumberTorpedo1: TLabel
        Left = 122
        Top = 19
        Width = 14
        Height = 14
        Caption = '01'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Visible = False
      end
      object pbFrameTorpedo1: TPaintBox
        Left = 0
        Top = 0
        Width = 140
        Height = 80
        OnPaint = pbFrameTorpedo1Paint
      end
    end
  end
  object tmrDrawTube: TTimer
    OnTimer = tmrDrawTubeTimer
    Left = 149
    Top = 65521
  end
end
