object frmMissileMonitor: TfrmMissileMonitor
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'frmMissileMonitor'
  ClientHeight = 850
  ClientWidth = 954
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 80
    Width = 954
    Height = 110
    Align = alTop
    Caption = 'Panel1'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 0
  end
  object Panel2: TPanel
    Left = 0
    Top = 190
    Width = 954
    Height = 110
    Align = alTop
    Caption = 'Panel1'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 1
  end
  object Panel3: TPanel
    Left = 0
    Top = 300
    Width = 954
    Height = 110
    Align = alTop
    Caption = 'Panel1'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 2
  end
  object Panel4: TPanel
    Left = 0
    Top = 410
    Width = 954
    Height = 110
    Align = alTop
    Caption = 'Panel1'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 3
  end
  object Panel5: TPanel
    Left = 0
    Top = 520
    Width = 954
    Height = 110
    Align = alTop
    Caption = 'Panel1'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 4
  end
  object Panel6: TPanel
    Left = 0
    Top = 630
    Width = 954
    Height = 110
    Align = alTop
    Caption = 'Panel1'
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 5
  end
  object pnlMMonitorHeader: TPanel
    Left = 0
    Top = 0
    Width = 954
    Height = 80
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 6
    object Label1: TLabel
      Left = 16
      Top = 52
      Width = 116
      Height = 18
      Caption = 'Input M. No. :'
      Font.Charset = ANSI_CHARSET
      Font.Color = 6168865
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object edtInputMissileNumMMon: TEdit
      Left = 152
      Top = 50
      Width = 121
      Height = 24
      Color = 16732757
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = '1'
    end
  end
  object Panel8: TPanel
    Left = 0
    Top = 740
    Width = 954
    Height = 110
    Align = alTop
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 7
    object Label2: TLabel
      Left = 10
      Top = 10
      Width = 75
      Height = 18
      Caption = 'M. state:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label3: TLabel
      Left = 10
      Top = 32
      Width = 79
      Height = 18
      Caption = 'INSstate:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblMissileState: TLabel
      Left = 91
      Top = 10
      Width = 40
      Height = 18
      Caption = '0000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblINSState: TLabel
      Left = 95
      Top = 32
      Width = 40
      Height = 18
      Caption = '0000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label4: TLabel
      Left = 157
      Top = 10
      Width = 68
      Height = 18
      Caption = 'M. step:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label5: TLabel
      Left = 157
      Top = 32
      Width = 73
      Height = 18
      Caption = 'In Port1:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblMissileStep: TLabel
      Left = 231
      Top = 10
      Width = 40
      Height = 18
      Caption = '0000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblInPort1: TLabel
      Left = 236
      Top = 32
      Width = 42
      Height = 18
      Caption = 'AA55'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label6: TLabel
      Left = 297
      Top = 10
      Width = 87
      Height = 18
      Caption = 'INS/GNSS:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label7: TLabel
      Left = 297
      Top = 32
      Width = 73
      Height = 18
      Caption = 'In Port2:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblINSGNSS: TLabel
      Left = 390
      Top = 10
      Width = 41
      Height = 18
      Caption = '020A'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblInPort2: TLabel
      Left = 376
      Top = 32
      Width = 41
      Height = 18
      Caption = '946B'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label8: TLabel
      Left = 456
      Top = 10
      Width = 94
      Height = 18
      Caption = 'Seer check:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label9: TLabel
      Left = 456
      Top = 32
      Width = 86
      Height = 18
      Caption = 'Out Port1:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblSeerCheck: TLabel
      Left = 556
      Top = 10
      Width = 41
      Height = 18
      Caption = '000A'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblOutPort1: TLabel
      Left = 548
      Top = 32
      Width = 40
      Height = 18
      Caption = '04FB'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label12: TLabel
      Left = 622
      Top = 10
      Width = 77
      Height = 18
      Caption = 'PLC CHK:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object Label13: TLabel
      Left = 622
      Top = 32
      Width = 86
      Height = 18
      Caption = 'Out Port2:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblPLCCHK: TLabel
      Left = 705
      Top = 10
      Width = 41
      Height = 18
      Caption = '000A'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object lblOutPort2: TLabel
      Left = 714
      Top = 32
      Width = 40
      Height = 18
      Caption = '0000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
end
