object frmLaunchData: TfrmLaunchData
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'frmLaunchData'
  ClientHeight = 850
  ClientWidth = 954
  Color = clMedGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object pnlLaunchDataHeader: TPanel
    Left = 0
    Top = 0
    Width = 954
    Height = 65
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 0
    object Label1: TLabel
      Left = 12
      Top = 21
      Width = 137
      Height = 23
      Caption = 'Input M. No. :'
      Font.Charset = ANSI_CHARSET
      Font.Color = 6168865
      Font.Height = -19
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
    object edtInputMissileNumLD: TEdit
      Left = 155
      Top = 17
      Width = 238
      Height = 31
      Color = 16732757
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = '1'
    end
  end
  object Panel1: TPanel
    Left = 0
    Top = 65
    Width = 954
    Height = 176
    Align = alTop
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    object pnlLeft1: TPanel
      Left = 1
      Top = 1
      Width = 318
      Height = 174
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 0
      object pnl_Row1_L1: TPanel
        Left = 0
        Top = 0
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        ExplicitLeft = 2
        ExplicitTop = 9
        ExplicitWidth = 475
        object Panel2: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label40: TLabel
            Left = 10
            Top = 9
            Width = 53
            Height = 18
            Caption = 'M. No.'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlMissileNum: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblMissileNumVal: TLabel
            Left = 75
            Top = 9
            Width = 10
            Height = 18
            Alignment = taCenter
            Caption = '0'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row2_L1: TPanel
        Left = 0
        Top = 35
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        ExplicitLeft = 2
        ExplicitTop = 52
        object Panel5: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label2: TLabel
            Left = 10
            Top = 9
            Width = 82
            Height = 18
            Caption = 'Lock Time'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlLockTime: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          ExplicitHeight = 27
          object lblLockTime: TLabel
            Left = 19
            Top = 8
            Width = 74
            Height = 18
            Alignment = taCenter
            Caption = '00:00:00'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row3_L1: TPanel
        Left = 0
        Top = 70
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        ExplicitLeft = 2
        ExplicitTop = 80
        object Panel6: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label3: TLabel
            Left = 10
            Top = 9
            Width = 57
            Height = 18
            Caption = 'T. Type'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTType: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTTypeVal: TLabel
            Left = 19
            Top = 8
            Width = 85
            Height = 18
            Alignment = taCenter
            Caption = 'In the sea'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row4_L1: TPanel
        Left = 0
        Top = 105
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        ExplicitLeft = 2
        ExplicitTop = 80
        object Panel7: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label4: TLabel
            Left = 10
            Top = 6
            Width = 45
            Height = 18
            Caption = 'T.NO.'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTNumber: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTNumberVal: TLabel
            Left = 19
            Top = 8
            Width = 40
            Height = 18
            Alignment = taCenter
            Caption = '0000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row5_L1: TPanel
        Left = 0
        Top = 140
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        ExplicitLeft = 2
        ExplicitTop = 150
        object Panel8: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label5: TLabel
            Left = 10
            Top = 6
            Width = 104
            Height = 18
            Caption = 'T.LONG(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTLong1: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTLongVal1: TLabel
            Left = 63
            Top = 8
            Width = 86
            Height = 18
            Alignment = taRightJustify
            Caption = '000.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
    end
    object pnlMid1: TPanel
      Left = 319
      Top = 1
      Width = 318
      Height = 174
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 1
      object pnl_Row1_M1: TPanel
        Left = 0
        Top = 0
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        ExplicitLeft = 2
        ExplicitTop = 9
        object Panel4: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label6: TLabel
            Left = 10
            Top = 9
            Width = 87
            Height = 18
            Caption = 'T.LAT(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTLat: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTLatVal: TLabel
            Left = 63
            Top = 9
            Width = 86
            Height = 18
            Alignment = taRightJustify
            Caption = '000.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row2_M1: TPanel
        Left = 0
        Top = 35
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        ExplicitLeft = 2
        ExplicitTop = 44
        object Panel11: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label8: TLabel
            Left = 10
            Top = 9
            Width = 87
            Height = 18
            Caption = 'T.RNG(km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTRng: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTRngVal: TLabel
            Left = 83
            Top = 9
            Width = 66
            Height = 18
            Alignment = taRightJustify
            Caption = '000.000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row3_M1: TPanel
        Left = 0
        Top = 70
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        ExplicitLeft = 2
        ExplicitTop = 79
        object Panel14: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label10: TLabel
            Left = 6
            Top = 11
            Width = 93
            Height = 18
            Caption = 'T.AZM(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTAzmVal: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTAzmVal: TLabel
            Left = 83
            Top = 9
            Width = 66
            Height = 18
            Alignment = taRightJustify
            Caption = '000.000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row4_M1: TPanel
        Left = 0
        Top = 105
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        ExplicitLeft = 2
        ExplicitTop = 114
        object Panel17: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label12: TLabel
            Left = 10
            Top = 6
            Width = 77
            Height = 18
            Caption = 'T.HGT(m)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTHgtVal: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTHgtVal: TLabel
            Left = 19
            Top = 8
            Width = 40
            Height = 18
            Alignment = taCenter
            Caption = '0000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row5_M1: TPanel
        Left = 0
        Top = 140
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        ExplicitLeft = 1
        ExplicitTop = 139
        object Panel20: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label14: TLabel
            Left = 10
            Top = 6
            Width = 119
            Height = 18
            Caption = 'Attack.A.(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlAttackA: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblAttackAVal: TLabel
            Left = 93
            Top = 9
            Width = 56
            Height = 18
            Alignment = taRightJustify
            Caption = '00.000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
    end
    object pnlRight1: TPanel
      Left = 637
      Top = 1
      Width = 318
      Height = 174
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 2
      object pnl_Row1_R1: TPanel
        Left = 0
        Top = 0
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        ExplicitLeft = 1
        ExplicitTop = 1
        object Panel10: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label7: TLabel
            Left = 10
            Top = 9
            Width = 118
            Height = 18
            Caption = 'S. LONG (deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlSLong: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblSLongVal: TLabel
            Left = 63
            Top = 9
            Width = 86
            Height = 18
            Alignment = taRightJustify
            Caption = '000.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row2_R1: TPanel
        Left = 0
        Top = 35
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        ExplicitLeft = 1
        ExplicitTop = 36
        object Panel15: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label11: TLabel
            Left = 10
            Top = 9
            Width = 95
            Height = 18
            Caption = 'S. LAT(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlSLat: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblSLatVal: TLabel
            Left = 73
            Top = 9
            Width = 76
            Height = 18
            Alignment = taRightJustify
            Caption = '00.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row3_R1: TPanel
        Left = 0
        Top = 70
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        ExplicitLeft = 1
        ExplicitTop = 71
        object Panel19: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label15: TLabel
            Left = 6
            Top = 11
            Width = 100
            Height = 18
            Caption = 'S.Pitch(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlSPitch: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblSPitchVal: TLabel
            Left = 103
            Top = 9
            Width = 46
            Height = 18
            Alignment = taRightJustify
            Caption = '0.000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row4_R1: TPanel
        Left = 0
        Top = 105
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        ExplicitLeft = 1
        ExplicitTop = 106
        object Panel23: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          ExplicitLeft = -6
          object Label17: TLabel
            Left = 10
            Top = 6
            Width = 91
            Height = 18
            Caption = 'S.Roll(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlSRoll: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblSRollVal: TLabel
            Left = 103
            Top = 9
            Width = 46
            Height = 18
            Alignment = taRightJustify
            Caption = '0.000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row5_R1: TPanel
        Left = 0
        Top = 140
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        ExplicitLeft = 1
        ExplicitTop = 141
        object Panel22: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          ExplicitLeft = -3
          object Label19: TLabel
            Left = 10
            Top = 6
            Width = 96
            Height = 18
            Caption = 'S.HDG(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlSHdg: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblSHdgVal: TLabel
            Left = 83
            Top = 9
            Width = 66
            Height = 18
            Alignment = taRightJustify
            Caption = '000.000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 247
    Width = 954
    Height = 176
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    object pnlLeft2: TPanel
      Left = 1
      Top = 1
      Width = 318
      Height = 174
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 0
      object pnl_Row1_L2: TPanel
        Left = 0
        Top = 0
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object Panel13: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label9: TLabel
            Left = 10
            Top = 9
            Width = 104
            Height = 18
            Caption = 'T.LONG(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTLong2: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTLongVal2: TLabel
            Left = 63
            Top = 9
            Width = 86
            Height = 18
            Alignment = taRightJustify
            Caption = '000.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row2_L2: TPanel
        Left = 0
        Top = 35
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object Panel21: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label16: TLabel
            Left = 10
            Top = 9
            Width = 87
            Height = 18
            Caption = 'T.LAT(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlTLat2: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblTLatVal2: TLabel
            Left = 73
            Top = 9
            Width = 76
            Height = 18
            Alignment = taRightJustify
            Caption = '00.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row3_L2: TPanel
        Left = 0
        Top = 70
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object Panel26: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label20: TLabel
            Left = 10
            Top = 9
            Width = 105
            Height = 18
            Caption = 'Range 1(km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRange1: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblRange1Val: TLabel
            Left = 93
            Top = 8
            Width = 56
            Height = 18
            Alignment = taRightJustify
            Caption = '00.000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row4_L2: TPanel
        Left = 0
        Top = 105
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object Panel29: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label22: TLabel
            Left = 10
            Top = 6
            Width = 105
            Height = 18
            Caption = 'Range 2(km)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlRange2: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          ExplicitLeft = 158
          object lblRange2Val: TLabel
            Left = 93
            Top = 9
            Width = 56
            Height = 18
            Alignment = taRightJustify
            Caption = '00.000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row5_L2: TPanel
        Left = 0
        Top = 140
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        object Panel32: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label24: TLabel
            Left = 10
            Top = 6
            Width = 111
            Height = 18
            Caption = 'Point Number'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlPointNumber: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblPointNumberVal: TLabel
            Left = 67
            Top = 6
            Width = 10
            Height = 18
            Caption = '0'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
    end
    object pnlMid2: TPanel
      Left = 319
      Top = 1
      Width = 318
      Height = 174
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 1
      object Panel35: TPanel
        Left = 0
        Top = 0
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object pnl_Row1_M2: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label26: TLabel
            Left = 10
            Top = 9
            Width = 116
            Height = 18
            Caption = 'P1 LONG(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlP1Long: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblP1LongVal: TLabel
            Left = 63
            Top = 9
            Width = 86
            Height = 18
            Alignment = taRightJustify
            Caption = '000.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row2_M2: TPanel
        Left = 0
        Top = 35
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object Panel39: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label28: TLabel
            Left = 10
            Top = 9
            Width = 99
            Height = 18
            Caption = 'P1 LAT(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlP1Lat: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblP1LatVal: TLabel
            Left = 73
            Top = 9
            Width = 76
            Height = 18
            Alignment = taRightJustify
            Caption = '00.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row3_M2: TPanel
        Left = 0
        Top = 70
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object Panel42: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label30: TLabel
            Left = 6
            Top = 11
            Width = 116
            Height = 18
            Caption = 'P2 LONG(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlP2Long: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblP2LongVal: TLabel
            Left = 83
            Top = 9
            Width = 66
            Height = 18
            Alignment = taRightJustify
            Caption = '0.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row4_M2: TPanel
        Left = 0
        Top = 105
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object Panel45: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label32: TLabel
            Left = 10
            Top = 6
            Width = 99
            Height = 18
            Caption = 'P2 LAT(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlP2Lat: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblP2LatVal: TLabel
            Left = 83
            Top = 9
            Width = 66
            Height = 18
            Alignment = taRightJustify
            Caption = '0.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row5_M2: TPanel
        Left = 0
        Top = 140
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        object Panel48: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label34: TLabel
            Left = 10
            Top = 6
            Width = 116
            Height = 18
            Caption = 'P3 LONG(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlP3Long: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblP3LongVal: TLabel
            Left = 83
            Top = 9
            Width = 66
            Height = 18
            Alignment = taRightJustify
            Caption = '0.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
    end
    object pnlRight2: TPanel
      Left = 637
      Top = 1
      Width = 318
      Height = 174
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 2
      object pnl_Row1_R2: TPanel
        Left = 0
        Top = 0
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        object Panel52: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label36: TLabel
            Left = 10
            Top = 9
            Width = 99
            Height = 18
            Caption = 'P3 LAT(deg)'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlP3Lat: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblP3LatVal: TLabel
            Left = 83
            Top = 9
            Width = 66
            Height = 18
            Alignment = taRightJustify
            Caption = '0.00000'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row2_R2: TPanel
        Left = 0
        Top = 35
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        object Panel55: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label38: TLabel
            Left = 10
            Top = 9
            Width = 80
            Height = 18
            Caption = 'Sea State'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlSearchState: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblSearchStateVal: TLabel
            Left = 10
            Top = 9
            Width = 32
            Height = 18
            Caption = 'Low'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row3_R2: TPanel
        Left = 0
        Top = 70
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        object Panel58: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label41: TLabel
            Left = 6
            Top = 11
            Width = 113
            Height = 18
            Caption = 'Capture Mode'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnllCaptureMode: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblCaptureModeVal: TLabel
            Left = 10
            Top = 9
            Width = 26
            Height = 18
            Caption = 'Big'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object pnl_Row4_R2: TPanel
        Left = 0
        Top = 105
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 3
        object Panel61: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
          object Label43: TLabel
            Left = 10
            Top = 6
            Width = 111
            Height = 18
            Caption = 'Search Range'
            Font.Charset = ANSI_CHARSET
            Font.Color = clWindowText
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
        object pnlSearchRng: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
          object lblSearchRngVal: TLabel
            Left = 10
            Top = 8
            Width = 24
            Height = 18
            Caption = 'Far'
            Font.Charset = ANSI_CHARSET
            Font.Color = clLime
            Font.Height = -16
            Font.Name = 'Verdana'
            Font.Style = []
            ParentFont = False
          end
        end
      end
      object Panel9: TPanel
        Left = 0
        Top = 140
        Width = 318
        Height = 35
        Align = alTop
        BevelOuter = bvNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        ExplicitTop = 139
        object Panel12: TPanel
          Left = 0
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 0
        end
        object Panel16: TPanel
          Left = 160
          Top = 0
          Width = 160
          Height = 35
          Align = alLeft
          Alignment = taLeftJustify
          Color = clBlack
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clLime
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentBackground = False
          ParentFont = False
          TabOrder = 1
        end
      end
    end
  end
end
