object frmINSTest: TfrmINSTest
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'frmINSTest'
  ClientHeight = 850
  ClientWidth = 954
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Bevel2: TBevel
    Left = 27
    Top = 731
    Width = 880
    Height = 9
    Shape = bsBottomLine
  end
  object Label51: TLabel
    Left = 32
    Top = 756
    Width = 381
    Height = 18
    Caption = 'Tip: Press key <1>~<2> to input missile No.,'
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -16
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object Label53: TLabel
    Left = 32
    Top = 788
    Width = 293
    Height = 18
    Caption = 'key<Enter> confirm,key<Esc> exit.'
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -16
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object Label1: TLabel
    Left = 215
    Top = 150
    Width = 239
    Height = 23
    Caption = 'Please input missile No.:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object edtInputMissileNumINSTest: TEdit
    Left = 500
    Top = 146
    Width = 238
    Height = 31
    BevelInner = bvLowered
    BevelKind = bkSoft
    Color = 16732757
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    Text = '1'
  end
  object Panel1: TPanel
    Left = 226
    Top = 242
    Width = 185
    Height = 41
    BevelKind = bkSoft
    TabOrder = 1
    object Label9: TLabel
      Left = 10
      Top = 9
      Width = 47
      Height = 18
      Caption = 'M.No.'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlMissileNumb1: TPanel
    Left = 408
    Top = 242
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 2
    object lblMissileNumVal: TLabel
      Left = 75
      Top = 9
      Width = 10
      Height = 18
      Alignment = taCenter
      Caption = '0'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlMissileNumb2: TPanel
    Left = 567
    Top = 242
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 3
    object Label2: TLabel
      Left = 75
      Top = 9
      Width = 10
      Height = 18
      Alignment = taCenter
      Caption = '0'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object Panel2: TPanel
    Left = 226
    Top = 280
    Width = 185
    Height = 41
    BevelKind = bkSoft
    TabOrder = 4
    object Label3: TLabel
      Left = 10
      Top = 9
      Width = 106
      Height = 18
      Caption = 'S.LONG(deg)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlSLong1: TPanel
    Left = 408
    Top = 280
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 5
  end
  object pnlSLong2: TPanel
    Left = 567
    Top = 280
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 6
    object lblSLong2: TLabel
      Left = 55
      Top = 9
      Width = 86
      Height = 18
      Alignment = taRightJustify
      Caption = '000.00000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object Panel3: TPanel
    Left = 226
    Top = 318
    Width = 185
    Height = 41
    BevelKind = bkSoft
    TabOrder = 7
    object Label6: TLabel
      Left = 10
      Top = 9
      Width = 89
      Height = 18
      Caption = 'S.LAT(deg)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlSLat1: TPanel
    Left = 408
    Top = 319
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 8
  end
  object pnlSLat2: TPanel
    Left = 567
    Top = 318
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 9
    object lblSLat2: TLabel
      Left = 55
      Top = 10
      Width = 86
      Height = 18
      Alignment = taRightJustify
      Caption = '000.00000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object Panel4: TPanel
    Left = 226
    Top = 356
    Width = 185
    Height = 41
    BevelKind = bkSoft
    TabOrder = 10
    object Label10: TLabel
      Left = 10
      Top = 9
      Width = 109
      Height = 18
      Caption = 'M.LONG(deg)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlMLong1: TPanel
    Left = 408
    Top = 356
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 11
  end
  object pnlMLong2: TPanel
    Left = 567
    Top = 356
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 12
    object lblMLong2: TLabel
      Left = 55
      Top = 10
      Width = 86
      Height = 18
      Alignment = taRightJustify
      Caption = '000.00000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object Panel5: TPanel
    Left = 226
    Top = 394
    Width = 185
    Height = 41
    BevelKind = bkSoft
    TabOrder = 13
    object Label13: TLabel
      Left = 10
      Top = 9
      Width = 92
      Height = 18
      Caption = 'M.LAT(deg)'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlMLat1: TPanel
    Left = 408
    Top = 394
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 14
  end
  object pnlMLat2: TPanel
    Left = 567
    Top = 394
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 15
    object lblMLat2: TLabel
      Left = 55
      Top = 10
      Width = 86
      Height = 18
      Alignment = taRightJustify
      Caption = '000.00000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object Panel6: TPanel
    Left = 226
    Top = 432
    Width = 185
    Height = 41
    BevelKind = bkSoft
    TabOrder = 16
    object Label16: TLabel
      Left = 10
      Top = 9
      Width = 116
      Height = 18
      Caption = 'Northward Err.'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlNortwardErr1: TPanel
    Left = 408
    Top = 433
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 17
  end
  object pnlNortwardErr2: TPanel
    Left = 567
    Top = 432
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 18
    object lblNortwardErr2: TLabel
      Left = 75
      Top = 10
      Width = 66
      Height = 18
      Alignment = taRightJustify
      Caption = '0.00000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object Panel7: TPanel
    Left = 226
    Top = 470
    Width = 185
    Height = 41
    BevelKind = bkSoft
    TabOrder = 19
    object Label19: TLabel
      Left = 10
      Top = 9
      Width = 107
      Height = 18
      Caption = 'Eastward Err.'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlEastwardErr1: TPanel
    Left = 408
    Top = 470
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 20
  end
  object pnlEastwardErr2: TPanel
    Left = 567
    Top = 470
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 21
    object lblEastwardErr2: TLabel
      Left = 75
      Top = 10
      Width = 66
      Height = 18
      Alignment = taRightJustify
      Caption = '0.00000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object Panel8: TPanel
    Left = 226
    Top = 508
    Width = 185
    Height = 41
    BevelKind = bkSoft
    TabOrder = 22
    object Label22: TLabel
      Left = 10
      Top = 9
      Width = 98
      Height = 18
      Caption = 'Position Err.'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
  object pnlPositionErr1: TPanel
    Left = 408
    Top = 508
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 23
  end
  object pnlPositionErr2: TPanel
    Left = 567
    Top = 508
    Width = 160
    Height = 41
    Alignment = taLeftJustify
    BevelKind = bkSoft
    BevelOuter = bvNone
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 24
    object lblPositionErr2: TLabel
      Left = 75
      Top = 9
      Width = 66
      Height = 18
      Alignment = taRightJustify
      Caption = '0.00000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clLime
      Font.Height = -16
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
    end
  end
end
