[DBCONFIG]
DBSERVER=127.0.0.1
DBPROTO=mysql
DBNAME=ZGJOU3VGcw==
DBUSER=cm9vdA==
DBPASS=VDNzZXJ2ZXIh
;DBPASS=YWRtaW4=
DBPORT=3306

[CONFIG]
SERVER=192.168.0.231
SERVERPORT=2120
3DSERVER=192.168.0.231
3DSERVERPORT=7001
ControlSrv=127.0.0.1
ControlSrvPort=1234
waitingtime=5000
reruncounter=15

[Map]
Mapmode  = 0
MapID    = 2

[Camera]
Cameramode = 1

[OnOff]
mode = 0
scenarioID = 0

[SystemServer]
2DServerAdress = 192.168.0.231
2DServerPort = 7001
3DServerAdress = 192.168.0.231
3DServerPort = 7002
Project = NSSFS
