[image]
imgpath=..\data\images\

[DBCONFIG]
;DBSERVER=192.168.0.232
DBSERVER=127.0.0.1
DBPROTO=mysql
DBNAME=ZGJOU3VGcw==
DBUSER=cm9vdA==
DBPASS=VDNzZXJ2ZXIh
DBPORT=3306

[CONFIG]
SERVER=192.168.0.210
SERVERPORT=2120
3DSERVER=192.168.0.210
3DSERVERPORT=5001
