[image]
imgpath=..\data\NewPicture\

[DBCONFIG]
DBSERVER=192.168.0.66
DBPROTO=mysql
DBNAME=ZGJOU3VGcw==
DBUSER=cm9vdA==
DBPASS=YWRtaW4=
;DBPASS=VDNzZXJ2ZXIh
DBPORT=3306

[CONFIG]
SERVER=192.168.0.66
SERVERPORT=2120
3DSERVER=192.168.0.193
3DSERVERPORT=7001
ControlSrv=127.0.0.1
ControlSrvPort=1234
waitingtime=5000
reruncounter=15