[image]
imgpath=.\data\Bitmap\
[DBCONFIG]
DBSERVER=127.0.0.1
DBPROTO=mysql
DBNAME=ZGJOU3VGcw==
DBUSER=cm9vdA==
DBPASS=VDNzZXJ2ZXIh
DBPORT=3306
[CONFIG]
SERVER=192.168.0.231
SERVERPORT=2120
3DSERVER=192.168.0.231
3DSERVERPORT=7001
[MRSetting]
MRMode=1
;mrmode 1=mr35, 2=mr103, 3=mr302
