[image]
imgpath=.\data\Picture\
[DBCONFIG]
DBSERVER=127.0.0.1
DBPROTO=mysql
DBNAME=ZGJOU3VGcw==
DBUSER=cm9vdA==
;DBPASS=VDNzZXJ2ZXIh
DBPASS=YWRtaW4=
DBPORT=3306
[CONFIG]
SERVER=192.168.110.191
SERVERPORT=2120
3DSERVER=192.168.110.191
3DSERVERPORT=5001
[FccSetting]
consoleMode=1
[SutBlacksharkSetting]
consoleMode=1
