object frmMainInstruktur: TfrmMainInstruktur
  Left = 197
  Top = 185
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Firing System Instruktur'
  ClientHeight = 722
  ClientWidth = 1280
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  Menu = MainMenu1
  OldCreateOrder = False
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = 0
    Top = 0
    Width = 1280
    Height = 722
    Align = alClient
    TabOrder = 0
    DesignSize = (
      1280
      722)
    object pnlMainBottom: TPanel
      Left = 1
      Top = 73
      Width = 1278
      Height = 571
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 0
      object MainMap: TMap
        Left = 0
        Top = 0
        Width = 1278
        Height = 571
        ParentColor = False
        Align = alClient
        TabOrder = 0
        OnMouseUp = MainMapMouseUp
        OnMouseMove = MainMapMouseMove
        OnMouseDown = MainMapMouseDown
        OnClick = MainMapClick
        OnMapViewChanged = MainMapMapViewChanged
        OnDrawUserLayer = MainMapDrawUserLayer
        ControlData = {
          8A1A060016840000043B0000010000000F0000FF0D47656F44696374696F6E61
          727905456D70747900E8030000000000000000000002000E001E000000000000
          0000000000000000000000000000000000000000000600010000000000500001
          010000640000000001F4010000050000800C000000000000000000000000FFFF
          FF000100000000000000000000000000000000000000000000000352E30B918F
          CE119DE300AA004BB85101000000900184C0060005417269616C000352E30B91
          8FCE119DE300AA004BB8510100000090015C790C0005417269616C0000000000
          00000000000000000000000000000000000000000000000000000000000000FF
          FFFF000000000000000001370000000000FFFFFF000000000000000352E30B91
          8FCE119DE300AA004BB851010000009001DC7C010005417269616C000352E30B
          918FCE119DE300AA004BB851010200009001A42C02000B4D61702053796D626F
          6C730000000000000001000100FFFFFF000200FFFFFF00000000000001000000
          01000118010000904BA204010000006C90BD771C000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000002
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          8076C000000000008056C0000000000080764000000000008056400100000018
          010000904BA20401000000880300C01C00000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000200000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000E8E19700CD8A49761C
          00000000000000B08A4976A8FA132EFD780ACB28E29700000000000000000000
          000088B3400000000000408F400001000001}
      end
    end
    object pnlInfo: TAdvSmoothPanel
      Left = 1
      Top = 644
      Width = 1278
      Height = 77
      Cursor = crDefault
      Caption.Location = plTopCenter
      Caption.HatchStyle = HatchStyleDiagonalBrick
      Caption.HTMLFont.Charset = DEFAULT_CHARSET
      Caption.HTMLFont.Color = clWindowText
      Caption.HTMLFont.Height = -13
      Caption.HTMLFont.Name = 'Tahoma'
      Caption.HTMLFont.Style = []
      Caption.Font.Charset = DEFAULT_CHARSET
      Caption.Font.Color = clWindowText
      Caption.Font.Height = -16
      Caption.Font.Name = 'Tahoma'
      Caption.Font.Style = [fsBold]
      Caption.Top = 20
      Caption.ColorStart = clWhite
      Caption.ColorEnd = clWhite
      Caption.GradientType = gtHorizontal
      Caption.LineColor = clBlack
      Caption.Line = False
      Fill.Color = 7301478
      Fill.ColorTo = 10066329
      Fill.ColorMirror = 10066329
      Fill.ColorMirrorTo = 7301478
      Fill.GradientType = gtVertical
      Fill.GradientMirrorType = gtVertical
      Fill.BorderColor = clSilver
      Fill.BorderWidth = 5
      Fill.Rounding = 10
      Fill.ShadowColor = clNone
      Fill.ShadowOffset = 10
      Fill.Glow = gmNone
      Version = '1.6.0.1'
      Align = alBottom
      TabOrder = 1
      TMSStyle = 0
      object lbl1: TLabel
        Left = 8
        Top = 18
        Width = 84
        Height = 14
        Caption = 'Longitude'#9':'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lbl2: TLabel
        Left = 8
        Top = 34
        Width = 84
        Height = 14
        Caption = 'Latitude'#9':'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblLongitude: TLabel
        Left = 135
        Top = 18
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblLatitude: TLabel
        Left = 135
        Top = 34
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object bvl1: TBevel
        Left = 177
        Top = 16
        Width = 7
        Height = 34
        Shape = bsLeftLine
      end
      object lbl3: TLabel
        Left = 183
        Top = 18
        Width = 84
        Height = 14
        Caption = 'Georef'#9#9':'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lbl4: TLabel
        Left = 183
        Top = 34
        Width = 84
        Height = 14
        Caption = 'Zoom Level'#9':'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblZoomLvl: TLabel
        Left = 297
        Top = 34
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblGeoref: TLabel
        Left = 297
        Top = 18
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object bvl2: TBevel
        Left = 340
        Top = 16
        Width = 7
        Height = 34
        Shape = bsLeftLine
      end
      object lbl5: TLabel
        Left = 346
        Top = 34
        Width = 54
        Height = 14
        Caption = 'Distance :'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
        Visible = False
      end
      object lbl6: TLabel
        Left = 346
        Top = 17
        Width = 52
        Height = 14
        Caption = 'Tool      :'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblToolUsed: TLabel
        Left = 457
        Top = 17
        Width = 29
        Height = 14
        Alignment = taRightJustify
        Caption = 'None'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblMapUnit: TLabel
        Left = 457
        Top = 34
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
        Visible = False
      end
      object bvl3: TBevel
        Left = 498
        Top = 15
        Width = 7
        Height = 34
        Shape = bsLeftLine
      end
      object lbl7: TLabel
        Left = 504
        Top = 18
        Width = 44
        Height = 14
        Caption = 'Height'#9':'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lbl8: TLabel
        Left = 504
        Top = 34
        Width = 44
        Height = 14
        Caption = 'Depth'#9':'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblElevation: TLabel
        Left = 606
        Top = 18
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblDepth: TLabel
        Left = 606
        Top = 34
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object bvl4: TBevel
        Left = 649
        Top = 15
        Width = 7
        Height = 34
        Shape = bsLeftLine
      end
      object lbl9: TLabel
        Left = 657
        Top = 18
        Width = 15
        Height = 14
        Caption = 'X :'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lbl10: TLabel
        Left = 656
        Top = 34
        Width = 16
        Height = 14
        Caption = 'Y :'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblX: TLabel
        Left = 734
        Top = 18
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lblY: TLabel
        Left = 734
        Top = 34
        Width = 39
        Height = 14
        Alignment = taRightJustify
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object bvl5: TBevel
        Left = 776
        Top = 17
        Width = 10
        Height = 34
        Shape = bsLeftLine
      end
      object lbl11: TLabel
        Left = 780
        Top = 34
        Width = 44
        Height = 14
        Caption = '3D Y'#9':'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lbl12: TLabel
        Left = 780
        Top = 18
        Width = 44
        Height = 14
        Caption = '3D X'#9':'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lbl3DY: TLabel
        Left = 877
        Top = 34
        Width = 39
        Height = 14
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object lbl3DX: TLabel
        Left = 877
        Top = 19
        Width = 39
        Height = 14
        Caption = '000.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -12
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        Transparent = True
      end
      object btnShowtikas: TButton
        Left = 1121
        Top = 25
        Width = 75
        Height = 25
        Caption = 'Hide Tikas'
        TabOrder = 0
        Visible = False
        OnClick = btnShowtikasClick
      end
    end
    object pnlMainUp: TAdvSmoothPanel
      Left = 1
      Top = 1
      Width = 1278
      Height = 72
      Cursor = crDefault
      Caption.Location = plTopCenter
      Caption.HatchStyle = HatchStyleDiagonalBrick
      Caption.HTMLFont.Charset = DEFAULT_CHARSET
      Caption.HTMLFont.Color = clWindowText
      Caption.HTMLFont.Height = -13
      Caption.HTMLFont.Name = 'Tahoma'
      Caption.HTMLFont.Style = []
      Caption.Font.Charset = DEFAULT_CHARSET
      Caption.Font.Color = clWindowText
      Caption.Font.Height = -16
      Caption.Font.Name = 'Tahoma'
      Caption.Font.Style = [fsBold]
      Caption.Top = 20
      Caption.ColorStart = clWhite
      Caption.ColorEnd = clWhite
      Caption.GradientType = gtHorizontal
      Caption.LineColor = clBlack
      Caption.Line = False
      Fill.Color = 7301478
      Fill.ColorTo = 10066329
      Fill.ColorMirror = 10066329
      Fill.ColorMirrorTo = 7301478
      Fill.GradientType = gtVertical
      Fill.GradientMirrorType = gtVertical
      Fill.BorderColor = clSilver
      Fill.BorderWidth = 5
      Fill.Rounding = 10
      Fill.ShadowColor = clNone
      Fill.ShadowOffset = 10
      Fill.Glow = gmNone
      Version = '1.6.0.1'
      Align = alTop
      TabOrder = 2
      TMSStyle = 0
      object pnlMainMenu: TAdvSmoothPanel
        Left = 392
        Top = 0
        Width = 697
        Height = 72
        Cursor = crDefault
        Caption.Location = plTopCenter
        Caption.HatchStyle = HatchStyleDiagonalBrick
        Caption.HTMLFont.Charset = DEFAULT_CHARSET
        Caption.HTMLFont.Color = clWindowText
        Caption.HTMLFont.Height = -13
        Caption.HTMLFont.Name = 'Tahoma'
        Caption.HTMLFont.Style = []
        Caption.Font.Charset = DEFAULT_CHARSET
        Caption.Font.Color = clWindowText
        Caption.Font.Height = -16
        Caption.Font.Name = 'Tahoma'
        Caption.Font.Style = [fsBold]
        Caption.Top = 20
        Caption.ColorStart = clWhite
        Caption.ColorEnd = clWhite
        Caption.GradientType = gtHorizontal
        Caption.LineColor = clBlack
        Caption.Line = False
        Fill.Color = 7301478
        Fill.ColorTo = 10066329
        Fill.ColorMirror = 10066329
        Fill.ColorMirrorTo = 7301478
        Fill.GradientType = gtVertical
        Fill.GradientMirrorType = gtVertical
        Fill.BorderColor = clSilver
        Fill.BorderWidth = 5
        Fill.Rounding = 10
        Fill.ShadowColor = clNone
        Fill.ShadowOffset = 10
        Fill.Glow = gmNone
        Version = '1.6.0.1'
        TabOrder = 0
        TMSStyle = 0
        object btnZoomOut: TSpeedButtonImage
          Left = 332
          Top = 11
          Width = 50
          Height = 50
          Hint = 'ZoomOut'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnRecordStart: TSpeedButtonImage
          Left = 629
          Top = 11
          Width = 50
          Height = 50
          Hint = 'OffRecord'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnSelectArrow: TSpeedButtonImage
          Left = 87
          Top = 11
          Width = 50
          Height = 50
          Hint = 'Arrow'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnSelectMove: TSpeedButtonImage
          Left = 141
          Top = 11
          Width = 50
          Height = 50
          Hint = 'Move'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnSelectMoveAll: TSpeedButtonImage
          Left = 194
          Top = 11
          Width = 50
          Height = 50
          Hint = 'MultiMove'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnZoomIn: TSpeedButtonImage
          Left = 387
          Top = 11
          Width = 50
          Height = 50
          Hint = 'ZoomIn'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnZoomValue: TSpeedButtonImage
          Left = 441
          Top = 11
          Width = 50
          Height = 50
          Hint = 'ZoomScale'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnHand: TSpeedButtonImage
          Left = 18
          Top = 11
          Width = 50
          Height = 50
          Hint = 'Hand'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnRecordPause: TSpeedButtonImage
          Left = 647
          Top = 10
          Width = 50
          Height = 50
          Caption = ''
          Flat = True
          Visible = False
        end
        object btnToolRuler: TSpeedButtonImage
          Left = 520
          Top = 11
          Width = 50
          Height = 50
          Hint = 'Ruler'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnToolTikas: TSpeedButtonImage
          Left = 574
          Top = 11
          Width = 50
          Height = 50
          Hint = 'Hide History'
          Caption = ''
          Flat = True
          ParentShowHint = False
          ShowHint = True
        end
        object btnZoomCenter: TSpeedButtonImage
          Left = 278
          Top = 11
          Width = 50
          Height = 50
          Hint = 'Center'
          Caption = ''
          Flat = True
          Layout = blGlyphTop
          Margin = 0
          ParentShowHint = False
          ShowHint = True
          Spacing = 0
        end
      end
      object pnlStatus: TAdvSmoothPanel
        Left = 0
        Top = 0
        Width = 153
        Height = 72
        Cursor = crDefault
        Caption.Location = plTopCenter
        Caption.HatchStyle = HatchStyleDiagonalBrick
        Caption.HTMLFont.Charset = DEFAULT_CHARSET
        Caption.HTMLFont.Color = clWindowText
        Caption.HTMLFont.Height = -13
        Caption.HTMLFont.Name = 'Tahoma'
        Caption.HTMLFont.Style = []
        Caption.Font.Charset = DEFAULT_CHARSET
        Caption.Font.Color = clWindowText
        Caption.Font.Height = -16
        Caption.Font.Name = 'Tahoma'
        Caption.Font.Style = [fsBold]
        Caption.Top = 20
        Caption.ColorStart = clWhite
        Caption.ColorEnd = clWhite
        Caption.GradientType = gtHorizontal
        Caption.LineColor = clBlack
        Caption.Line = False
        Fill.Color = 7301478
        Fill.ColorTo = 10066329
        Fill.ColorMirror = 10066329
        Fill.ColorMirrorTo = 7301478
        Fill.GradientType = gtVertical
        Fill.GradientMirrorType = gtVertical
        Fill.BorderColor = clSilver
        Fill.BorderWidth = 5
        Fill.Rounding = 10
        Fill.ShadowColor = clNone
        Fill.ShadowOffset = 10
        Fill.Glow = gmNone
        Version = '1.6.0.1'
        Align = alLeft
        TabOrder = 1
        TMSStyle = 0
        object lblConnection: TAdvSmoothLabel
          Left = 28
          Top = 29
          Width = 92
          Height = 33
          Fill.ColorMirror = clNone
          Fill.ColorMirrorTo = clNone
          Fill.GradientType = gtVertical
          Fill.GradientMirrorType = gtSolid
          Fill.BorderColor = clNone
          Fill.Rounding = 0
          Fill.ShadowOffset = 0
          Fill.Glow = gmNone
          Caption.Text = 'Closed'
          Caption.Font.Charset = DEFAULT_CHARSET
          Caption.Font.Color = clWindowText
          Caption.Font.Height = -13
          Caption.Font.Name = 'Tahoma'
          Caption.Font.Style = [fsBold]
          Caption.ColorStart = clSilver
          Caption.ColorEnd = clWhite
          CaptionShadow.Text = 'AdvSmoothLabel'
          CaptionShadow.Font.Charset = DEFAULT_CHARSET
          CaptionShadow.Font.Color = clWindowText
          CaptionShadow.Font.Height = -27
          CaptionShadow.Font.Name = 'Tahoma'
          CaptionShadow.Font.Style = []
          Version = '1.6.1.0'
        end
        object advsmthlbl1: TAdvSmoothLabel
          Left = 28
          Top = 13
          Width = 97
          Height = 33
          Fill.ColorMirror = clNone
          Fill.ColorMirrorTo = clNone
          Fill.GradientType = gtVertical
          Fill.GradientMirrorType = gtSolid
          Fill.BorderColor = clNone
          Fill.Rounding = 0
          Fill.ShadowOffset = 0
          Fill.Glow = gmNone
          Caption.Text = 'Connection '
          Caption.Font.Charset = DEFAULT_CHARSET
          Caption.Font.Color = clWindowText
          Caption.Font.Height = -13
          Caption.Font.Name = 'Tahoma'
          Caption.Font.Style = [fsBold]
          Caption.ColorStart = clSilver
          Caption.ColorEnd = clWhite
          CaptionShadow.Text = 'AdvSmoothLabel'
          CaptionShadow.Font.Charset = DEFAULT_CHARSET
          CaptionShadow.Font.Color = clWindowText
          CaptionShadow.Font.Height = -27
          CaptionShadow.Font.Name = 'Tahoma'
          CaptionShadow.Font.Style = []
          Version = '1.6.1.0'
        end
        object lblConnection2: TAdvSmoothLabel
          Left = -15
          Top = -3
          Width = 92
          Height = 33
          Fill.ColorMirror = clNone
          Fill.ColorMirrorTo = clNone
          Fill.GradientType = gtVertical
          Fill.GradientMirrorType = gtSolid
          Fill.BorderColor = clNone
          Fill.Rounding = 0
          Fill.ShadowOffset = 0
          Fill.Glow = gmNone
          Caption.Text = 'Closed'
          Caption.Font.Charset = DEFAULT_CHARSET
          Caption.Font.Color = clWindowText
          Caption.Font.Height = -13
          Caption.Font.Name = 'Tahoma'
          Caption.Font.Style = [fsBold]
          Caption.ColorStart = clSilver
          Caption.ColorEnd = clWhite
          CaptionShadow.Text = 'AdvSmoothLabel'
          CaptionShadow.Font.Charset = DEFAULT_CHARSET
          CaptionShadow.Font.Color = clWindowText
          CaptionShadow.Font.Height = -27
          CaptionShadow.Font.Name = 'Tahoma'
          CaptionShadow.Font.Style = []
          Version = '1.6.1.0'
          Visible = False
        end
        object advsmthlbl3: TAdvSmoothLabel
          Left = 5
          Top = -3
          Width = 52
          Height = 33
          Fill.ColorMirror = clNone
          Fill.ColorMirrorTo = clNone
          Fill.GradientType = gtVertical
          Fill.GradientMirrorType = gtSolid
          Fill.BorderColor = clNone
          Fill.Rounding = 0
          Fill.ShadowOffset = 0
          Fill.Glow = gmNone
          Caption.Text = '2D Srv'
          Caption.Font.Charset = DEFAULT_CHARSET
          Caption.Font.Color = clWindowText
          Caption.Font.Height = -13
          Caption.Font.Name = 'Tahoma'
          Caption.Font.Style = [fsBold]
          Caption.ColorStart = clSilver
          Caption.ColorEnd = clWhite
          CaptionShadow.Text = 'AdvSmoothLabel'
          CaptionShadow.Font.Charset = DEFAULT_CHARSET
          CaptionShadow.Font.Color = clWindowText
          CaptionShadow.Font.Height = -27
          CaptionShadow.Font.Name = 'Tahoma'
          CaptionShadow.Font.Style = []
          Version = '1.6.1.0'
          Visible = False
        end
        object advsmthlbl4: TAdvSmoothLabel
          Left = 5
          Top = -4
          Width = 52
          Height = 33
          Fill.ColorMirror = clNone
          Fill.ColorMirrorTo = clNone
          Fill.GradientType = gtVertical
          Fill.GradientMirrorType = gtSolid
          Fill.BorderColor = clNone
          Fill.Rounding = 0
          Fill.ShadowOffset = 0
          Fill.Glow = gmNone
          Caption.Text = 'Ct Srv'
          Caption.Font.Charset = DEFAULT_CHARSET
          Caption.Font.Color = clWindowText
          Caption.Font.Height = -13
          Caption.Font.Name = 'Tahoma'
          Caption.Font.Style = [fsBold]
          Caption.ColorStart = clSilver
          Caption.ColorEnd = clWhite
          CaptionShadow.Text = 'AdvSmoothLabel'
          CaptionShadow.Font.Charset = DEFAULT_CHARSET
          CaptionShadow.Font.Color = clWindowText
          CaptionShadow.Font.Height = -27
          CaptionShadow.Font.Name = 'Tahoma'
          CaptionShadow.Font.Style = []
          Version = '1.6.1.0'
          Visible = False
        end
        object AdvSmoothPanel1: TAdvSmoothPanel
          Left = 0
          Top = 0
          Width = 153
          Height = 72
          Cursor = crDefault
          Caption.Location = plTopCenter
          Caption.HatchStyle = HatchStyleDiagonalBrick
          Caption.HTMLFont.Charset = DEFAULT_CHARSET
          Caption.HTMLFont.Color = clWindowText
          Caption.HTMLFont.Height = -13
          Caption.HTMLFont.Name = 'Tahoma'
          Caption.HTMLFont.Style = []
          Caption.Font.Charset = DEFAULT_CHARSET
          Caption.Font.Color = clWindowText
          Caption.Font.Height = -16
          Caption.Font.Name = 'Tahoma'
          Caption.Font.Style = [fsBold]
          Caption.Top = 20
          Caption.ColorStart = clWhite
          Caption.ColorEnd = clWhite
          Caption.GradientType = gtHorizontal
          Caption.LineColor = clBlack
          Caption.Line = False
          Fill.Color = 7301478
          Fill.ColorTo = 10066329
          Fill.ColorMirror = 10066329
          Fill.ColorMirrorTo = 7301478
          Fill.GradientType = gtVertical
          Fill.GradientMirrorType = gtVertical
          Fill.BorderColor = clSilver
          Fill.BorderWidth = 5
          Fill.Rounding = 10
          Fill.ShadowColor = clNone
          Fill.ShadowOffset = 10
          Fill.Glow = gmNone
          Version = '1.6.0.1'
          Align = alLeft
          TabOrder = 0
          TMSStyle = 0
          object AdvSmoothLabel1: TAdvSmoothLabel
            Left = 28
            Top = 29
            Width = 92
            Height = 33
            Fill.ColorMirror = clNone
            Fill.ColorMirrorTo = clNone
            Fill.GradientType = gtVertical
            Fill.GradientMirrorType = gtSolid
            Fill.BorderColor = clNone
            Fill.Rounding = 0
            Fill.ShadowOffset = 0
            Fill.Glow = gmNone
            Caption.Text = 'Closed'
            Caption.Font.Charset = DEFAULT_CHARSET
            Caption.Font.Color = clWindowText
            Caption.Font.Height = -13
            Caption.Font.Name = 'Tahoma'
            Caption.Font.Style = [fsBold]
            Caption.ColorStart = clSilver
            Caption.ColorEnd = clWhite
            CaptionShadow.Text = 'AdvSmoothLabel'
            CaptionShadow.Font.Charset = DEFAULT_CHARSET
            CaptionShadow.Font.Color = clWindowText
            CaptionShadow.Font.Height = -27
            CaptionShadow.Font.Name = 'Tahoma'
            CaptionShadow.Font.Style = []
            Version = '1.6.1.0'
          end
          object AdvSmoothLabel2: TAdvSmoothLabel
            Left = 28
            Top = 13
            Width = 97
            Height = 33
            Fill.ColorMirror = clNone
            Fill.ColorMirrorTo = clNone
            Fill.GradientType = gtVertical
            Fill.GradientMirrorType = gtSolid
            Fill.BorderColor = clNone
            Fill.Rounding = 0
            Fill.ShadowOffset = 0
            Fill.Glow = gmNone
            Caption.Text = 'Connection '
            Caption.Font.Charset = DEFAULT_CHARSET
            Caption.Font.Color = clWindowText
            Caption.Font.Height = -13
            Caption.Font.Name = 'Tahoma'
            Caption.Font.Style = [fsBold]
            Caption.ColorStart = clSilver
            Caption.ColorEnd = clWhite
            CaptionShadow.Text = 'AdvSmoothLabel'
            CaptionShadow.Font.Charset = DEFAULT_CHARSET
            CaptionShadow.Font.Color = clWindowText
            CaptionShadow.Font.Height = -27
            CaptionShadow.Font.Name = 'Tahoma'
            CaptionShadow.Font.Style = []
            Version = '1.6.1.0'
          end
          object AdvSmoothLabel3: TAdvSmoothLabel
            Left = -15
            Top = -3
            Width = 92
            Height = 33
            Fill.ColorMirror = clNone
            Fill.ColorMirrorTo = clNone
            Fill.GradientType = gtVertical
            Fill.GradientMirrorType = gtSolid
            Fill.BorderColor = clNone
            Fill.Rounding = 0
            Fill.ShadowOffset = 0
            Fill.Glow = gmNone
            Caption.Text = 'Closed'
            Caption.Font.Charset = DEFAULT_CHARSET
            Caption.Font.Color = clWindowText
            Caption.Font.Height = -13
            Caption.Font.Name = 'Tahoma'
            Caption.Font.Style = [fsBold]
            Caption.ColorStart = clSilver
            Caption.ColorEnd = clWhite
            CaptionShadow.Text = 'AdvSmoothLabel'
            CaptionShadow.Font.Charset = DEFAULT_CHARSET
            CaptionShadow.Font.Color = clWindowText
            CaptionShadow.Font.Height = -27
            CaptionShadow.Font.Name = 'Tahoma'
            CaptionShadow.Font.Style = []
            Version = '1.6.1.0'
            Visible = False
          end
          object AdvSmoothLabel4: TAdvSmoothLabel
            Left = 5
            Top = -3
            Width = 52
            Height = 33
            Fill.ColorMirror = clNone
            Fill.ColorMirrorTo = clNone
            Fill.GradientType = gtVertical
            Fill.GradientMirrorType = gtSolid
            Fill.BorderColor = clNone
            Fill.Rounding = 0
            Fill.ShadowOffset = 0
            Fill.Glow = gmNone
            Caption.Text = '2D Srv'
            Caption.Font.Charset = DEFAULT_CHARSET
            Caption.Font.Color = clWindowText
            Caption.Font.Height = -13
            Caption.Font.Name = 'Tahoma'
            Caption.Font.Style = [fsBold]
            Caption.ColorStart = clSilver
            Caption.ColorEnd = clWhite
            CaptionShadow.Text = 'AdvSmoothLabel'
            CaptionShadow.Font.Charset = DEFAULT_CHARSET
            CaptionShadow.Font.Color = clWindowText
            CaptionShadow.Font.Height = -27
            CaptionShadow.Font.Name = 'Tahoma'
            CaptionShadow.Font.Style = []
            Version = '1.6.1.0'
            Visible = False
          end
          object AdvSmoothLabel5: TAdvSmoothLabel
            Left = 5
            Top = -4
            Width = 52
            Height = 33
            Fill.ColorMirror = clNone
            Fill.ColorMirrorTo = clNone
            Fill.GradientType = gtVertical
            Fill.GradientMirrorType = gtSolid
            Fill.BorderColor = clNone
            Fill.Rounding = 0
            Fill.ShadowOffset = 0
            Fill.Glow = gmNone
            Caption.Text = 'Ct Srv'
            Caption.Font.Charset = DEFAULT_CHARSET
            Caption.Font.Color = clWindowText
            Caption.Font.Height = -13
            Caption.Font.Name = 'Tahoma'
            Caption.Font.Style = [fsBold]
            Caption.ColorStart = clSilver
            Caption.ColorEnd = clWhite
            CaptionShadow.Text = 'AdvSmoothLabel'
            CaptionShadow.Font.Charset = DEFAULT_CHARSET
            CaptionShadow.Font.Color = clWindowText
            CaptionShadow.Font.Height = -27
            CaptionShadow.Font.Name = 'Tahoma'
            CaptionShadow.Font.Style = []
            Version = '1.6.1.0'
            Visible = False
          end
          object AdvSmoothPanel2: TAdvSmoothPanel
            Left = 153
            Top = 0
            Width = 153
            Height = 72
            Cursor = crDefault
            Caption.Location = plTopCenter
            Caption.HatchStyle = HatchStyleDiagonalBrick
            Caption.HTMLFont.Charset = DEFAULT_CHARSET
            Caption.HTMLFont.Color = clWindowText
            Caption.HTMLFont.Height = -13
            Caption.HTMLFont.Name = 'Tahoma'
            Caption.HTMLFont.Style = []
            Caption.Font.Charset = DEFAULT_CHARSET
            Caption.Font.Color = clWindowText
            Caption.Font.Height = -16
            Caption.Font.Name = 'Tahoma'
            Caption.Font.Style = [fsBold]
            Caption.Top = 20
            Caption.ColorStart = clWhite
            Caption.ColorEnd = clWhite
            Caption.GradientType = gtHorizontal
            Caption.LineColor = clBlack
            Caption.Line = False
            Fill.Color = 7301478
            Fill.ColorTo = 10066329
            Fill.ColorMirror = 10066329
            Fill.ColorMirrorTo = 7301478
            Fill.GradientType = gtVertical
            Fill.GradientMirrorType = gtVertical
            Fill.BorderColor = clSilver
            Fill.BorderWidth = 5
            Fill.Rounding = 10
            Fill.ShadowColor = clNone
            Fill.ShadowOffset = 10
            Fill.Glow = gmNone
            Version = '1.6.0.1'
            Align = alLeft
            TabOrder = 0
            TMSStyle = 0
            object AdvSmoothLabel6: TAdvSmoothLabel
              Left = 28
              Top = 29
              Width = 92
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = 'Closed'
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
            end
            object AdvSmoothLabel7: TAdvSmoothLabel
              Left = 28
              Top = 13
              Width = 97
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = 'Connection '
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
            end
            object AdvSmoothLabel8: TAdvSmoothLabel
              Left = -15
              Top = -3
              Width = 92
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = 'Closed'
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
              Visible = False
            end
            object AdvSmoothLabel9: TAdvSmoothLabel
              Left = 5
              Top = -3
              Width = 52
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = '2D Srv'
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
              Visible = False
            end
            object AdvSmoothLabel10: TAdvSmoothLabel
              Left = 5
              Top = -4
              Width = 52
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = 'Ct Srv'
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
              Visible = False
            end
            object AdvSmoothPanel3: TAdvSmoothPanel
              Left = 0
              Top = 0
              Width = 153
              Height = 72
              Cursor = crDefault
              Caption.Location = plTopCenter
              Caption.HatchStyle = HatchStyleDiagonalBrick
              Caption.HTMLFont.Charset = DEFAULT_CHARSET
              Caption.HTMLFont.Color = clWindowText
              Caption.HTMLFont.Height = -13
              Caption.HTMLFont.Name = 'Tahoma'
              Caption.HTMLFont.Style = []
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -16
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.Top = 20
              Caption.ColorStart = clWhite
              Caption.ColorEnd = clWhite
              Caption.GradientType = gtHorizontal
              Caption.LineColor = clBlack
              Caption.Line = False
              Fill.Color = 7301478
              Fill.ColorTo = 10066329
              Fill.ColorMirror = 10066329
              Fill.ColorMirrorTo = 7301478
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtVertical
              Fill.BorderColor = clSilver
              Fill.BorderWidth = 5
              Fill.Rounding = 10
              Fill.ShadowColor = clNone
              Fill.ShadowOffset = 10
              Fill.Glow = gmNone
              Version = '1.6.0.1'
              Align = alLeft
              TabOrder = 0
              TMSStyle = 0
              object AdvSmoothLabel11: TAdvSmoothLabel
                Left = 28
                Top = 29
                Width = 92
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = 'Closed'
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
              end
              object AdvSmoothLabel12: TAdvSmoothLabel
                Left = 28
                Top = 13
                Width = 97
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = 'Connection '
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
              end
              object AdvSmoothLabel13: TAdvSmoothLabel
                Left = -15
                Top = -3
                Width = 92
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = 'Closed'
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
                Visible = False
              end
              object AdvSmoothLabel14: TAdvSmoothLabel
                Left = 5
                Top = -3
                Width = 52
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = '2D Srv'
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
                Visible = False
              end
              object AdvSmoothLabel15: TAdvSmoothLabel
                Left = 5
                Top = -4
                Width = 52
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = 'Ct Srv'
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
                Visible = False
              end
            end
          end
          object AdvSmoothPanel4: TAdvSmoothPanel
            Left = 0
            Top = 0
            Width = 153
            Height = 72
            Cursor = crDefault
            Caption.Location = plTopCenter
            Caption.HatchStyle = HatchStyleDiagonalBrick
            Caption.HTMLFont.Charset = DEFAULT_CHARSET
            Caption.HTMLFont.Color = clWindowText
            Caption.HTMLFont.Height = -13
            Caption.HTMLFont.Name = 'Tahoma'
            Caption.HTMLFont.Style = []
            Caption.Font.Charset = DEFAULT_CHARSET
            Caption.Font.Color = clWindowText
            Caption.Font.Height = -16
            Caption.Font.Name = 'Tahoma'
            Caption.Font.Style = [fsBold]
            Caption.Top = 20
            Caption.ColorStart = clWhite
            Caption.ColorEnd = clWhite
            Caption.GradientType = gtHorizontal
            Caption.LineColor = clBlack
            Caption.Line = False
            Fill.Color = 7301478
            Fill.ColorTo = 10066329
            Fill.ColorMirror = 10066329
            Fill.ColorMirrorTo = 7301478
            Fill.GradientType = gtVertical
            Fill.GradientMirrorType = gtVertical
            Fill.BorderColor = clSilver
            Fill.BorderWidth = 5
            Fill.Rounding = 10
            Fill.ShadowColor = clNone
            Fill.ShadowOffset = 10
            Fill.Glow = gmNone
            Version = '1.6.0.1'
            Align = alLeft
            TabOrder = 1
            TMSStyle = 0
            object AdvSmoothLabel16: TAdvSmoothLabel
              Left = 28
              Top = 29
              Width = 92
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = 'Closed'
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
            end
            object AdvSmoothLabel17: TAdvSmoothLabel
              Left = 28
              Top = 13
              Width = 97
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = 'Connection '
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
            end
            object AdvSmoothLabel18: TAdvSmoothLabel
              Left = -15
              Top = -3
              Width = 92
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = 'Closed'
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
              Visible = False
            end
            object AdvSmoothLabel19: TAdvSmoothLabel
              Left = 5
              Top = -3
              Width = 52
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = '2D Srv'
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
              Visible = False
            end
            object AdvSmoothLabel20: TAdvSmoothLabel
              Left = 5
              Top = -4
              Width = 52
              Height = 33
              Fill.ColorMirror = clNone
              Fill.ColorMirrorTo = clNone
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtSolid
              Fill.BorderColor = clNone
              Fill.Rounding = 0
              Fill.ShadowOffset = 0
              Fill.Glow = gmNone
              Caption.Text = 'Ct Srv'
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -13
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.ColorStart = clSilver
              Caption.ColorEnd = clWhite
              CaptionShadow.Text = 'AdvSmoothLabel'
              CaptionShadow.Font.Charset = DEFAULT_CHARSET
              CaptionShadow.Font.Color = clWindowText
              CaptionShadow.Font.Height = -27
              CaptionShadow.Font.Name = 'Tahoma'
              CaptionShadow.Font.Style = []
              Version = '1.6.1.0'
              Visible = False
            end
            object AdvSmoothPanel5: TAdvSmoothPanel
              Left = 0
              Top = 0
              Width = 153
              Height = 72
              Cursor = crDefault
              Caption.Location = plTopCenter
              Caption.HatchStyle = HatchStyleDiagonalBrick
              Caption.HTMLFont.Charset = DEFAULT_CHARSET
              Caption.HTMLFont.Color = clWindowText
              Caption.HTMLFont.Height = -13
              Caption.HTMLFont.Name = 'Tahoma'
              Caption.HTMLFont.Style = []
              Caption.Font.Charset = DEFAULT_CHARSET
              Caption.Font.Color = clWindowText
              Caption.Font.Height = -16
              Caption.Font.Name = 'Tahoma'
              Caption.Font.Style = [fsBold]
              Caption.Top = 20
              Caption.ColorStart = clWhite
              Caption.ColorEnd = clWhite
              Caption.GradientType = gtHorizontal
              Caption.LineColor = clBlack
              Caption.Line = False
              Fill.Color = 7301478
              Fill.ColorTo = 10066329
              Fill.ColorMirror = 10066329
              Fill.ColorMirrorTo = 7301478
              Fill.GradientType = gtVertical
              Fill.GradientMirrorType = gtVertical
              Fill.BorderColor = clSilver
              Fill.BorderWidth = 5
              Fill.Rounding = 10
              Fill.ShadowColor = clNone
              Fill.ShadowOffset = 10
              Fill.Glow = gmNone
              Version = '1.6.0.1'
              Align = alLeft
              TabOrder = 0
              TMSStyle = 0
              object AdvSmoothLabel21: TAdvSmoothLabel
                Left = 28
                Top = 29
                Width = 92
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = 'Closed'
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
              end
              object AdvSmoothLabel22: TAdvSmoothLabel
                Left = 28
                Top = 13
                Width = 97
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = 'Connection '
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
              end
              object AdvSmoothLabel23: TAdvSmoothLabel
                Left = -15
                Top = -3
                Width = 92
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = 'Closed'
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
                Visible = False
              end
              object AdvSmoothLabel24: TAdvSmoothLabel
                Left = 5
                Top = -3
                Width = 52
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = '2D Srv'
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
                Visible = False
              end
              object AdvSmoothLabel25: TAdvSmoothLabel
                Left = 5
                Top = -4
                Width = 52
                Height = 33
                Fill.ColorMirror = clNone
                Fill.ColorMirrorTo = clNone
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtSolid
                Fill.BorderColor = clNone
                Fill.Rounding = 0
                Fill.ShadowOffset = 0
                Fill.Glow = gmNone
                Caption.Text = 'Ct Srv'
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -13
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.ColorStart = clSilver
                Caption.ColorEnd = clWhite
                CaptionShadow.Text = 'AdvSmoothLabel'
                CaptionShadow.Font.Charset = DEFAULT_CHARSET
                CaptionShadow.Font.Color = clWindowText
                CaptionShadow.Font.Height = -27
                CaptionShadow.Font.Name = 'Tahoma'
                CaptionShadow.Font.Style = []
                Version = '1.6.1.0'
                Visible = False
              end
              object AdvSmoothPanel6: TAdvSmoothPanel
                Left = 0
                Top = 0
                Width = 153
                Height = 72
                Cursor = crDefault
                Caption.Location = plTopCenter
                Caption.HatchStyle = HatchStyleDiagonalBrick
                Caption.HTMLFont.Charset = DEFAULT_CHARSET
                Caption.HTMLFont.Color = clWindowText
                Caption.HTMLFont.Height = -13
                Caption.HTMLFont.Name = 'Tahoma'
                Caption.HTMLFont.Style = []
                Caption.Font.Charset = DEFAULT_CHARSET
                Caption.Font.Color = clWindowText
                Caption.Font.Height = -16
                Caption.Font.Name = 'Tahoma'
                Caption.Font.Style = [fsBold]
                Caption.Top = 20
                Caption.ColorStart = clWhite
                Caption.ColorEnd = clWhite
                Caption.GradientType = gtHorizontal
                Caption.LineColor = clBlack
                Caption.Line = False
                Fill.Color = 7301478
                Fill.ColorTo = 10066329
                Fill.ColorMirror = 10066329
                Fill.ColorMirrorTo = 7301478
                Fill.GradientType = gtVertical
                Fill.GradientMirrorType = gtVertical
                Fill.BorderColor = clSilver
                Fill.BorderWidth = 5
                Fill.Rounding = 10
                Fill.ShadowColor = clNone
                Fill.ShadowOffset = 10
                Fill.Glow = gmNone
                Version = '1.6.0.1'
                Align = alLeft
                TabOrder = 0
                TMSStyle = 0
                object AdvSmoothLabel26: TAdvSmoothLabel
                  Left = 28
                  Top = 29
                  Width = 92
                  Height = 33
                  Fill.ColorMirror = clNone
                  Fill.ColorMirrorTo = clNone
                  Fill.GradientType = gtVertical
                  Fill.GradientMirrorType = gtSolid
                  Fill.BorderColor = clNone
                  Fill.Rounding = 0
                  Fill.ShadowOffset = 0
                  Fill.Glow = gmNone
                  Caption.Text = 'Closed'
                  Caption.Font.Charset = DEFAULT_CHARSET
                  Caption.Font.Color = clWindowText
                  Caption.Font.Height = -13
                  Caption.Font.Name = 'Tahoma'
                  Caption.Font.Style = [fsBold]
                  Caption.ColorStart = clSilver
                  Caption.ColorEnd = clWhite
                  CaptionShadow.Text = 'AdvSmoothLabel'
                  CaptionShadow.Font.Charset = DEFAULT_CHARSET
                  CaptionShadow.Font.Color = clWindowText
                  CaptionShadow.Font.Height = -27
                  CaptionShadow.Font.Name = 'Tahoma'
                  CaptionShadow.Font.Style = []
                  Version = '1.6.1.0'
                end
                object AdvSmoothLabel27: TAdvSmoothLabel
                  Left = 28
                  Top = 13
                  Width = 97
                  Height = 33
                  Fill.ColorMirror = clNone
                  Fill.ColorMirrorTo = clNone
                  Fill.GradientType = gtVertical
                  Fill.GradientMirrorType = gtSolid
                  Fill.BorderColor = clNone
                  Fill.Rounding = 0
                  Fill.ShadowOffset = 0
                  Fill.Glow = gmNone
                  Caption.Text = 'Connection '
                  Caption.Font.Charset = DEFAULT_CHARSET
                  Caption.Font.Color = clWindowText
                  Caption.Font.Height = -13
                  Caption.Font.Name = 'Tahoma'
                  Caption.Font.Style = [fsBold]
                  Caption.ColorStart = clSilver
                  Caption.ColorEnd = clWhite
                  CaptionShadow.Text = 'AdvSmoothLabel'
                  CaptionShadow.Font.Charset = DEFAULT_CHARSET
                  CaptionShadow.Font.Color = clWindowText
                  CaptionShadow.Font.Height = -27
                  CaptionShadow.Font.Name = 'Tahoma'
                  CaptionShadow.Font.Style = []
                  Version = '1.6.1.0'
                end
                object AdvSmoothLabel28: TAdvSmoothLabel
                  Left = -15
                  Top = -3
                  Width = 92
                  Height = 33
                  Fill.ColorMirror = clNone
                  Fill.ColorMirrorTo = clNone
                  Fill.GradientType = gtVertical
                  Fill.GradientMirrorType = gtSolid
                  Fill.BorderColor = clNone
                  Fill.Rounding = 0
                  Fill.ShadowOffset = 0
                  Fill.Glow = gmNone
                  Caption.Text = 'Closed'
                  Caption.Font.Charset = DEFAULT_CHARSET
                  Caption.Font.Color = clWindowText
                  Caption.Font.Height = -13
                  Caption.Font.Name = 'Tahoma'
                  Caption.Font.Style = [fsBold]
                  Caption.ColorStart = clSilver
                  Caption.ColorEnd = clWhite
                  CaptionShadow.Text = 'AdvSmoothLabel'
                  CaptionShadow.Font.Charset = DEFAULT_CHARSET
                  CaptionShadow.Font.Color = clWindowText
                  CaptionShadow.Font.Height = -27
                  CaptionShadow.Font.Name = 'Tahoma'
                  CaptionShadow.Font.Style = []
                  Version = '1.6.1.0'
                  Visible = False
                end
                object AdvSmoothLabel29: TAdvSmoothLabel
                  Left = 5
                  Top = -3
                  Width = 52
                  Height = 33
                  Fill.ColorMirror = clNone
                  Fill.ColorMirrorTo = clNone
                  Fill.GradientType = gtVertical
                  Fill.GradientMirrorType = gtSolid
                  Fill.BorderColor = clNone
                  Fill.Rounding = 0
                  Fill.ShadowOffset = 0
                  Fill.Glow = gmNone
                  Caption.Text = '2D Srv'
                  Caption.Font.Charset = DEFAULT_CHARSET
                  Caption.Font.Color = clWindowText
                  Caption.Font.Height = -13
                  Caption.Font.Name = 'Tahoma'
                  Caption.Font.Style = [fsBold]
                  Caption.ColorStart = clSilver
                  Caption.ColorEnd = clWhite
                  CaptionShadow.Text = 'AdvSmoothLabel'
                  CaptionShadow.Font.Charset = DEFAULT_CHARSET
                  CaptionShadow.Font.Color = clWindowText
                  CaptionShadow.Font.Height = -27
                  CaptionShadow.Font.Name = 'Tahoma'
                  CaptionShadow.Font.Style = []
                  Version = '1.6.1.0'
                  Visible = False
                end
                object AdvSmoothLabel30: TAdvSmoothLabel
                  Left = 5
                  Top = -4
                  Width = 52
                  Height = 33
                  Fill.ColorMirror = clNone
                  Fill.ColorMirrorTo = clNone
                  Fill.GradientType = gtVertical
                  Fill.GradientMirrorType = gtSolid
                  Fill.BorderColor = clNone
                  Fill.Rounding = 0
                  Fill.ShadowOffset = 0
                  Fill.Glow = gmNone
                  Caption.Text = 'Ct Srv'
                  Caption.Font.Charset = DEFAULT_CHARSET
                  Caption.Font.Color = clWindowText
                  Caption.Font.Height = -13
                  Caption.Font.Name = 'Tahoma'
                  Caption.Font.Style = [fsBold]
                  Caption.ColorStart = clSilver
                  Caption.ColorEnd = clWhite
                  CaptionShadow.Text = 'AdvSmoothLabel'
                  CaptionShadow.Font.Charset = DEFAULT_CHARSET
                  CaptionShadow.Font.Color = clWindowText
                  CaptionShadow.Font.Height = -27
                  CaptionShadow.Font.Name = 'Tahoma'
                  CaptionShadow.Font.Style = []
                  Version = '1.6.1.0'
                  Visible = False
                end
                object AdvSmoothPanel7: TAdvSmoothPanel
                  Left = 0
                  Top = 0
                  Width = 153
                  Height = 72
                  Cursor = crDefault
                  Caption.Location = plTopCenter
                  Caption.HatchStyle = HatchStyleDiagonalBrick
                  Caption.HTMLFont.Charset = DEFAULT_CHARSET
                  Caption.HTMLFont.Color = clWindowText
                  Caption.HTMLFont.Height = -13
                  Caption.HTMLFont.Name = 'Tahoma'
                  Caption.HTMLFont.Style = []
                  Caption.Font.Charset = DEFAULT_CHARSET
                  Caption.Font.Color = clWindowText
                  Caption.Font.Height = -16
                  Caption.Font.Name = 'Tahoma'
                  Caption.Font.Style = [fsBold]
                  Caption.Top = 20
                  Caption.ColorStart = clWhite
                  Caption.ColorEnd = clWhite
                  Caption.GradientType = gtHorizontal
                  Caption.LineColor = clBlack
                  Caption.Line = False
                  Fill.Color = 7301478
                  Fill.ColorTo = 10066329
                  Fill.ColorMirror = 10066329
                  Fill.ColorMirrorTo = 7301478
                  Fill.GradientType = gtVertical
                  Fill.GradientMirrorType = gtVertical
                  Fill.BorderColor = clSilver
                  Fill.BorderWidth = 5
                  Fill.Rounding = 10
                  Fill.ShadowColor = clNone
                  Fill.ShadowOffset = 10
                  Fill.Glow = gmNone
                  Version = '1.6.0.1'
                  Align = alLeft
                  TabOrder = 0
                  TMSStyle = 0
                  object lblConnect: TAdvSmoothLabel
                    Left = 22
                    Top = 31
                    Width = 102
                    Height = 26
                    Fill.ColorMirror = clNone
                    Fill.ColorMirrorTo = clNone
                    Fill.GradientType = gtVertical
                    Fill.GradientMirrorType = gtSolid
                    Fill.BorderColor = clNone
                    Fill.Rounding = 0
                    Fill.ShadowOffset = 0
                    Fill.Glow = gmNone
                    Caption.Text = 'Closed'
                    Caption.Font.Charset = DEFAULT_CHARSET
                    Caption.Font.Color = clWindowText
                    Caption.Font.Height = -13
                    Caption.Font.Name = 'Tahoma'
                    Caption.Font.Style = [fsBold]
                    Caption.ColorStart = clSilver
                    Caption.ColorEnd = clWhite
                    CaptionShadow.Text = 'AdvSmoothLabel'
                    CaptionShadow.Font.Charset = DEFAULT_CHARSET
                    CaptionShadow.Font.Color = clWindowText
                    CaptionShadow.Font.Height = -27
                    CaptionShadow.Font.Name = 'Tahoma'
                    CaptionShadow.Font.Style = []
                    Version = '1.6.1.0'
                  end
                  object AdvSmoothLabel32: TAdvSmoothLabel
                    Left = 31
                    Top = 11
                    Width = 91
                    Height = 31
                    Fill.ColorMirror = clNone
                    Fill.ColorMirrorTo = clNone
                    Fill.GradientType = gtVertical
                    Fill.GradientMirrorType = gtSolid
                    Fill.BorderColor = clNone
                    Fill.Rounding = 0
                    Fill.ShadowOffset = 0
                    Fill.Glow = gmNone
                    Caption.Text = 'Connection '
                    Caption.Font.Charset = DEFAULT_CHARSET
                    Caption.Font.Color = clWindowText
                    Caption.Font.Height = -13
                    Caption.Font.Name = 'Tahoma'
                    Caption.Font.Style = [fsBold]
                    Caption.ColorStart = clSilver
                    Caption.ColorEnd = clWhite
                    CaptionShadow.Text = 'AdvSmoothLabel'
                    CaptionShadow.Font.Charset = DEFAULT_CHARSET
                    CaptionShadow.Font.Color = clWindowText
                    CaptionShadow.Font.Height = -27
                    CaptionShadow.Font.Name = 'Tahoma'
                    CaptionShadow.Font.Style = []
                    Version = '1.6.1.0'
                  end
                end
              end
            end
          end
        end
      end
      object advsmthpnl1: TAdvSmoothPanel
        Left = 1052
        Top = 1
        Width = 225
        Height = 72
        Cursor = crDefault
        Caption.Location = plTopCenter
        Caption.HatchStyle = HatchStyleDiagonalBrick
        Caption.HTMLFont.Charset = DEFAULT_CHARSET
        Caption.HTMLFont.Color = clWindowText
        Caption.HTMLFont.Height = -13
        Caption.HTMLFont.Name = 'Tahoma'
        Caption.HTMLFont.Style = []
        Caption.Font.Charset = DEFAULT_CHARSET
        Caption.Font.Color = clWindowText
        Caption.Font.Height = -16
        Caption.Font.Name = 'Tahoma'
        Caption.Font.Style = [fsBold]
        Caption.Top = 20
        Caption.ColorStart = clWhite
        Caption.ColorEnd = clWhite
        Caption.GradientType = gtHorizontal
        Caption.LineColor = clBlack
        Caption.Line = False
        Fill.Color = 7301478
        Fill.ColorTo = 10066329
        Fill.ColorMirror = 10066329
        Fill.ColorMirrorTo = 7301478
        Fill.GradientType = gtVertical
        Fill.GradientMirrorType = gtVertical
        Fill.BorderColor = clSilver
        Fill.BorderWidth = 5
        Fill.Rounding = 10
        Fill.ShadowColor = clNone
        Fill.ShadowOffset = 10
        Fill.Glow = gmNone
        Version = '1.6.0.1'
        Align = alCustom
        Anchors = [akTop, akRight]
        TabOrder = 2
        TMSStyle = 0
        object btnZoomCenterMap1: TSpeedButtonImage
          Left = 16
          Top = 11
          Width = 50
          Height = 50
          Hint = 'Monitor 1'
          Caption = ''
          Flat = True
          Layout = blGlyphTop
          Margin = 0
          ParentShowHint = False
          ShowHint = True
          Spacing = 0
        end
        object btnZoomCenterMap2: TSpeedButtonImage
          Left = 162
          Top = 11
          Width = 50
          Height = 50
          Hint = 'Monitor 2'
          Caption = ''
          Flat = True
          Layout = blGlyphTop
          Margin = 0
          ParentShowHint = False
          ShowHint = True
          Spacing = 0
        end
      end
      object advsmthpnlStatus: TAdvSmoothPanel
        Left = 150
        Top = 0
        Width = 120
        Height = 73
        Cursor = crDefault
        Caption.HTMLFont.Charset = DEFAULT_CHARSET
        Caption.HTMLFont.Color = clWindowText
        Caption.HTMLFont.Height = -11
        Caption.HTMLFont.Name = 'Tahoma'
        Caption.HTMLFont.Style = []
        Caption.Font.Charset = DEFAULT_CHARSET
        Caption.Font.Color = clWindowText
        Caption.Font.Height = -16
        Caption.Font.Name = 'Tahoma'
        Caption.Font.Style = [fsBold]
        Caption.ColorStart = clSilver
        Caption.ColorEnd = clWhite
        Fill.Color = clGray
        Fill.ColorTo = 10066329
        Fill.ColorMirror = 10066329
        Fill.ColorMirrorTo = clGray
        Fill.GradientType = gtVertical
        Fill.GradientMirrorType = gtVertical
        Fill.BorderColor = clSilver
        Fill.BorderWidth = 5
        Fill.Rounding = 10
        Fill.ShadowColor = clNone
        Fill.ShadowOffset = 10
        Fill.Glow = gmNone
        Version = '1.6.0.1'
        Align = alCustom
        TabOrder = 3
        DesignSize = (
          120
          73)
        TMSStyle = 0
        object lblCekRunning: TLabel
          Left = 0
          Top = 40
          Width = 121
          Height = 22
          Alignment = taCenter
          Anchors = [akLeft, akTop, akRight, akBottom]
          AutoSize = False
          Caption = 'Stop'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWhite
          Font.Height = -12
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lbl13: TLabel
          Left = 2
          Top = 23
          Width = 121
          Height = 14
          Alignment = taCenter
          Anchors = [akLeft, akTop, akRight, akBottom]
          AutoSize = False
          Caption = 'Status '
          Font.Charset = ANSI_CHARSET
          Font.Color = clWhite
          Font.Height = -12
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
      end
      object edt1: TEdit
        Left = 1112
        Top = 29
        Width = 121
        Height = 21
        TabOrder = 4
        Visible = False
      end
      object advsmthpnlStatus3D: TAdvSmoothPanel
        Left = 270
        Top = -1
        Width = 120
        Height = 73
        Cursor = crDefault
        Caption.HTMLFont.Charset = DEFAULT_CHARSET
        Caption.HTMLFont.Color = clWindowText
        Caption.HTMLFont.Height = -11
        Caption.HTMLFont.Name = 'Tahoma'
        Caption.HTMLFont.Style = []
        Caption.Font.Charset = DEFAULT_CHARSET
        Caption.Font.Color = clWindowText
        Caption.Font.Height = -16
        Caption.Font.Name = 'Tahoma'
        Caption.Font.Style = [fsBold]
        Caption.ColorStart = clSilver
        Caption.ColorEnd = clWhite
        Fill.Color = clGray
        Fill.ColorTo = 10066329
        Fill.ColorMirror = 10066329
        Fill.ColorMirrorTo = clGray
        Fill.GradientType = gtVertical
        Fill.GradientMirrorType = gtVertical
        Fill.BorderColor = clSilver
        Fill.BorderWidth = 5
        Fill.Rounding = 10
        Fill.ShadowColor = clNone
        Fill.ShadowOffset = 10
        Fill.Glow = gmNone
        Version = '1.6.0.1'
        Align = alCustom
        TabOrder = 5
        DesignSize = (
          120
          73)
        TMSStyle = 0
        object lblBtmStat3d: TLabel
          Left = 0
          Top = 40
          Width = 121
          Height = 22
          Alignment = taCenter
          Anchors = [akLeft, akTop, akRight, akBottom]
          AutoSize = False
          Caption = 'Stop'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWhite
          Font.Height = -12
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
        object lblTopStat3d: TLabel
          Left = 6
          Top = 23
          Width = 121
          Height = 14
          Alignment = taCenter
          Anchors = [akLeft, akTop, akRight, akBottom]
          AutoSize = False
          Caption = 'Status 3D'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWhite
          Font.Height = -12
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          Transparent = True
        end
      end
    end
    object pnlMapInset: TPanel
      Left = 1027
      Top = 463
      Width = 253
      Height = 190
      Anchors = [akRight, akBottom]
      Caption = 'pnlMapInset'
      TabOrder = 3
      DesignSize = (
        253
        190)
      object MapInset: TMap
        Left = 10
        Top = 8
        Width = 233
        Height = 173
        Anchors = [akLeft, akTop, akRight, akBottom]
        ParentColor = False
        TabOrder = 0
        OnDrawUserLayer = MapInsetDrawUserLayer
        ControlData = {
          8A1A060015180000E1110000010000000F0000FF0D47656F44696374696F6E61
          727905456D70747900E8030000000000000000000002000E001E000000000000
          0000000000000000000000000000000000000000000600010000000000500001
          010000640000000001F4010000050000800C000000000000000000000000FFFF
          FF000100000000000000000000000000000000000000000000000352E30B918F
          CE119DE300AA004BB8510100000090010CF2010005417269616C000352E30B91
          8FCE119DE300AA004BB8510100000090015C790C0005417269616C0000000000
          00000000000000000000000000000000000000000000000000000000000000FF
          FFFF000000000000000001370000000000FFFFFF000000000000000352E30B91
          8FCE119DE300AA004BB851010000009001DC7C010005417269616C000352E30B
          918FCE119DE300AA004BB851010200009001A42C02000B4D61702053796D626F
          6C730000000000000001000100FFFFFF000200FFFFFF00000000000001000000
          01000118010000904BA20401000000E5E297001C000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000002
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          8076C000000000008056C0000000000080764000000000008056400100000018
          010000904BA20401000000895F99771C00000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000200000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000000000000000000000
          0000000000000000000000000000000000000000000000895F997700E29700F4
          E197007E91065030E697004EA20550CC9F363305000000000000000000000000
          000088B3400000000000408F400001000001}
      end
    end
  end
  object MainMenu1: TMainMenu
    Left = 209
    Top = 153
    object DisplayGameController1: TMenuItem
      Tag = 1
      Caption = 'Application'
      OnClick = DisplayGameController1Click
      object DisplayController1: TMenuItem
        Tag = 1
        Caption = 'Display Controller'
        OnClick = DisplayController1Click
      end
      object DisplayFiringCommandProcedure1: TMenuItem
        Tag = 2
        Caption = 'Display Firing Command & Procedure'
        Enabled = False
        Visible = False
        OnClick = DisplayController1Click
      end
      object MapReviewSHOW1: TMenuItem
        Caption = 'MapReview'
        OnClick = MapReviewSHOW1Click
      end
      object erminate1: TMenuItem
        Tag = 10
        Caption = 'Exit'
        OnClick = DisplayController1Click
      end
    end
    object mniTools: TMenuItem
      Caption = 'Tools'
      object mniReplay: TMenuItem
        Caption = 'Replay'
        OnClick = mniReplayClick
      end
    end
  end
end
