program SutBlackshark;

uses
  Vcl.Forms,
  uLibConst in 'LibUtils\uLibConst.pas',
  uBaseConst in 'LibBaseSystem\uBaseConst.pas',
  GdiPlus in 'libGDI\GdiPlus.pas',
  GdiPlusHelpers in 'libGDI\GdiPlusHelpers.pas',
  uObjectVisual in 'LibVisual\uObjectVisual.pas',
  uSimVisuals in 'LibVisual\uSimVisuals.pas',
  uCoordConverter in 'LibBaseSystem\uCoordConverter.pas',
  uCoordDataTypes in 'LibBaseSystem\uCoordDataTypes.pas',
  uMapXUnitConverter in 'LibMapX\uMapXUnitConverter.pas',
  uSutBlacksharkManager in 'uSutBlacksharkManager.pas',
  uBridgeSet in '..\ShareLib\LibSetting\uBridgeSet.pas',
  uCodecBase64 in '..\ShareLib\LibSetting\uCodecBase64.pas',
  uSimulationManager in '..\ShareLib\LibBaseSystem\uSimulationManager.pas',
  MSThreadTimer in '..\ShareLib\LibBaseSystem\Timer\MSThreadTimer.pas',
  uVirtualTime in '..\ShareLib\LibBaseSystem\Timer\uVirtualTime.pas',
  uTCPClient in '..\ShareLib\LibNetworks\uTCPClient.pas',
  uTCPDatatype in '..\ShareLib\LibNetworks\uTCPDatatype.pas',
  uBaseDataType in '..\ShareLib\LibBaseSystem\uBaseDataType.pas',
  uBaseSimulationObject in '..\ShareLib\LibBaseSystem\uBaseSimulationObject.pas',
  uBaseConstan in '..\ShareLib\LibBaseSystem\uBaseConstan.pas',
  uTestShip in '..\ShareLib\LibTest\uTestShip.pas',
  uMapXSim in '..\ShareLib\LibObject\uMapXSim.pas',
  uMover in '..\ShareLib\LibObject\uMover.pas',
  uObjectView in '..\ShareLib\LibObject\uObjectView.pas',
  uBaseFunction in '..\ShareLib\LibBaseSystem\uBaseFunction.pas',
  uBaseGraphicProc in '..\ShareLib\libGrafik\uBaseGraphicProc.pas',
  uLibClientObject in '..\ShareLib\LibClientObject\uLibClientObject.pas',
  uRadarVisual in 'LibVisual\uRadarVisual.pas',
  uRadarDynamicSector in 'LibVisual\uRadarDynamicSector.pas',
  uRadarNorthIndicator in 'uRadarNorthIndicator.pas',
  uRadarTargets in 'LibVisual\uRadarTargets.pas',
  uScriptSutBlackshark in 'uScriptSutBlackshark.pas',
  uDataModule in '..\ShareLib\AppForms\uDataModule.pas' {DataModule1: TDataModule},
  uClassDatabase in '..\ShareLib\AppForms\uClassDatabase.pas',
  uVehicleManager in 'uVehicleManager.pas',
  Grijjy.BinaryCoding in '..\ShareLib\LibNetsJSON\Grijjy\Grijjy.BinaryCoding.pas',
  Grijjy.Bson.IO in '..\ShareLib\LibNetsJSON\Grijjy\Grijjy.Bson.IO.pas',
  Grijjy.Bson in '..\ShareLib\LibNetsJSON\Grijjy\Grijjy.Bson.pas',
  Grijjy.Bson.Serialization in '..\ShareLib\LibNetsJSON\Grijjy\Grijjy.Bson.Serialization.pas',
  Grijjy.Collections in '..\ShareLib\LibNetsJSON\Grijjy\Grijjy.Collections.pas',
  Grijjy.DateUtils in '..\ShareLib\LibNetsJSON\Grijjy\Grijjy.DateUtils.pas',
  Grijjy.SysUtils in '..\ShareLib\LibNetsJSON\Grijjy\Grijjy.SysUtils.pas',
  uIniFilesProcs in 'LibSutBlackshark\uIniFilesProcs.pas',
  ulibSettings in 'LibSutBlackshark\ulibSettings.pas',
  uScriptCommon in 'LibSutBlackshark\uScriptCommon.pas',
  uTrackView in 'LibSutBlacksharkObject\uTrackView.pas',
  uVehicle in 'LibSutBlacksharkObject\uVehicle.pas',
  uBaseFunctionSutBlackshark in 'LibBaseSystem\uBaseFunctionSutBlackshark.pas',
  ufrmTorpedoWP in 'ufrmTorpedoWP.pas' {FrmTorpedoWP},
  ufrmTacticalScreen in 'ufrmTacticalScreen.pas' {FrmTacticalScreen},
  uSettingFormToMonitorWith_ini in '..\ShareLib\LibUtil\uSettingFormToMonitorWith_ini.pas',
  uFormUtil in '..\ShareLib\LibUtil\uFormUtil.pas',
  uBaseObject in 'LibSutBlacksharkObject\uBaseObject.pas',
  uPointTrack in 'LibSutBlacksharkObject\uPointTrack.pas',
  UfrmRadar in 'UfrmRadar.pas' {frmRadar},
  uRadarSensor in 'LibMapX\uRadarSensor.pas',
  uShipModel in 'LibMapX\uShipModel.pas',
  uTorpedoLauncher in 'LibSutBlacksharkObject\uTorpedoLauncher.pas',
  uSimulationTrack in 'LibSutBlacksharkObject\uSimulationTrack.pas',
  uSubSurfaceTrack in 'LibSutBlacksharkObject\uSubSurfaceTrack.pas',
  uSurfaceTrack in 'LibSutBlacksharkObject\uSurfaceTrack.pas',
  ufrmDepthPlot in 'Permanen Form\ufrmDepthPlot.pas' {frmDepthPlot},
  ufrmHomingCommands in 'Permanen Form\ufrmHomingCommands.pas' {frmHomingCommands},
  ufrmHomingStatusPlot in 'Permanen Form\ufrmHomingStatusPlot.pas' {frmHomingStatusPlot},
  ufrmTorpedoGuidance in 'Permanen Form\ufrmTorpedoGuidance.pas' {frmTorpedoGuidanceWindow},
  ufrmTorpedoParameterSetting in 'Permanen Form\ufrmTorpedoParameterSetting.pas' {frmTorpedoParameterSetting},
  ufrmTorpedoTubeCommands in 'Permanen Form\ufrmTorpedoTubeCommands.pas' {frmTorpedoTubeCommands},
  ufrmTorpedoTubeStatusWindow in 'Permanen Form\ufrmTorpedoTubeStatusWindow.pas' {frmTorpedoTubeStatusWindow},
  ufrmTrackInfo in 'Permanen Form\ufrmTrackInfo.pas' {frmTrackInfo},
  ufrmControlByNumber in 'Pop-up form\ufrmControlByNumber.pas' {frmControlByNumber},
  ufrmCreateModifyTrack in 'Pop-up form\ufrmCreateModifyTrack.pas' {frmCreateModifyTrack},
  ufrmSensorTrackList in 'Pop-up form\ufrmSensorTrackList.pas' {frmSensorTrackList},
  ufrmTackHistory in 'Pop-up form\ufrmTackHistory.pas' {frmTrackHistory},
  ufrmTorpedoContactList in 'Pop-up form\ufrmTorpedoContactList.pas' {frmTorpedoContactList},
  ufrmTorpedoVerticalView in 'Pop-up form\ufrmTorpedoVerticalView.pas' {frmTorpedoVerticalView},
  ufrmTrackFilter in 'Pop-up form\ufrmTrackFilter.pas' {frmTrackFilter},
  ufrmEngagementDataOverview in 'Permanen Form\ufrmEngagementDataOverview.pas' {frmEngagementDataOverview},
  ufrmManualGuidance in 'Permanen Form\ufrmManualGuidance.pas' {frmManualGuidance},
  ufrmOwnShip in 'Permanen Form\ufrmOwnShip.pas' {frmOwnShip},
  ufrmAlertandOpearatorMassage in 'Permanen Form\ufrmAlertandOpearatorMassage.pas' {frmAlertsandOpearatorMassage},
  ufmTargetInControl in 'Permanen Form\ufmTargetInControl.pas' {frmTargetInControl},
  ufrmContactInControl in 'Permanen Form\ufrmContactInControl.pas' {frmContactInControl},
  ufrmTrackingList in 'Pop-up form\ufrmTrackingList.pas' {frmTrackListNumber},
  ufrmWakeList in 'Pop-up form\ufrmWakeList.pas' {frmWakeList},
  ufrmTorpedoAllocation in 'Permanen Form\ufrmTorpedoAllocation.pas' {frmTorpedoAllocation};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TDataModule1, DataModule1);
  Application.CreateForm(TFrmTorpedoWP, FrmTorpedoWP);
  Application.CreateForm(TFrmTacticalScreen, FrmTacticalScreen);
  Application.CreateForm(TfrmTrackListNumber, frmTrackListNumber);
  Application.CreateForm(TfrmWakeList, frmWakeList);
  Application.CreateForm(TfrmTorpedoAllocation, frmTorpedoAllocation);
  //    Application.CreateForm(TfrmMainSutBlackshark, frmMainSutBlackshark);

  Application.Run;
end.
