object frmTrackFilter: TfrmTrackFilter
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsSingle
  ClientHeight = 478
  ClientWidth = 273
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = -4
    Top = 0
    Width = 440
    Height = 665
    Color = clBlack
    ParentBackground = False
    TabOrder = 0
    object Label3: TLabel
      Left = 13
      Top = 24
      Width = 121
      Height = 16
      Caption = 'Track Velocity Vector'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label1: TLabel
      Left = 16
      Top = 44
      Width = 52
      Height = 16
      Caption = 'Air Track'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label2: TLabel
      Left = 16
      Top = 68
      Width = 149
      Height = 16
      Caption = 'Subsurface/Surface Track'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label4: TLabel
      Left = 37
      Top = 103
      Width = 98
      Height = 16
      Caption = 'Own Ship History'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label5: TLabel
      Left = 14
      Top = 127
      Width = 157
      Height = 16
      Caption = 'Toggle Single Track History'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblToggleSingle: TLabel
      Left = 200
      Top = 129
      Width = 38
      Height = 16
      Caption = 'On/Off'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label6: TLabel
      Left = 15
      Top = 149
      Width = 81
      Height = 16
      Caption = 'History Length'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label7: TLabel
      Left = 151
      Top = 204
      Width = 16
      Height = 16
      Caption = 'Air'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label8: TLabel
      Left = 175
      Top = 204
      Width = 44
      Height = 16
      Caption = 'Surface'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label9: TLabel
      Left = 223
      Top = 205
      Width = 44
      Height = 16
      Caption = 'Subsurf'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label10: TLabel
      Left = 80
      Top = 224
      Width = 14
      Height = 16
      Caption = 'All'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label11: TLabel
      Left = 15
      Top = 243
      Width = 45
      Height = 16
      Caption = 'Pending'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label12: TLabel
      Left = 15
      Top = 262
      Width = 45
      Height = 16
      Caption = 'Friendly'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label13: TLabel
      Left = 15
      Top = 281
      Width = 41
      Height = 16
      Caption = 'Neutral'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label14: TLabel
      Left = 15
      Top = 300
      Width = 39
      Height = 16
      Caption = 'History'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label15: TLabel
      Left = 15
      Top = 320
      Width = 45
      Height = 16
      Caption = 'Vel vect'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label16: TLabel
      Left = 15
      Top = 339
      Width = 51
      Height = 16
      Caption = 'Track No'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label17: TLabel
      Left = 15
      Top = 358
      Width = 55
      Height = 16
      Caption = 'Free Text'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label18: TLabel
      Left = 15
      Top = 377
      Width = 42
      Height = 16
      Caption = 'Symbol'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label19: TLabel
      Left = 37
      Top = 413
      Width = 110
      Height = 16
      Caption = 'Area of Uncertainty'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label20: TLabel
      Left = 36
      Top = 432
      Width = 79
      Height = 16
      Caption = 'Special Points'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label21: TLabel
      Left = 37
      Top = 451
      Width = 74
      Height = 16
      Caption = 'Rim Symbols'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label22: TLabel
      Left = 203
      Top = 416
      Width = 34
      Height = 16
      Caption = 'Radar'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label23: TLabel
      Left = 203
      Top = 434
      Width = 33
      Height = 16
      Caption = 'Link Y'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object cbAirTrack: TComboBox
      Left = 202
      Top = 47
      Width = 63
      Height = 24
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Text = '10 sec'
      Items.Strings = (
        '10 sec'
        '20 sec'
        '30 sec'
        '1 min'
        '3 min'
        '6 min')
    end
    object ComboBox1: TComboBox
      Left = 202
      Top = 71
      Width = 63
      Height = 24
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Text = '1 min'
      Items.Strings = (
        '1 min'
        '3 min'
        '6 min'
        '9 min'
        '15 min')
    end
    object chkOwnShipHistory: TCheckBox
      Left = 13
      Top = 104
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 2
    end
    object cbHistoryLength: TComboBox
      Left = 201
      Top = 148
      Width = 63
      Height = 24
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      Text = '10 min'
      Items.Strings = (
        '10 min'
        '20 min'
        '30 min'
        '40 min'
        '50 min'
        '60 min')
    end
    object chkAir1: TCheckBox
      Left = 151
      Top = 223
      Width = 17
      Height = 17
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 4
    end
    object chkSurface1: TCheckBox
      Left = 194
      Top = 223
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 5
    end
    object chkSubsurf1: TCheckBox
      Left = 236
      Top = 223
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 6
    end
    object chkAir2: TCheckBox
      Left = 151
      Top = 244
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 7
    end
    object chkSurface2: TCheckBox
      Left = 194
      Top = 244
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 8
    end
    object chkSubsurf2: TCheckBox
      Left = 236
      Top = 244
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 9
    end
    object CheckBox8: TCheckBox
      Left = 76
      Top = 245
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 10
    end
    object CheckBox7: TCheckBox
      Left = 76
      Top = 264
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 11
    end
    object CheckBox9: TCheckBox
      Left = 76
      Top = 283
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 12
    end
    object CheckBox10: TCheckBox
      Left = 76
      Top = 302
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 13
    end
    object CheckBox11: TCheckBox
      Left = 76
      Top = 322
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 14
    end
    object CheckBox12: TCheckBox
      Left = 76
      Top = 341
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 15
    end
    object CheckBox13: TCheckBox
      Left = 76
      Top = 360
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 16
    end
    object CheckBox14: TCheckBox
      Left = 76
      Top = 379
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 17
    end
    object chkAir3: TCheckBox
      Left = 150
      Top = 264
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 18
    end
    object chkAir4: TCheckBox
      Left = 150
      Top = 283
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 19
    end
    object chkAir5: TCheckBox
      Left = 150
      Top = 302
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 20
    end
    object chkAir6: TCheckBox
      Left = 150
      Top = 322
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 21
    end
    object chkAir7: TCheckBox
      Left = 150
      Top = 341
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 22
    end
    object chkAir8: TCheckBox
      Left = 150
      Top = 360
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 23
    end
    object chkAir9: TCheckBox
      Left = 150
      Top = 379
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 24
    end
    object chkSurface3: TCheckBox
      Left = 193
      Top = 264
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 25
    end
    object chkSurface4: TCheckBox
      Left = 193
      Top = 283
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 26
    end
    object chkSurface5: TCheckBox
      Left = 193
      Top = 302
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 27
    end
    object chkSurface6: TCheckBox
      Left = 193
      Top = 322
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 28
    end
    object chkSurface7: TCheckBox
      Left = 193
      Top = 341
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 29
    end
    object chkSurface8: TCheckBox
      Left = 193
      Top = 360
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 30
    end
    object chkSurface9: TCheckBox
      Left = 193
      Top = 379
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 31
    end
    object chkSubsurf3: TCheckBox
      Left = 235
      Top = 264
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 32
    end
    object chkSubsurf4: TCheckBox
      Left = 235
      Top = 283
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 33
    end
    object chkSubsurf5: TCheckBox
      Left = 235
      Top = 302
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 34
    end
    object chkSubsurf6: TCheckBox
      Left = 235
      Top = 322
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 35
    end
    object chkSubsurf7: TCheckBox
      Left = 235
      Top = 341
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 36
    end
    object chkSubsurf8: TCheckBox
      Left = 235
      Top = 360
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 37
    end
    object chkSubsurf9: TCheckBox
      Left = 235
      Top = 379
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 38
    end
    object chkArea: TCheckBox
      Left = 14
      Top = 413
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 39
    end
    object chkSpecial: TCheckBox
      Left = 14
      Top = 432
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 40
    end
    object chkRim: TCheckBox
      Left = 14
      Top = 451
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 41
    end
    object chkRadar: TCheckBox
      Left = 182
      Top = 416
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 42
    end
    object chkLink: TCheckBox
      Left = 182
      Top = 434
      Width = 17
      Height = 17
      Caption = 'chkOwnShipHistory'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      TabOrder = 43
    end
  end
end
