object frmTrackInfo: TfrmTrackInfo
  Left = 0
  Top = 0
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 598
  ClientWidth = 552
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TPanel
    Left = -1
    Top = -1
    Width = 554
    Height = 602
    Color = -1
    ParentBackground = False
    TabOrder = 0
    object lbl1: TLabel
      Left = 12
      Top = 13
      Width = 30
      Height = 19
      Caption = 'TNo'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblTNo: TLabel
      Left = 52
      Top = 13
      Width = 54
      Height = 19
      Caption = '110002'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lbl2: TLabel
      Left = 196
      Top = 13
      Width = 48
      Height = 19
      Caption = 'Source'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblSource: TLabel
      Left = 260
      Top = 13
      Width = 44
      Height = 19
      Caption = 'A-MSI'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label1: TLabel
      Left = 12
      Top = 45
      Width = 23
      Height = 19
      Caption = 'Cat'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblCat: TLabel
      Left = 52
      Top = 45
      Width = 79
      Height = 19
      Caption = 'SubSurface'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lbl3: TLabel
      Left = 196
      Top = 45
      Width = 43
      Height = 19
      Caption = 'Pltfrm'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblPlatform: TLabel
      Left = 260
      Top = 45
      Width = 96
      Height = 19
      Caption = 'No Statement'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label6: TLabel
      Left = 12
      Top = 77
      Width = 15
      Height = 19
      Caption = 'Id'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblId: TLabel
      Left = 52
      Top = 77
      Width = 67
      Height = 19
      Caption = 'Unknown'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label8: TLabel
      Left = 196
      Top = 77
      Width = 35
      Height = 19
      Caption = 'Type'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblType: TLabel
      Left = 260
      Top = 77
      Width = 96
      Height = 19
      Caption = 'No Statement'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblCas: TLabel
      Left = 20
      Top = 565
      Width = 30
      Height = 19
      Caption = 'CAS'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblFAS: TLabel
      Left = 75
      Top = 565
      Width = 28
      Height = 19
      Caption = 'FAS'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblInt: TLabel
      Left = 128
      Top = 565
      Width = 20
      Height = 19
      Caption = 'Int'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblP: TLabel
      Left = 173
      Top = 565
      Width = 9
      Height = 19
      Caption = 'P'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblResm1: TLabel
      Left = 207
      Top = 565
      Width = 49
      Height = 19
      Caption = 'RESM1'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblResm2: TLabel
      Left = 281
      Top = 565
      Width = 49
      Height = 19
      Caption = 'RESM2'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lbllink: TLabel
      Left = 355
      Top = 565
      Width = 29
      Height = 19
      Caption = 'Link'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object lblRadar: TLabel
      Left = 409
      Top = 565
      Width = 41
      Height = 19
      Caption = 'Radar'
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object TabSelectTrackInfo: TAdvSmoothTabPager
      Left = 8
      Top = 112
      Width = 521
      Height = 433
      Fill.Color = clBlack
      Fill.ColorTo = -1
      Fill.ColorMirror = -1
      Fill.ColorMirrorTo = -1
      Fill.GradientType = gtVertical
      Fill.GradientMirrorType = gtSolid
      Fill.BorderColor = clBlack
      Fill.Rounding = 0
      Fill.ShadowColor = -1
      Fill.ShadowOffset = 0
      Fill.Glow = gmNone
      Fill.GlowGradientColor = -1
      Fill.GlowRadialColor = -1
      Transparent = False
      ActivePage = TabEW
      Color = -1
      TabTextOrientation = toHorizontal
      TabSettings.LeftMargin = 0
      TabSettings.RightMargin = 0
      TabSettings.StartMargin = 0
      TabSettings.Height = 40
      TabSettings.Spacing = 5
      TabSettings.Width = 85
      TabReorder = False
      TabOrder = 0
      Touch.ParentTabletOptions = False
      Touch.TabletOptions = [toPressAndHold]
      TMSStyle = 4
      object TabKinem: TAdvSmoothTabPage
        Left = 1
        Top = 40
        Width = 519
        Height = 391
        Caption = 'Kinem'
        PageAppearance.Color = -1
        PageAppearance.ColorTo = -1
        PageAppearance.ColorMirror = -1
        PageAppearance.ColorMirrorTo = -1
        PageAppearance.GradientType = gtVertical
        PageAppearance.GradientMirrorType = gtVertical
        PageAppearance.BorderColor = -1
        PageAppearance.BorderWidth = 0
        PageAppearance.Rounding = 0
        PageAppearance.ShadowOffset = 0
        PageAppearance.Glow = gmNone
        TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Appearance.Font.Color = clBlack
        TabAppearance.Appearance.Font.Height = -13
        TabAppearance.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Appearance.Font.Style = []
        TabAppearance.Appearance.FocusColor = -1
        TabAppearance.Appearance.SimpleLayout = True
        TabAppearance.Appearance.Rounding = 0
        TabAppearance.Status.Caption = '0'
        TabAppearance.Status.Appearance.Fill.Color = clRed
        TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
        TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
        TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
        TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
        TabAppearance.Status.Appearance.Fill.BorderColor = clGray
        TabAppearance.Status.Appearance.Fill.Rounding = 0
        TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
        TabAppearance.Status.Appearance.Fill.Glow = gmNone
        TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Status.Appearance.Font.Color = clWhite
        TabAppearance.Status.Appearance.Font.Height = -11
        TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Status.Appearance.Font.Style = []
        TabAppearance.BevelColor = clWhite
        TabAppearance.BevelColorDown = clWhite
        TabAppearance.BevelColorSelected = clWhite
        TabAppearance.BevelColorDisabled = clWhite
        TabAppearance.Color = clWhite
        TabAppearance.ColorDown = clWhite
        TabAppearance.ColorSelected = 16250613
        TabAppearance.ColorHot = 16776701
        TabAppearance.ColorDisabled = clWhite
        TabAppearance.ColorTextHot = clWhite
        TabAppearance.ColorTextSelected = -1
        TMSStyle = 20
        object lblBBRF: TLabel
          Left = 1
          Top = 21
          Width = 100
          Height = 19
          Caption = 'BBRF B-CA BB'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label3: TLabel
          Left = 177
          Top = 21
          Width = 110
          Height = 19
          Caption = '000.0 deg   < -'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label4: TLabel
          Left = 369
          Top = 21
          Width = 87
          Height = 19
          Caption = '0.0 deg/min'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label2: TLabel
          Left = 1
          Top = 53
          Width = 96
          Height = 19
          Caption = 'Bearing (deg)'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label5: TLabel
          Left = 201
          Top = 53
          Width = 23
          Height = 19
          Caption = '0.0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label7: TLabel
          Left = 369
          Top = 53
          Width = 87
          Height = 19
          Caption = '0.0 deg/min'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label9: TLabel
          Left = 1
          Top = 85
          Width = 71
          Height = 19
          Caption = 'Range km'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label10: TLabel
          Left = 177
          Top = 85
          Width = 103
          Height = 19
          Caption = '  0.00           |'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label11: TLabel
          Left = 369
          Top = 85
          Width = 50
          Height = 19
          Caption = '0.0 km'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label12: TLabel
          Left = 1
          Top = 117
          Width = 49
          Height = 19
          Caption = 'Course'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label13: TLabel
          Left = 177
          Top = 117
          Width = 102
          Height = 19
          Caption = '000.0           |'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label14: TLabel
          Left = 369
          Top = 117
          Width = 54
          Height = 19
          Caption = '0.0 deg'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label15: TLabel
          Left = 1
          Top = 149
          Width = 43
          Height = 19
          Caption = 'Speed'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label16: TLabel
          Left = 177
          Top = 149
          Width = 104
          Height = 19
          Caption = '  3.5             |'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label17: TLabel
          Left = 369
          Top = 149
          Width = 55
          Height = 19
          Caption = '0.9 m/s'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label18: TLabel
          Left = 1
          Top = 181
          Width = 42
          Height = 19
          Caption = 'Depth'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label19: TLabel
          Left = 177
          Top = 181
          Width = 61
          Height = 19
          Caption = '  00.0 m'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label21: TLabel
          Left = 1
          Top = 277
          Width = 61
          Height = 19
          Caption = 'Obs Age'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label22: TLabel
          Left = 177
          Top = 277
          Width = 113
          Height = 19
          Caption = '00:00:00 h:m:s'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label30: TLabel
          Left = 1
          Top = 303
          Width = 94
          Height = 19
          Caption = 'Track Quality'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblTrackQuality: TLabel
          Left = 177
          Top = 303
          Width = 112
          Height = 19
          Caption = '           0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object AdvGridDropDown1: TAdvGridDropDown
          Left = 80
          Top = 88
          Width = 41
          Height = 21
          LineColor = 15855083
          FixedLineColor = 13745060
          Columns = <
            item
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Tahoma'
              Font.Style = []
            end
            item
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Tahoma'
              Font.Style = []
            end
            item
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -11
              Font.Name = 'Tahoma'
              Font.Style = []
            end>
          HeaderColor = clWhite
          HeaderColorTo = clGray
          HeaderHeight = 25
          HeaderFont.Charset = DEFAULT_CHARSET
          HeaderFont.Color = 7485192
          HeaderFont.Height = -11
          HeaderFont.Name = 'Tahoma'
          HeaderFont.Style = []
          Items = <>
          Navigation.HomeEndKey = heFirstLastRow
          SearchFooter.FindNextCaption = 'Find &next'
          SearchFooter.FindPrevCaption = 'Find &previous'
          SearchFooter.Font.Charset = DEFAULT_CHARSET
          SearchFooter.Font.Color = clWindowText
          SearchFooter.Font.Height = -11
          SearchFooter.Font.Name = 'Tahoma'
          SearchFooter.Font.Style = []
          SearchFooter.HighLightCaption = 'Highlight'
          SearchFooter.HintClose = 'Close'
          SearchFooter.HintFindNext = 'Find next occurrence'
          SearchFooter.HintFindPrev = 'Find previous occurrence'
          SearchFooter.HintHighlight = 'Highlight occurrences'
          SearchFooter.MatchCaseCaption = 'Match case'
          SearchFooter.ResultFormat = '(%d of %d)'
          Style = dsDropDown
          DropDownBorderColor = clNone
          DropDownHeight = 200
          LabelMargin = 0
          LabelFont.Charset = DEFAULT_CHARSET
          LabelFont.Color = clWindowText
          LabelFont.Height = -11
          LabelFont.Name = 'Tahoma'
          LabelFont.Style = []
          Version = '6.1.1.0'
          SelectionColor = 14155773
          SelectionColorTo = 5821692
          ButtonAppearance.BorderColorHot = 10079963
          ButtonAppearance.BorderColorDown = clBlack
          ButtonAppearance.Color = clBlack
          ButtonAppearance.ColorTo = 16768452
          ButtonAppearance.ColorDisabledTo = 11974326
          ButtonAppearance.ColorDown = 11196927
          ButtonAppearance.ColorDownTo = 7257087
          ButtonAppearance.ColorHot = 15465983
          ButtonAppearance.ColorHotTo = 11332863
          ButtonAppearance.Font.Charset = DEFAULT_CHARSET
          ButtonAppearance.Font.Color = clWindowText
          ButtonAppearance.Font.Height = -11
          ButtonAppearance.Font.Name = 'Tahoma'
          ButtonAppearance.Font.Style = []
          DropDownHeader.Color = 16773091
          DropDownHeader.ColorTo = 16765615
          DropDownHeader.Font.Charset = DEFAULT_CHARSET
          DropDownHeader.Font.Color = 7485192
          DropDownHeader.Font.Height = -11
          DropDownHeader.Font.Name = 'Tahoma'
          DropDownHeader.Font.Style = []
          DropDownHeader.Visible = True
          DropDownHeader.BorderColor = 16765615
          DropDownHeader.Buttons = <>
          DropDownFooter.Color = 16773091
          DropDownFooter.ColorTo = 16765615
          DropDownFooter.Font.Charset = DEFAULT_CHARSET
          DropDownFooter.Font.Color = 7485192
          DropDownFooter.Font.Height = -11
          DropDownFooter.Font.Name = 'Tahoma'
          DropDownFooter.Font.Style = []
          DropDownFooter.Visible = True
          DropDownFooter.BorderColor = 16765615
          DropDownFooter.Buttons = <>
          TabOrder = 0
          SelectionColorStyle = 1
          TMSStyle = 4
        end
      end
      object TabGen: TAdvSmoothTabPage
        Left = 1
        Top = 40
        Width = 519
        Height = 391
        Caption = 'Gen'
        PageAppearance.Color = -1
        PageAppearance.ColorTo = -1
        PageAppearance.ColorMirror = -1
        PageAppearance.ColorMirrorTo = -1
        PageAppearance.GradientType = gtVertical
        PageAppearance.GradientMirrorType = gtVertical
        PageAppearance.BorderColor = -1
        PageAppearance.Rounding = 0
        PageAppearance.ShadowOffset = 0
        PageAppearance.Glow = gmNone
        TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Appearance.Font.Color = clBlack
        TabAppearance.Appearance.Font.Height = -11
        TabAppearance.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Appearance.Font.Style = []
        TabAppearance.Appearance.SimpleLayout = True
        TabAppearance.Appearance.Rounding = 0
        TabAppearance.Status.Caption = '0'
        TabAppearance.Status.Appearance.Fill.Color = clRed
        TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
        TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
        TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
        TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
        TabAppearance.Status.Appearance.Fill.BorderColor = clGray
        TabAppearance.Status.Appearance.Fill.Rounding = 0
        TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
        TabAppearance.Status.Appearance.Fill.Glow = gmNone
        TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Status.Appearance.Font.Color = clWhite
        TabAppearance.Status.Appearance.Font.Height = -11
        TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Status.Appearance.Font.Style = []
        TabAppearance.BevelColor = clWhite
        TabAppearance.BevelColorDown = clWhite
        TabAppearance.BevelColorSelected = clWhite
        TabAppearance.BevelColorDisabled = clWhite
        TabAppearance.Color = clWhite
        TabAppearance.ColorDown = clWhite
        TabAppearance.ColorSelected = 16250613
        TabAppearance.ColorHot = 16776701
        TabAppearance.ColorDisabled = clWhite
        TabAppearance.ColorTextHot = clWhite
        TabAppearance.ColorTextSelected = -1
        TMSStyle = 20
        object Label25: TLabel
          Left = 12
          Top = 189
          Width = 120
          Height = 19
          Caption = 'IFF Mode Code 1'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblSubmarineConfLevel: TLabel
          Left = 220
          Top = 189
          Width = 96
          Height = 19
          Caption = 'No Statement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label27: TLabel
          Left = 12
          Top = 213
          Width = 120
          Height = 19
          Caption = 'IFF Mode Code 2'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblEstimatedDepth: TLabel
          Left = 220
          Top = 213
          Width = 96
          Height = 19
          Caption = 'No Statement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label29: TLabel
          Left = 12
          Top = 237
          Width = 120
          Height = 19
          Caption = 'IFF Mode Code 3'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblDataReportType: TLabel
          Left = 220
          Top = 237
          Width = 142
          Height = 19
          Caption = 'Surfaced Submarine'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label31: TLabel
          Left = 12
          Top = 277
          Width = 66
          Height = 19
          Caption = 'Free Text'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFreetext: TLabel
          Left = 220
          Top = 277
          Width = 76
          Height = 19
          Caption = 'Amundsen'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label33: TLabel
          Left = 12
          Top = 301
          Width = 52
          Height = 19
          Caption = 'Activity'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblActivity: TLabel
          Left = 220
          Top = 301
          Width = 95
          Height = 19
          Caption = 'No Ststement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label35: TLabel
          Left = 12
          Top = 341
          Width = 106
          Height = 19
          Caption = 'Weapon Range'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblWeaponRange: TLabel
          Left = 220
          Top = 341
          Width = 23
          Height = 19
          Caption = '0.0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label37: TLabel
          Left = 12
          Top = 365
          Width = 115
          Height = 19
          Caption = 'Detection Range'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblDetectionRange: TLabel
          Left = 220
          Top = 365
          Width = 23
          Height = 19
          Caption = '0.0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label26: TLabel
          Left = 252
          Top = 341
          Width = 22
          Height = 19
          Caption = 'km'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label28: TLabel
          Left = 252
          Top = 365
          Width = 22
          Height = 19
          Caption = 'km'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object RzTrackNumbers: TRzCheckGroup
          Left = 8
          Top = 40
          Width = 201
          Height = 121
          Caption = 'Track Number'
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWhite
          CaptionFont.Height = -11
          CaptionFont.Name = 'Tahoma'
          CaptionFont.Style = []
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -11
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          object Label20: TLabel
            Left = 12
            Top = 21
            Width = 62
            Height = 19
            Caption = 'MSI TNo'
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -16
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
          object lblMSITNo: TLabel
            Left = 100
            Top = 21
            Width = 63
            Height = 19
            Caption = '1100002'
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -16
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
          object Label23: TLabel
            Left = 12
            Top = 53
            Width = 79
            Height = 19
            Caption = 'Link Y TNo'
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -16
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
          object lblLinkYTNo: TLabel
            Left = 100
            Top = 53
            Width = 36
            Height = 19
            Caption = '1234'
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -16
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
          object Label24: TLabel
            Left = 12
            Top = 85
            Width = 62
            Height = 19
            Caption = 'Rep TNo'
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -16
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
          object lblRepTNo: TLabel
            Left = 100
            Top = 85
            Width = 36
            Height = 19
            Caption = '0012'
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -16
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = False
            ParentFont = False
          end
        end
        object RzTrackIndicators: TRzCheckGroup
          Left = 224
          Top = 40
          Width = 265
          Height = 121
          Caption = 'Track Indicators'
          CaptionFont.Charset = DEFAULT_CHARSET
          CaptionFont.Color = clWhite
          CaptionFont.Height = -11
          CaptionFont.Name = 'Tahoma'
          CaptionFont.Style = []
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Tahoma'
          Font.Style = []
          ItemFont.Charset = DEFAULT_CHARSET
          ItemFont.Color = clBlack
          ItemFont.Height = -11
          ItemFont.Name = 'Tahoma'
          ItemFont.Style = []
          ItemHeight = 15
          Items.Strings = (
            'Exercise'
            'Force Tell'
            'Emergency')
          ParentFont = False
          TabOrder = 1
          CheckStates = (
            0
            0
            0)
        end
      end
      object TabSonar: TAdvSmoothTabPage
        Left = 1
        Top = 40
        Width = 519
        Height = 391
        Caption = 'Sonar'
        PageAppearance.Color = -1
        PageAppearance.ColorTo = -1
        PageAppearance.ColorMirror = -1
        PageAppearance.ColorMirrorTo = -1
        PageAppearance.GradientType = gtVertical
        PageAppearance.GradientMirrorType = gtVertical
        PageAppearance.BorderColor = -1
        PageAppearance.Rounding = 0
        PageAppearance.ShadowOffset = 0
        PageAppearance.Glow = gmNone
        TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Appearance.Font.Color = clBlack
        TabAppearance.Appearance.Font.Height = -11
        TabAppearance.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Appearance.Font.Style = []
        TabAppearance.Appearance.SimpleLayout = True
        TabAppearance.Appearance.Rounding = 0
        TabAppearance.Status.Caption = '0'
        TabAppearance.Status.Appearance.Fill.Color = clRed
        TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
        TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
        TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
        TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
        TabAppearance.Status.Appearance.Fill.BorderColor = clGray
        TabAppearance.Status.Appearance.Fill.Rounding = 0
        TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
        TabAppearance.Status.Appearance.Fill.Glow = gmNone
        TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Status.Appearance.Font.Color = clWhite
        TabAppearance.Status.Appearance.Font.Height = -11
        TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Status.Appearance.Font.Style = []
        TabAppearance.BevelColor = clWhite
        TabAppearance.BevelColorDown = clWhite
        TabAppearance.BevelColorSelected = clWhite
        TabAppearance.BevelColorDisabled = clWhite
        TabAppearance.Color = clWhite
        TabAppearance.ColorDown = 16250613
        TabAppearance.ColorSelected = 16250613
        TabAppearance.ColorHot = 16776701
        TabAppearance.ColorDisabled = 15921906
        TMSStyle = 20
        object lvTracklistNumber: TListView
          Left = 8
          Top = 16
          Width = 473
          Height = 81
          BevelInner = bvNone
          BevelOuter = bvNone
          BiDiMode = bdRightToLeft
          Color = -1
          Columns = <
            item
              Caption = 'Sensor'
            end
            item
              Alignment = taCenter
              Caption = 'Id'
            end
            item
              Alignment = taRightJustify
              Caption = 'Tgl Lvl(dB)'
            end
            item
              Alignment = taRightJustify
              Caption = 'Conf(%)'
            end
            item
              Alignment = taRightJustify
              Caption = 'Classification'
            end>
          GridLines = True
          ParentBiDiMode = False
          TabOrder = 0
          ViewStyle = vsReport
        end
      end
      object TabIntercept: TAdvSmoothTabPage
        Left = 1
        Top = 40
        Width = 519
        Height = 391
        Caption = 'Intercept'
        PageAppearance.Color = clBlack
        PageAppearance.ColorTo = clBlack
        PageAppearance.ColorMirror = clBlack
        PageAppearance.ColorMirrorTo = clBlack
        PageAppearance.GradientType = gtVertical
        PageAppearance.GradientMirrorType = gtVertical
        PageAppearance.BorderColor = clBlack
        PageAppearance.Rounding = 0
        PageAppearance.ShadowOffset = 0
        PageAppearance.Glow = gmNone
        PageAppearance.GlowGradientColor = clBlack
        PageAppearance.GlowRadialColor = clBlack
        TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Appearance.Font.Color = clBlack
        TabAppearance.Appearance.Font.Height = -11
        TabAppearance.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Appearance.Font.Style = []
        TabAppearance.Appearance.SimpleLayout = True
        TabAppearance.Appearance.Rounding = 0
        TabAppearance.Status.Caption = '0'
        TabAppearance.Status.Appearance.Fill.Color = clRed
        TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
        TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
        TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
        TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
        TabAppearance.Status.Appearance.Fill.BorderColor = clGray
        TabAppearance.Status.Appearance.Fill.Rounding = 0
        TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
        TabAppearance.Status.Appearance.Fill.Glow = gmNone
        TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Status.Appearance.Font.Color = clWhite
        TabAppearance.Status.Appearance.Font.Height = -11
        TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Status.Appearance.Font.Style = []
        TabAppearance.BevelColor = clWhite
        TabAppearance.BevelColorDown = clWhite
        TabAppearance.BevelColorSelected = clWhite
        TabAppearance.BevelColorDisabled = clWhite
        TabAppearance.Color = clWhite
        TabAppearance.ColorDown = clWhite
        TabAppearance.ColorSelected = 16250613
        TabAppearance.ColorHot = 16776701
        TabAppearance.ColorDisabled = clWhite
        TabAppearance.ColorTextHot = clWhite
        TMSStyle = 20
        object Label32: TLabel
          Left = 20
          Top = 21
          Width = 73
          Height = 19
          Caption = 'Contact Id'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblContactId: TLabel
          Left = 316
          Top = 21
          Width = 39
          Height = 19
          Caption = '      1'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblSensor: TLabel
          Left = 316
          Top = 53
          Width = 40
          Height = 19
          Caption = '  CAS'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label36: TLabel
          Left = 20
          Top = 53
          Width = 48
          Height = 19
          Caption = 'Sensor'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFrequency: TLabel
          Left = 316
          Top = 85
          Width = 38
          Height = 19
          Caption = '   1.0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label39: TLabel
          Left = 20
          Top = 85
          Width = 72
          Height = 19
          Caption = 'Frequency'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPRI: TLabel
          Left = 316
          Top = 117
          Width = 53
          Height = 19
          Caption = '   0.10'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label41: TLabel
          Left = 20
          Top = 117
          Width = 25
          Height = 19
          Caption = 'PRI'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPulselength: TLabel
          Left = 316
          Top = 149
          Width = 50
          Height = 19
          Caption = '0.0000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label43: TLabel
          Left = 20
          Top = 149
          Width = 90
          Height = 19
          Caption = 'Pulse Length'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPulseLevel: TLabel
          Left = 316
          Top = 181
          Width = 43
          Height = 19
          Caption = '    0.0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label45: TLabel
          Left = 20
          Top = 181
          Width = 78
          Height = 19
          Caption = 'Pulse Level'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblConfidence: TLabel
          Left = 316
          Top = 213
          Width = 39
          Height = 19
          Caption = '      0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label47: TLabel
          Left = 20
          Top = 213
          Width = 78
          Height = 19
          Caption = 'Confidence'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblClassification: TLabel
          Left = 260
          Top = 245
          Width = 99
          Height = 19
          Caption = '12345678901'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label49: TLabel
          Left = 20
          Top = 245
          Width = 91
          Height = 19
          Caption = 'Classification'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label34: TLabel
          Left = 372
          Top = 85
          Width = 26
          Height = 19
          Caption = 'kHz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label38: TLabel
          Left = 382
          Top = 117
          Width = 7
          Height = 19
          Caption = 's'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label50: TLabel
          Left = 382
          Top = 149
          Width = 7
          Height = 19
          Caption = 's'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label51: TLabel
          Left = 372
          Top = 181
          Width = 18
          Height = 19
          Caption = 'dB'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label52: TLabel
          Left = 372
          Top = 213
          Width = 16
          Height = 19
          Caption = '%'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
      end
      object TabRESM: TAdvSmoothTabPage
        Left = 1
        Top = 40
        Width = 519
        Height = 391
        Caption = 'RESM'
        PageAppearance.Color = clBlack
        PageAppearance.ColorTo = clBlack
        PageAppearance.ColorMirror = clBlack
        PageAppearance.ColorMirrorTo = clBlack
        PageAppearance.GradientType = gtVertical
        PageAppearance.GradientMirrorType = gtVertical
        PageAppearance.BorderColor = clBlack
        PageAppearance.Rounding = 0
        PageAppearance.ShadowOffset = 0
        PageAppearance.Glow = gmNone
        PageAppearance.GlowGradientColor = clBlack
        TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Appearance.Font.Color = clBlack
        TabAppearance.Appearance.Font.Height = -11
        TabAppearance.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Appearance.Font.Style = []
        TabAppearance.Appearance.SimpleLayout = True
        TabAppearance.Appearance.Rounding = 0
        TabAppearance.Status.Caption = '0'
        TabAppearance.Status.Appearance.Fill.Color = clRed
        TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
        TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
        TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
        TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
        TabAppearance.Status.Appearance.Fill.BorderColor = clGray
        TabAppearance.Status.Appearance.Fill.Rounding = 0
        TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
        TabAppearance.Status.Appearance.Fill.Glow = gmNone
        TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Status.Appearance.Font.Color = clWhite
        TabAppearance.Status.Appearance.Font.Height = -11
        TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Status.Appearance.Font.Style = []
        TabAppearance.BevelColor = clWhite
        TabAppearance.BevelColorDown = clWhite
        TabAppearance.BevelColorSelected = clWhite
        TabAppearance.BevelColorDisabled = clWhite
        TabAppearance.Color = clWhite
        TabAppearance.ColorDown = 16250613
        TabAppearance.ColorSelected = clWhite
        TabAppearance.ColorHot = 16776701
        TabAppearance.ColorDisabled = 15921906
        TabAppearance.ColorTextHot = clWhite
        TabAppearance.ColorTextDisabled = clWhite
        TMSStyle = 20
        object Label40: TLabel
          Left = 12
          Top = 45
          Width = 83
          Height = 19
          Caption = 'Pulse Width'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPulseWidth: TLabel
          Left = 132
          Top = 45
          Width = 50
          Height = 19
          Caption = '204.00'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label44: TLabel
          Left = 12
          Top = 13
          Width = 54
          Height = 19
          Caption = 'RESM 1'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label46: TLabel
          Left = 188
          Top = 45
          Width = 16
          Height = 19
          Caption = 'us'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label42: TLabel
          Left = 292
          Top = 45
          Width = 27
          Height = 19
          Caption = 'PRF'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPRF: TLabel
          Left = 412
          Top = 45
          Width = 41
          Height = 19
          Caption = '0.000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label53: TLabel
          Left = 468
          Top = 45
          Width = 26
          Height = 19
          Caption = 'kHz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label48: TLabel
          Left = 12
          Top = 77
          Width = 73
          Height = 19
          Caption = 'Scan Type'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFixedScan: TLabel
          Left = 132
          Top = 77
          Width = 103
          Height = 19
          Caption = 'Fixed Scan (D)'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label54: TLabel
          Left = 12
          Top = 109
          Width = 83
          Height = 19
          Caption = 'Scan Period'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblScanPeriod: TLabel
          Left = 132
          Top = 109
          Width = 50
          Height = 19
          Caption = '30.000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label56: TLabel
          Left = 188
          Top = 109
          Width = 7
          Height = 19
          Caption = 's'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label55: TLabel
          Left = 13
          Top = 140
          Width = 31
          Height = 19
          Caption = 'Freq'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFrq: TLabel
          Left = 132
          Top = 140
          Width = 50
          Height = 19
          Caption = '0.0000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label58: TLabel
          Left = 189
          Top = 141
          Width = 29
          Height = 19
          Caption = 'GHz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFMOP: TLabel
          Left = 285
          Top = 141
          Width = 41
          Height = 19
          Caption = 'FMOP'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblCW: TLabel
          Left = 369
          Top = 141
          Width = 24
          Height = 19
          Caption = 'CW'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPMOP: TLabel
          Left = 424
          Top = 141
          Width = 42
          Height = 19
          Caption = 'PMOP'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label57: TLabel
          Left = 13
          Top = 172
          Width = 73
          Height = 19
          Caption = 'Amplitude'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblAmplitude: TLabel
          Left = 132
          Top = 172
          Width = 49
          Height = 19
          Caption = '        0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label60: TLabel
          Left = 189
          Top = 173
          Width = 18
          Height = 19
          Caption = 'dB'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label59: TLabel
          Left = 12
          Top = 213
          Width = 54
          Height = 19
          Caption = 'RESM 2'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label61: TLabel
          Left = 12
          Top = 245
          Width = 83
          Height = 19
          Caption = 'Pulse Width'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPulseWidthResm2: TLabel
          Left = 124
          Top = 245
          Width = 50
          Height = 19
          Caption = '204.00'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label63: TLabel
          Left = 180
          Top = 245
          Width = 16
          Height = 19
          Caption = 'us'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label64: TLabel
          Left = 292
          Top = 245
          Width = 27
          Height = 19
          Caption = 'PRF'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPRFResm2: TLabel
          Left = 412
          Top = 245
          Width = 41
          Height = 19
          Caption = '0.000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label66: TLabel
          Left = 468
          Top = 245
          Width = 26
          Height = 19
          Caption = 'kHz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label67: TLabel
          Left = 12
          Top = 277
          Width = 73
          Height = 19
          Caption = 'Scan Type'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblScantypeResm2: TLabel
          Left = 124
          Top = 277
          Width = 103
          Height = 19
          Caption = 'Fixed Scan (D)'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label69: TLabel
          Left = 12
          Top = 309
          Width = 83
          Height = 19
          Caption = 'Scan Period'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblscanPeriodResm2: TLabel
          Left = 124
          Top = 309
          Width = 50
          Height = 19
          Caption = '30.000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label71: TLabel
          Left = 180
          Top = 309
          Width = 7
          Height = 19
          Caption = 's'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label72: TLabel
          Left = 14
          Top = 341
          Width = 31
          Height = 19
          Caption = 'Freq'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFreqResm2: TLabel
          Left = 124
          Top = 340
          Width = 50
          Height = 19
          Caption = '0.0000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label74: TLabel
          Left = 181
          Top = 341
          Width = 29
          Height = 19
          Caption = 'GHz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFMOPResm2: TLabel
          Left = 285
          Top = 341
          Width = 41
          Height = 19
          Caption = 'FMOP'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblCWResm: TLabel
          Left = 369
          Top = 341
          Width = 24
          Height = 19
          Caption = 'CW'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPMOPResm2: TLabel
          Left = 424
          Top = 341
          Width = 42
          Height = 19
          Caption = 'PMOP'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label78: TLabel
          Left = 189
          Top = 373
          Width = 18
          Height = 19
          Caption = 'dB'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblAmplitudeResm2: TLabel
          Left = 132
          Top = 372
          Width = 49
          Height = 19
          Caption = '        0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label80: TLabel
          Left = 13
          Top = 372
          Width = 73
          Height = 19
          Caption = 'Amplitude'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
      end
      object TabEW: TAdvSmoothTabPage
        Left = 1
        Top = 40
        Width = 519
        Height = 391
        Caption = 'EW'
        PageAppearance.Color = clBlack
        PageAppearance.ColorTo = clBlack
        PageAppearance.ColorMirror = clBlack
        PageAppearance.ColorMirrorTo = clBlack
        PageAppearance.GradientType = gtVertical
        PageAppearance.GradientMirrorType = gtVertical
        PageAppearance.BorderColor = clBlack
        PageAppearance.Rounding = 0
        PageAppearance.ShadowOffset = 0
        PageAppearance.Glow = gmNone
        PageAppearance.GlowGradientColor = clBlack
        PageAppearance.GlowRadialColor = clBlack
        TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Appearance.Font.Color = clBlack
        TabAppearance.Appearance.Font.Height = -11
        TabAppearance.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Appearance.Font.Style = []
        TabAppearance.Appearance.SimpleLayout = True
        TabAppearance.Appearance.Rounding = 0
        TabAppearance.Status.Caption = '0'
        TabAppearance.Status.Appearance.Fill.Color = clRed
        TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
        TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
        TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
        TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
        TabAppearance.Status.Appearance.Fill.BorderColor = clGray
        TabAppearance.Status.Appearance.Fill.Rounding = 0
        TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
        TabAppearance.Status.Appearance.Fill.Glow = gmNone
        TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
        TabAppearance.Status.Appearance.Font.Color = clWhite
        TabAppearance.Status.Appearance.Font.Height = -11
        TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
        TabAppearance.Status.Appearance.Font.Style = []
        TabAppearance.BevelColor = clWhite
        TabAppearance.BevelColorDown = clWhite
        TabAppearance.BevelColorSelected = clWhite
        TabAppearance.BevelColorDisabled = clWhite
        TabAppearance.Color = clWhite
        TabAppearance.ColorDown = 16250613
        TabAppearance.ColorSelected = 16250613
        TabAppearance.ColorHot = 16776701
        TabAppearance.ColorDisabled = 15921906
        TMSStyle = 20
        object Label62: TLabel
          Left = 12
          Top = 13
          Width = 51
          Height = 19
          Caption = 'Emitter'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label65: TLabel
          Left = 12
          Top = 45
          Width = 20
          Height = 19
          Caption = 'No'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblNumber: TLabel
          Left = 76
          Top = 45
          Width = 9
          Height = 19
          Caption = '0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label68: TLabel
          Left = 12
          Top = 77
          Width = 78
          Height = 19
          Caption = 'Confidence'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label73: TLabel
          Left = 172
          Top = 45
          Width = 63
          Height = 19
          Caption = 'Mode No'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblModeNumber: TLabel
          Left = 260
          Top = 45
          Width = 9
          Height = 19
          Caption = '0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblConfidenceEW: TLabel
          Left = 172
          Top = 77
          Width = 96
          Height = 19
          Caption = 'No Statement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label70: TLabel
          Left = 12
          Top = 125
          Width = 132
          Height = 19
          Caption = 'Platform Eval Conf'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lbl76: TLabel
          Left = 12
          Top = 157
          Width = 91
          Height = 19
          Caption = 'Broad Classif'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPlatformEvalConf: TLabel
          Left = 172
          Top = 125
          Width = 96
          Height = 19
          Caption = 'No Statement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblBroadClassif: TLabel
          Left = 172
          Top = 157
          Width = 96
          Height = 19
          Caption = 'No Statement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label75: TLabel
          Left = 12
          Top = 237
          Width = 35
          Height = 19
          Caption = 'Jitter'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblJitter: TLabel
          Left = 172
          Top = 237
          Width = 96
          Height = 19
          Caption = 'No Statement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label77: TLabel
          Left = 12
          Top = 269
          Width = 83
          Height = 19
          Caption = 'Pulse Width'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPulseWidthEW: TLabel
          Left = 172
          Top = 269
          Width = 32
          Height = 19
          Caption = '0.00'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label81: TLabel
          Left = 12
          Top = 202
          Width = 43
          Height = 19
          Caption = 'Signal'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label76: TLabel
          Left = 215
          Top = 269
          Width = 16
          Height = 19
          Caption = 'us'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label79: TLabel
          Left = 292
          Top = 237
          Width = 47
          Height = 19
          Caption = 'Polariz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblPolariz: TLabel
          Left = 406
          Top = 237
          Width = 96
          Height = 19
          Caption = 'No Statement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label83: TLabel
          Left = 292
          Top = 269
          Width = 31
          Height = 19
          Caption = 'Freq'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFreqEW: TLabel
          Left = 404
          Top = 269
          Width = 41
          Height = 19
          Caption = '0.000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label85: TLabel
          Left = 455
          Top = 269
          Width = 26
          Height = 19
          Caption = 'kHz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label82: TLabel
          Left = 12
          Top = 301
          Width = 73
          Height = 19
          Caption = 'Scan Type'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblScanTypeEW: TLabel
          Left = 172
          Top = 301
          Width = 96
          Height = 19
          Caption = 'No Statement'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label84: TLabel
          Left = 12
          Top = 333
          Width = 83
          Height = 19
          Caption = 'Scan Period'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblScanPeriodEW: TLabel
          Left = 185
          Top = 333
          Width = 23
          Height = 19
          Caption = '0.0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label87: TLabel
          Left = 215
          Top = 333
          Width = 7
          Height = 19
          Caption = 's'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label88: TLabel
          Left = 292
          Top = 333
          Width = 31
          Height = 19
          Caption = 'Rate'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblRateEW: TLabel
          Left = 420
          Top = 333
          Width = 23
          Height = 19
          Caption = '0.0'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label90: TLabel
          Left = 455
          Top = 333
          Width = 18
          Height = 19
          Caption = 'Hz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label86: TLabel
          Left = 12
          Top = 365
          Width = 45
          Height = 19
          Caption = 'Freq 1'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFreq1EW: TLabel
          Left = 170
          Top = 365
          Width = 41
          Height = 19
          Caption = '0.000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label91: TLabel
          Left = 215
          Top = 365
          Width = 29
          Height = 19
          Caption = 'GHz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lbl77: TLabel
          Left = 292
          Top = 365
          Width = 45
          Height = 19
          Caption = 'Freq 2'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object lblFreq2EW: TLabel
          Left = 404
          Top = 365
          Width = 41
          Height = 19
          Caption = '0.000'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
        object Label94: TLabel
          Left = 455
          Top = 365
          Width = 29
          Height = 19
          Caption = 'GHz'
          Color = clWhite
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWhite
          Font.Height = -16
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentColor = False
          ParentFont = False
        end
      end
    end
  end
end
