object frmMainFCC: TfrmMainFCC
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'FCC'
  ClientHeight = 1024
  ClientWidth = 1280
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesigned
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Label6: TLabel
    Left = 28
    Top = 235
    Width = 39
    Height = 16
    Caption = 'Radar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label16: TLabel
    Left = 132
    Top = 235
    Width = 24
    Height = 16
    Caption = '----'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object pnlUpper: TPanel
    Left = 0
    Top = 0
    Width = 1280
    Height = 1027
    TabOrder = 0
    object pnlViewer3DTV: TPanel
      Left = 0
      Top = 0
      Width = 640
      Height = 480
      BevelOuter = bvNone
      Caption = 'pnlViewer3DTV'
      Color = clBlack
      ParentBackground = False
      TabOrder = 0
      object Shape1: TShape
        Left = 325
        Top = 0
        Width = 1
        Height = 501
        Pen.Color = clWhite
        Visible = False
      end
      object Shape2: TShape
        Left = 0
        Top = 251
        Width = 649
        Height = 1
        Pen.Color = clWhite
        Visible = False
      end
      object Panel1: TPanel
        Left = 0
        Top = 439
        Width = 640
        Height = 41
        Align = alBottom
        BevelOuter = bvNone
        Caption = 'pnlValBearElev'
        TabOrder = 0
        ExplicitLeft = 232
        ExplicitTop = 224
        ExplicitWidth = 185
        object lblValBearTop: TPanel
          Left = 185
          Top = 0
          Width = 176
          Height = 41
          Align = alClient
          BevelOuter = bvNone
          Caption = 'BE 000.00'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWhite
          Font.Height = -17
          Font.Name = 'Consolas'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
          ExplicitLeft = 0
          ExplicitWidth = 361
        end
        object lblValElevTop: TPanel
          Left = 361
          Top = 0
          Width = 279
          Height = 41
          Align = alRight
          BevelOuter = bvNone
          Caption = 'EL:    0.00 deg'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWhite
          Font.Height = -17
          Font.Name = 'Consolas'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 1
        end
        object lblValRangeTop: TPanel
          Left = 0
          Top = 0
          Width = 185
          Height = 41
          Align = alLeft
          BevelOuter = bvNone
          Caption = 'R 00000'
          Font.Charset = ANSI_CHARSET
          Font.Color = clWhite
          Font.Height = -17
          Font.Name = 'Consolas'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 2
          ExplicitLeft = 88
        end
      end
    end
    object Panel2: TPanel
      Left = 640
      Top = 0
      Width = 640
      Height = 480
      BevelOuter = bvNone
      Caption = 'pnlViewer3D'
      Color = clBlack
      ParentBackground = False
      TabOrder = 1
      object Shape3: TShape
        Left = 325
        Top = 0
        Width = 1
        Height = 501
        Pen.Color = clWhite
        Visible = False
      end
      object Shape4: TShape
        Left = 0
        Top = 251
        Width = 649
        Height = 1
        Pen.Color = clWhite
        Visible = False
      end
    end
  end
  object pnlBite: TPanel
    Left = 642
    Top = 626
    Width = 213
    Height = 351
    ParentBackground = False
    TabOrder = 2
    object pnlHaeaderBite: TPanel
      Left = 1
      Top = 1
      Width = 211
      Height = 28
      Align = alTop
      Caption = 'BITE'
      Color = clHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      ExplicitWidth = 449
    end
  end
  object pnlExteriorData: TPanel
    Left = 642
    Top = 484
    Width = 638
    Height = 143
    ParentBackground = False
    TabOrder = 1
    object pnlHeaderExteriorData: TPanel
      Left = 1
      Top = 1
      Width = 636
      Height = 28
      Align = alTop
      Caption = 'EXTERIOR DATA &&  INTERNAL COMMUNICATIONS'
      Color = clHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      ExplicitWidth = 447
    end
  end
  object pnlBearElev: TPanel
    Left = 0
    Top = 484
    Width = 640
    Height = 478
    BevelOuter = bvNone
    Color = clBlack
    ParentBackground = False
    TabOrder = 3
    object vrAngularElev: TVrAngularMeter
      Left = 219
      Top = 1
      Width = 443
      Height = 408
      MaxValue = 90.000000000000000000
      MinValue = -90.000000000000000000
      Decimals = 0
      Angle = 180
      AngleOffset = 180
      Spacing = 30
      Ticks = 180
      TicksMin = 1
      TicksMax = 3
      TicksEnlarge = 5
      ColorZone1 = clLime
      ColorZone2 = clRed
      ColorZone3 = clSkyBlue
      Percent1 = 50
      Percent2 = 50
      Labels = 0
      LabelsOffset = 15
      NeedleBaseWidth = 1
      NeedleColor = clWhite
      CenterDotWidth = 1
      LabelsFont.Charset = DEFAULT_CHARSET
      LabelsFont.Color = clWhite
      LabelsFont.Height = -11
      LabelsFont.Name = 'Tahoma'
      LabelsFont.Style = []
      Color = clNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
    end
    object vrAngularBearing: TVrAngularMeter
      Left = -18
      Top = 1
      Width = 443
      Height = 408
      MaxValue = 180.000000000000000000
      MinValue = -180.000000000000000000
      Decimals = 0
      Angle = 0
      AngleOffset = 360
      Spacing = 30
      Ticks = 360
      TicksMin = 1
      TicksMax = 3
      TicksEnlarge = 5
      ColorZone1 = clRed
      ColorZone2 = clLime
      ColorZone3 = clSkyBlue
      Percent1 = 50
      Percent2 = 50
      Labels = 12
      LabelsOffset = 15
      NeedleBaseWidth = 1
      NeedleColor = clWhite
      CenterDotWidth = 1
      LabelsFont.Charset = DEFAULT_CHARSET
      LabelsFont.Color = clWhite
      LabelsFont.Height = -11
      LabelsFont.Name = 'Tahoma'
      LabelsFont.Style = []
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
    end
    object lineBearHor: TShape
      Left = 28
      Top = 205
      Width = 350
      Height = 1
      Pen.Color = clWhite
    end
    object lineBearVer: TShape
      Left = 203
      Top = 30
      Width = 1
      Height = 350
      Pen.Color = clWhite
    end
    object lineElevVer: TShape
      Left = 440
      Top = 30
      Width = 1
      Height = 350
      Pen.Color = clWhite
    end
    object lineElevHor: TShape
      Left = 440
      Top = 205
      Width = 175
      Height = 1
      Pen.Color = clWhite
    end
    object pnlValBearElev: TPanel
      Left = 0
      Top = 437
      Width = 640
      Height = 41
      Align = alBottom
      BevelOuter = bvNone
      Caption = 'pnlValBearElev'
      TabOrder = 0
      ExplicitLeft = 232
      ExplicitTop = 224
      ExplicitWidth = 185
      object pnlValBearingBottom: TPanel
        Left = 0
        Top = 0
        Width = 361
        Height = 41
        Align = alLeft
        BevelOuter = bvNone
        Caption = 'BE:      0.00 deg'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWhite
        Font.Height = -17
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
      end
      object pnlValElevBottom: TPanel
        Left = 361
        Top = 0
        Width = 279
        Height = 41
        Align = alClient
        BevelOuter = bvNone
        Caption = 'EL:    0.00 deg'
        Font.Charset = ANSI_CHARSET
        Font.Color = clWhite
        Font.Height = -17
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        ExplicitLeft = 280
        ExplicitWidth = 360
      end
    end
    object lbl0: TPanel
      Left = 612
      Top = 189
      Width = 25
      Height = 33
      AutoSize = True
      BevelOuter = bvNone
      Caption = '0'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object lblMin30: TPanel
      Left = 595
      Top = 286
      Width = 25
      Height = 33
      AutoSize = True
      BevelOuter = bvNone
      Caption = '-30'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
    end
    object lbl90: TPanel
      Left = 426
      Top = -2
      Width = 25
      Height = 33
      AutoSize = True
      BevelOuter = bvNone
      Caption = '90'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
    end
    object lbl60: TPanel
      Left = 524
      Top = 24
      Width = 25
      Height = 33
      AutoSize = True
      BevelOuter = bvNone
      Caption = '60'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
    end
    object lbl30: TPanel
      Left = 596
      Top = 98
      Width = 25
      Height = 33
      AutoSize = True
      BevelOuter = bvNone
      Caption = '30'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 5
    end
    object lblMin90: TPanel
      Left = 427
      Top = 375
      Width = 25
      Height = 33
      AutoSize = True
      BevelOuter = bvNone
      Caption = '-90'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
    end
    object lblMin60: TPanel
      Left = 526
      Top = 354
      Width = 25
      Height = 33
      AutoSize = True
      BevelOuter = bvNone
      Caption = '-60'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 960
    Width = 640
    Height = 64
    ParentBackground = False
    TabOrder = 4
    object Panel4: TPanel
      Left = 1
      Top = 1
      Width = 638
      Height = 28
      Align = alTop
      Caption = 'EXTERIOR DATA &&  INTERNAL COMMUNICATIONS'
      Color = clHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      ExplicitLeft = -119
      ExplicitTop = 49
      ExplicitWidth = 450
    end
  end
  object Panel5: TPanel
    Left = 855
    Top = 626
    Width = 213
    Height = 351
    ParentBackground = False
    TabOrder = 5
    object Panel6: TPanel
      Left = 1
      Top = 1
      Width = 211
      Height = 28
      Align = alTop
      Caption = 'BITE'
      Color = clHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
    end
  end
  object Panel7: TPanel
    Left = 1068
    Top = 626
    Width = 212
    Height = 351
    ParentBackground = False
    TabOrder = 6
    object Panel8: TPanel
      Left = 1
      Top = 1
      Width = 210
      Height = 28
      Align = alTop
      Caption = 'BITE'
      Color = clHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      ExplicitWidth = 211
    end
  end
  object tmrUpdateShipPos: TTimer
    Interval = 500
    OnTimer = UpdatePosition
    Left = 808
    Top = 384
  end
  object tmrUpdateForm: TTimer
    OnTimer = tmrUpdateFormTimer
    Left = 737
    Top = 409
  end
end
