//NFS MOC4 PROG
[CONFIG]
SERVER=127.0.0.1
SERVERPORT=2120
3DSERVER=127.0.0.1
3DSERVERPORT=7002
[DBCONFIG]
DBSERVER=127.0.0.1
DBPROTO=mysql
DBNAME=ZGJOU3VGcw==
DBUSER=cm9vdA==
;DBPASS=VDNzZXJ2ZXIh
DBPASS=YWRtaW4=
[SHIPS]
SHIPID=41
SHIPNAME=Raden Eddy Martadinata
SHIPCLASSID=10
SHIPCLASSNAME=Martadinata