object frmMain: TfrmMain
  Left = 1068
  Top = 176
  Hint = 'Client 3D'
  BorderIcons = []
  BorderStyle = bsNone
  Caption = '3D :: Launcher'
  ClientHeight = 513
  ClientWidth = 367
  Color = clGray
  TransparentColorValue = clGray
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PopupMenu = PopupMenu1
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object pnlMain: TAdvSmoothPanel
    Left = 0
    Top = 0
    Width = 367
    Height = 513
    Cursor = crDefault
    Caption.HTMLFont.Charset = DEFAULT_CHARSET
    Caption.HTMLFont.Color = clWindowText
    Caption.HTMLFont.Height = -11
    Caption.HTMLFont.Name = 'Tahoma'
    Caption.HTMLFont.Style = []
    Caption.Font.Charset = DEFAULT_CHARSET
    Caption.Font.Color = clWindowText
    Caption.Font.Height = -16
    Caption.Font.Name = 'Tahoma'
    Caption.Font.Style = []
    Fill.Color = clWhite
    Fill.ColorTo = clBlack
    Fill.ColorMirror = clNone
    Fill.ColorMirrorTo = clNone
    Fill.GradientType = gtHorizontal
    Fill.GradientMirrorType = gtVertical
    Fill.Opacity = 132
    Fill.OpacityTo = 129
    Fill.BorderColor = clNone
    Fill.Rounding = 0
    Fill.ShadowOffset = 0
    Fill.Glow = gmNone
    Version = '1.6.0.1'
    Align = alClient
    TabOrder = 1
    TMSStyle = 0
  end
  object Panel3: TPanel
    Left = 0
    Top = 0
    Width = 367
    Height = 513
    Align = alClient
    BevelOuter = bvNone
    BorderWidth = 1
    Color = clGray
    ParentBackground = False
    TabOrder = 0
    OnMouseDown = MoveForm
    object Panel1: TPanel
      Left = 1
      Top = 1
      Width = 365
      Height = 511
      Align = alClient
      BevelOuter = bvNone
      Color = clGray
      TabOrder = 0
      object Panel2: TPanel
        Left = 0
        Top = 0
        Width = 365
        Height = 60
        Align = alTop
        BevelOuter = bvNone
        Color = clGray
        ParentBackground = False
        TabOrder = 0
        OnDblClick = Panel2DblClick
        OnMouseDown = MoveForm
        object pnlMenu: TAdvSmoothPanel
          Left = 0
          Top = 23
          Width = 365
          Height = 37
          Cursor = crDefault
          Caption.Location = plCenterLeft
          Caption.HTMLFont.Charset = DEFAULT_CHARSET
          Caption.HTMLFont.Color = clWindowText
          Caption.HTMLFont.Height = -11
          Caption.HTMLFont.Name = 'Tahoma'
          Caption.HTMLFont.Style = []
          Caption.Font.Charset = DEFAULT_CHARSET
          Caption.Font.Color = clWindowText
          Caption.Font.Height = -13
          Caption.Font.Name = 'Arial'
          Caption.Font.Style = [fsBold]
          Caption.ColorStart = clWhite
          Caption.ColorEnd = clWhite
          Caption.Line = False
          Fill.Color = clBlack
          Fill.ColorTo = clBlack
          Fill.ColorMirror = clBlack
          Fill.ColorMirrorTo = clBlack
          Fill.GradientType = gtVertical
          Fill.GradientMirrorType = gtVertical
          Fill.Opacity = 101
          Fill.OpacityTo = 243
          Fill.OpacityMirror = 243
          Fill.OpacityMirrorTo = 203
          Fill.BorderColor = clNone
          Fill.Rounding = 3
          Fill.ShadowColor = clNone
          Fill.ShadowOffset = 0
          Fill.Glow = gmNone
          Fill.GlowGradientColor = clNone
          Version = '1.6.0.1'
          Align = alClient
          OnDblClick = Panel2DblClick
          OnMouseDown = MoveForm
          TabOrder = 4
          TMSStyle = 0
        end
        object spb2DServer: TPanel
          Left = 1
          Top = 29
          Width = 150
          Height = 33
          Cursor = crHandPoint
          BevelOuter = bvNone
          Caption = '2D SERVER :: OFFLINE'
          Color = clDefault
          Ctl3D = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindow
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentBackground = False
          ParentCtl3D = False
          ParentFont = False
          TabOrder = 1
          Visible = False
        end
        object btnClose: TPanel
          Left = 399
          Top = 2
          Width = 80
          Height = 33
          Cursor = crHandPoint
          Caption = 'CLOSE'
          TabOrder = 0
          Visible = False
          OnClick = btnCloseClick
        end
        object cbDebug: TCheckBox
          Left = 315
          Top = 34
          Width = 45
          Height = 17
          Alignment = taLeftJustify
          Caption = 'Debug'
          TabOrder = 2
          Visible = False
          OnClick = cbDebugClick
        end
        object spbDBServer: TPanel
          Left = 155
          Top = 29
          Width = 150
          Height = 33
          Cursor = crHandPoint
          BevelOuter = bvNone
          Caption = 'DB SERVER :: OFFLINE'
          Color = clDefault
          Ctl3D = False
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindow
          Font.Height = -13
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentBackground = False
          ParentCtl3D = False
          ParentFont = False
          TabOrder = 3
          Visible = False
        end
        object pnlStatus: TPanel
          Left = 0
          Top = 0
          Width = 365
          Height = 23
          Align = alTop
          BevelOuter = bvNone
          Color = clGray
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindow
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 5
          OnMouseDown = MoveForm
        end
      end
      object pnl1: TPanel
        Left = 0
        Top = 60
        Width = 365
        Height = 451
        Align = alClient
        BevelOuter = bvNone
        BorderWidth = 1
        Caption = 'pnl1'
        Color = clBlack
        ParentBackground = False
        TabOrder = 1
        object pnlMemo: TPanel
          Left = 1
          Top = 1
          Width = 363
          Height = 449
          Align = alClient
          BevelOuter = bvNone
          Caption = 'pnlMemo'
          TabOrder = 0
          object Memo1: TMemo
            Left = 0
            Top = 0
            Width = 363
            Height = 356
            Align = alClient
            BevelInner = bvNone
            BevelOuter = bvNone
            BorderStyle = bsNone
            Color = clGray
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clSilver
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            ReadOnly = True
            TabOrder = 0
          end
          object Memo2: TMemo
            Left = 0
            Top = 356
            Width = 363
            Height = 93
            Align = alBottom
            BevelInner = bvNone
            BevelOuter = bvNone
            BorderStyle = bsNone
            Color = clGray
            Ctl3D = False
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clSilver
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentCtl3D = False
            ParentFont = False
            ReadOnly = True
            TabOrder = 1
            Visible = False
          end
        end
      end
    end
  end
  object TmrCheckConnect: TTimer
    Enabled = False
    OnTimer = TmrCheckConnectTimer
    Left = 64
    Top = 104
  end
  object PopupMenu1: TPopupMenu
    Left = 152
    Top = 104
    object ShowHideScroll1: TMenuItem
      Caption = 'Show/Hide Scroll'
      OnClick = ShowHideScroll1Click
    end
    object N1: TMenuItem
      Caption = '-'
    end
    object Minimize1: TMenuItem
      Caption = 'Minimize'
      OnClick = Minimize1Click
    end
    object Close1: TMenuItem
      Caption = 'Close'
      OnClick = Close1Click
    end
  end
end
